### ISSUE TITLE
[Test Flake] GCP deployer script resource conflict setting IAM policy

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1140]
https://github.com/kubeflow/kubeflow/pull/1109

Got the following test flake

````
gcloud services operations describe operations/tmo-acf.982d2d0f-6f2d-41a4-bccb-3c30b8e33130
+ gcloud projects add-iam-policy-binding kubeflow-ci --member serviceAccount:593963025935@cloudservices.gserviceaccount.com --role roles/resourcemanager.projectIamAdmin
ERROR: (gcloud.projects.add-iam-policy-binding) Resource in project [kubeflow-ci:setIamPolicy] is the subject of a conflict: There were concurrent policy changes. Please retry the whole r
ead-modify-write with exponential backoff.
Traceback (most recent call last):
 File "/mnt/test-data-volume/kubeflow-presubmit-kubeflow-e2e-gke-1109-866b43a-2401-ac17/src/kubeflow/testing/py/kubeflow/testing/test_helper.py", line 96, in wrap_test
   test_case.test_func(test_case)
 File "/mnt/test-data-volume/kubeflow-presubmit-kubeflow-e2e-gke-1109-866b43a-2401-ac17/src/kubeflow/kubeflow/testing/run_with_retry.py", line 40, in run_with_retry
   run()
 File "/usr/local/lib/python2.7/dist-packages/retrying.py", line 49, in wrapped_f
   return Retrying(*dargs, **dkw).call(f, *args, **kw)
 File "/usr/local/lib/python2.7/dist-packages/retrying.py", line 212, in call
   raise attempt.get()
 File "/usr/local/lib/python2.7/dist-packages/retrying.py", line 247, in get
   six.reraise(self.value[0], self.value[1], self.value[2])
 File "/usr/local/lib/python2.7/dist-packages/retrying.py", line 200, in call
   attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
 File "/mnt/test-data-volume/kubeflow-presubmit-kubeflow-e2e-gke-1109-866b43a-2401-ac17/src/kubeflow/kubeflow/testing/run_with_retry.py", line 38, in run
   util.run(args.remaining_args[1:])
 File "/mnt/test-data-volume/kubeflow-presubmit-kubeflow-e2e-gke-1109-866b43a-2401-ac17/src/kubeflow/testing/py/kubeflow/testing/util.py", line 74, in run
   " ".join(command), process.returncode), "\n".join(output))
CalledProcessError: Command 'cmd: bash /mnt/test-data-volume/kubeflow-presubmit-kubeflow-e2e-gke-1109-866b43a-2401-ac17/src/kubeflow/kubeflow/testing/deploy_kubeflow_gcp.sh e2e-ac17 /mnt/
test-data-volume/kubeflow-presubmit-kubeflow-e2e-gke-1109-866b43a-2401-ac17/src/kubeflow/kubeflow v1alpha1 gcr.io/kubeflow-ci/bootstrapper:kubeflow-presubmit-kubeflow-e2e-gke-1109-866b43a
-2401-ac17 exited with code 1' returned non-zero exit status 1
Traceback (most recent call last):
 File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
   "__main__", fname, loader, pkg_name)
 File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
   exec code in run_globals
````

We should add some backoff and retry to the setIamPolicy in the script.

**Comment by jlewi** [comment]
It looks like this being done as part of initializing the project.
https://github.com/kubeflow/kubeflow/blob/5a11d74220480212f2e56048fe08a162b934d224/scripts/gke/util.sh#L33

I don't think this should be needed anymore. I think we were granting the cloud services account Iam project admin permission so that we could set IAM policies using deployment manager but we no longer do that. So we should just be able to delete that line.
