### ISSUE TITLE
Spawning Jupyter failed; user jovyan does not have permission to write to default storage class

### ISSUE THREAD

**Issue by antigenius0910** [kubeflow/kubeflow#1241]
Hi,

First thank you so much for this kubeflow project. It looks amazing.
I followed your official instruction and got kubeflow installed and all default services and pods looks fine.

The only problem I am facing now is I can't get JupyterHub to start a Jupyter Notebook server

Below are my kubernates status and all logs I've know how to pull out.

Really appreciate if anybody can point me steps to start troubleshooting this issue. Thanks

```
Every 2.0s: kubectl -n default get po,svc,deploy,pv,pvc -o wide                                                                                            Thu Jul 19 15:35:02 2018

NAME                                                   READY     STATUS             RESTARTS   AGE       IP               NODE
pod/ambassador-56ccfbc448-bqj52                        2/2       Running            0          23h       10.1.41.22       bubnicki
pod/ambassador-56ccfbc448-g9g7d                        2/2       Running            0          23h       10.1.3.11        zalewski
pod/ambassador-56ccfbc448-vfr95                        2/2       Running            0          23h       10.1.41.23       bubnicki
pod/centraldashboard-57696464f5-sfc45                  1/1       Running            0          23h       10.1.3.10        zalewski
pod/default-http-backend-hbnvp                         1/1       Running            0          2d        10.1.41.2        bubnicki
pod/jupyter-test11                                     0/1       CrashLoopBackOff   6          6m        10.1.3.15        zalewski
pod/nginx-ingress-kubernetes-worker-controller-llwwb   1/1       Running            0          2d        172.29.100.129   bubnicki
pod/nginx-ingress-kubernetes-worker-controller-r4tqm   1/1       Running            0          2d        172.29.100.138   zalewski
pod/tf-hub-0                                           1/1       Running            0          23h       10.1.41.21       bubnicki
pod/tf-job-dashboard-7db5b474c8-75h8j                  1/1       Running            0          23h       10.1.3.12        zalewski
pod/tf-job-operator-v1alpha2-7954bdcf76-74svl          1/1       Running            0          23h       10.1.3.9         zalewski

NAME                           TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE       SELECTOR
service/ambassador             ClusterIP   10.152.183.53    <none>        80/TCP         23h       service=ambassador
service/ambassador-admin       ClusterIP   10.152.183.149   <none>        8877/TCP       23h       service=ambassador
service/centraldashboard       ClusterIP   10.152.183.113   <none>        80/TCP         23h       app=centraldashboard
service/default-http-backend   ClusterIP   10.152.183.137   <none>        80/TCP         2d        app=default-http-backend
service/k8s-dashboard          ClusterIP   10.152.183.26    <none>        443/TCP        23h       k8s-app=kubernetes-dashboard
service/kubernetes             ClusterIP   10.152.183.1     <none>        443/TCP        2d        <none>
service/tf-hub-0               ClusterIP   None             <none>        8000/TCP       23h       app=tf-hub
service/tf-hub-lb              NodePort    10.152.183.196   <none>        80:30508/TCP   23h       app=tf-hub
service/tf-job-dashboard       ClusterIP   10.152.183.200   <none>        80/TCP         23h       name=tf-job-dashboard

NAME                                             DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE       CONTAINERS          IMAGES
             SELECTOR
deployment.extensions/ambassador                 3         3         3            3           23h       ambassador,statsd   quay.io/datawire/ambassador:0.30.1,quay.io/datawire/sta
tsd:0.30.1   service=ambassador
deployment.extensions/centraldashboard           1         1         1            1           23h       centraldashboard    gcr.io/kubeflow-images-public/centraldashboard:v0.2.1
             app=centraldashboard
deployment.extensions/tf-job-dashboard           1         1         1            1           23h       tf-job-dashboard    gcr.io/kubeflow-images-public/tf_operator:v0.2.0
             name=tf-job-dashboard
deployment.extensions/tf-job-operator-v1alpha2   1         1         1            1           23h       tf-job-operator     gcr.io/kubeflow-images-public/tf_operator:v0.2.0
             name=tf-job-operator

NAME                      CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM                  STORAGECLASS   REASON    AGE
persistentvolume/nfs-pv   30Gi       RWO            Retain           Bound     default/claim-test11                            19m

NAME                                 STATUS    VOLUME    CAPACITY   ACCESS MODES   STORAGECLASS   AGE
persistentvolumeclaim/claim-test11   Bound     nfs-pv    30Gi       RWO                           6m
```

After I pick up the image and request CPU and Memory the pod trying to start but seems like it always ended in 'error'

```
Every 2.0s: kubectl describe po/jupyter-test11                                                                                                             Thu Jul 19 15:36:28 2018

Name:         jupyter-test11
Namespace:    default
Node:         zalewski/172.29.100.138
Start Time:   Thu, 19 Jul 2018 15:28:15 +0000
Labels:       app=jupyterhub
              component=singleuser-server
              heritage=jupyterhub
Annotations:  hub.jupyter.org/username=test11
Status:       Running
IP:           10.1.3.15
Containers:
  notebook:
    Container ID:  docker://78e980d4e6a236a956d73accee043b6ed50b17969d09dcdb3f65e5eee035eae5
    Image:         gcr.io/kubeflow-images-public/tensorflow-1.8.0-notebook-gpu:v0.2.1
    Image ID:      docker-pullable://gcr.io/kubeflow-images-public/tensorflow-1.8.0-notebook-gpu@sha256:63b30b10b0b597a4d52701c8bb2cfa40826ce39f9b33d66a3648c30e2e0e28d3
    Port:          8888/TCP
    Host Port:     0/TCP
    Args:
      start-singleuser.sh
      --ip="0.0.0.0"
      --port=8888
      --allow-root
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 19 Jul 2018 15:33:59 +0000
      Finished:     Thu, 19 Jul 2018 15:34:00 +0000
    Ready:          False
    Restart Count:  6
    Limits:
      nvidia.com/gpu:  1
    Requests:
      cpu:             1
      memory:          1536Mi
      nvidia.com/gpu:  1
    Environment:
      JUPYTERHUB_API_TOKEN:           60c0146617a74fc0b52594f4cd2b0315
      JPY_API_TOKEN:                  60c0146617a74fc0b52594f4cd2b0315
      JUPYTERHUB_CLIENT_ID:           jupyterhub-user-test11
      JUPYTERHUB_HOST:
      JUPYTERHUB_OAUTH_CALLBACK_URL:  /user/test11/oauth_callback
      JUPYTERHUB_USER:                test11
      JUPYTERHUB_API_URL:             http://tf-hub-0:8081/hub/api
      JUPYTERHUB_BASE_URL:            /
      JUPYTERHUB_SERVICE_PREFIX:      /user/test11/
      MEM_GUARANTEE:                  1.5Gi
      CPU_GUARANTEE:                  1.0
    Mounts:
      /home/jovyan from volume-test11 (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from no-api-access-please (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  volume-test11:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  claim-test11
    ReadOnly:   false
  no-api-access-please:
    Type:        EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age               From               Message
  ----     ------     ----              ----               -------
  Normal   Scheduled  8m                default-scheduler  Successfully assigned default/jupyter-test11 to zalewski
  Normal   Pulled     6m (x5 over 8m)   kubelet, zalewski  Container image "gcr.io/kubeflow-images-public/tensorflow-1.8.0-notebook-gpu:v0.2.1" already present on machine
  Normal   Created    6m (x5 over 8m)   kubelet, zalewski  Created container
  Normal   Started    6m (x5 over 8m)   kubelet, zalewski  Started container
  Warning  BackOff    3m (x26 over 8m)  kubelet, zalewski  Back-off restarting failed container
```
 
When I check the log, it show as above but I don't really know what is the next step for troubleshooting.

```
$ kubectl logs -f pod/jupyter-test11   
checking if /home/jovyan volume needs init...
.../home/jovyan already has content...
...done
Execute the command
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'runtime_dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/jupyterhub-singleuser", line 6, in <module>
    main()
  File "/opt/conda/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 495, in main
    return SingleUserNotebookApp.launch_instance(argv)
  File "/opt/conda/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "/opt/conda/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 402, in initialize
    return super().initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/opt/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1535, in initialize
    self.init_configurables()
  File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1233, in init_configurables
    connection_dir=self.runtime_dir,
  File "/opt/conda/lib/python3.6/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/opt/conda/lib/python3.6/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/opt/conda/lib/python3.6/site-packages/jupyter_core/application.py", line 99, in _runtime_dir_default
    ensure_dir_exists(rd, mode=0o700)
  File "/opt/conda/lib/python3.6/site-packages/jupyter_core/utils/__init__.py", line 13, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/opt/conda/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/opt/conda/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/opt/conda/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/opt/conda/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/jovyan/.local'
```

logs from pod/tf-hub-0. 

```
$ kubectl logs -f pod/tf-hub-0 
I 2018-07-19 15:28:08.117 JupyterHub base:498] User logged in: test11
[I 2018-07-19 15:28:08.118 JupyterHub log:158] 302 POST /hub/login?next= -> /user/test11/ (test11@10.1.3.0) 16.95ms
[I 2018-07-19 15:28:08.138 JupyterHub log:158] 302 GET /user/test11/ -> /hub/user/test11/ (@10.1.3.0) 0.66ms
[W 2018-07-19 15:28:08.168 JupyterHub configurable:168] Config option `singleuser_image_spec` not recognized by `KubeFormSpawner`.  Did you mean one of: `singleuser_image_pull_policy, singleuser_image_pull_secrets, singleuser_node_selector`?
[I 2018-07-19 15:28:08.169 JupyterHub log:158] 302 GET /hub/user/test11/ -> /hub/spawn?next=%2Fhub%2Fuser%2Ftest11%2F (test11@10.1.3.0) 13.50ms
[I 2018-07-19 15:28:08.206 JupyterHub log:158] 200 GET /hub/spawn?next=%2Fhub%2Fuser%2Ftest11%2F (test11@10.1.3.0) 5.14ms
[W 2018-07-19 15:28:25.080 JupyterHub base:678] User test11 is slow to start (timeout=10)
[I 2018-07-19 15:28:25.091 JupyterHub log:158] 302 POST /hub/spawn?next=%2Fhub%2Fuser%2Ftest11%2F -> /hub/user/test11/ (test11@10.1.3.0) 10025.35ms
[I 2018-07-19 15:28:35.212 JupyterHub base:951] Pending spawn for test11 didn't finish in 10.0 seconds
[I 2018-07-19 15:28:35.212 JupyterHub base:956] test11 is pending spawn
[I 2018-07-19 15:28:35.215 JupyterHub log:158] 200 GET /hub/user/test11/ (test11@10.1.3.0) 10010.33ms
15:29:37.351 - info: [ConfigProxy] 200 GET /api/routes 
[I 2018-07-19 15:29:37.352 JupyterHub proxy:299] Checking routes
2018-07-19 15:31:14,335 WARNING Connection pool is full, discarding connection: 10.152.183.1
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: 10.152.183.1
[I 2018-07-19 15:31:14.335 JupyterHub reflector:129] watching for pods with label selector heritage=jupyterhub,component=singleuser-server in namespace default
15:34:37.351 - info: [ConfigProxy] 200 GET /api/routes 
[I 2018-07-19 15:34:37.352 JupyterHub proxy:299] Checking routes
[W 2018-07-19 15:39:29.388 JupyterHub user:504] test11's server never showed up at http://10.1.3.15:8888/user/test11/ after 300 seconds. Giving up
15:39:37.354 - info: [ConfigProxy] 200 GET /api/routes 
[I 2018-07-19 15:39:37.354 JupyterHub proxy:299] Checking routes
[E 2018-07-19 15:39:41.434 JupyterHub gen:940] Exception in Future <Task finished coro=<BaseHandler.spawn_single_user.<locals>.finish_user_spawn() done, defined at /opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py:618> exception=TimeoutError("Server at http://10.1.3.15:8888/user/test11/ didn't respond in 300 seconds",)> after timeout
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 936, in error_callback
        future.result()
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 625, in finish_user_spawn
        await spawn_future
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/user.py", line 522, in spawn
        raise e
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/user.py", line 496, in spawn
        resp = await server.wait_up(http=True, timeout=spawner.http_timeout)
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/utils.py", line 197, in wait_for_http_server
        timeout=timeout
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/utils.py", line 155, in exponential_backoff
        raise TimeoutError(fail_message)
    TimeoutError: Server at http://10.1.3.15:8888/user/test11/ didn't respond in 300 seconds

```

**Comment by jlewi** [comment]
The problem is your home directory is being backed by a persistent volume. The container is running as user jovyan and it looks like this doesn't have permissions to write to the PD.

Try doing the following

```
ks param set kubeflow-core jupyterNotebookPVCMount /home/jovyan/work
ks apply ${ENV} -c ${KUBEFLOW_COMPONENT}
```

This will cause the PV to be mounted at /home/jovyan. Note that a consequence of this is that data in root of your home directory (/home/jovyan) won't be on PV and will be lost if your pod restarts.

Can you provide more information about cluster setup in perticular the permission model with respect to the default storage class. I'd like to figure out how to better address this use case.

/cc @pdmack

**Comment by antigenius0910** [comment]
Hi @jlewi ,

you are 100% correct. we are using NFS for the creating the pv and once I change the folder permission to 777 the container come up right away. THANK YOU!!!

```
ychuang@Kubernetes-master:/opt$ kubectl describe pod/jupyter-test13
Name:         jupyter-test13
Namespace:    default
Node:         bubnicki/172.29.100.129
Start Time:   Fri, 20 Jul 2018 20:53:44 +0000
Labels:       app=jupyterhub
              component=singleuser-server
              heritage=jupyterhub
Annotations:  hub.jupyter.org/username=test13
Status:       Running
IP:           10.1.41.29
Containers:
  notebook:
    Container ID:  docker://c89471c44bee4e3acb4db572563bde8a48f9295a79cdc36850ef444b6201435c
    Image:         gcr.io/kubeflow-images-public/tensorflow-1.8.0-notebook-gpu:v0.2.1
    Image ID:      docker-pullable://gcr.io/kubeflow-images-public/tensorflow-1.8.0-notebook-gpu@sha256:63b30b10b0b597a4d52701c8bb2cfa40826ce39f9b33d66a3648c30e2e0e28d3
    Port:          8888/TCP
    Host Port:     0/TCP
    Args:
      start-singleuser.sh
      --ip="0.0.0.0"
      --port=8888
      --allow-root
    State:          Running
      Started:      Fri, 20 Jul 2018 20:53:45 +0000
    Ready:          True
    Restart Count:  0
    Limits:
      nvidia.com/gpu:  1
    Requests:
      cpu:             1
      memory:          1536Mi
      nvidia.com/gpu:  1
    Environment:
      JUPYTERHUB_API_TOKEN:           c85323a22ca046148f9b7c7ae2d000cf
      JPY_API_TOKEN:                  c85323a22ca046148f9b7c7ae2d000cf
      JUPYTERHUB_CLIENT_ID:           jupyterhub-user-test13
      JUPYTERHUB_HOST:                
      JUPYTERHUB_OAUTH_CALLBACK_URL:  /user/test13/oauth_callback
      JUPYTERHUB_USER:                test13
      JUPYTERHUB_API_URL:             http://tf-hub-0:8081/hub/api
      JUPYTERHUB_BASE_URL:            /
      JUPYTERHUB_SERVICE_PREFIX:      /user/test13/
      MEM_GUARANTEE:                  1.5Gi
      CPU_GUARANTEE:                  1.0
    Mounts:
      /home/jovyan from volume-test13 (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from no-api-access-please (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  volume-test13:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  claim-test13
    ReadOnly:   false
  no-api-access-please:
    Type:        EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:      
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  15s   default-scheduler  pod has unbound PersistentVolumeClaims (repeated 2 times)
  Normal   Scheduled         15s   default-scheduler  Successfully assigned default/jupyter-test13 to bubnicki
  Normal   Pulled            14s   kubelet, bubnicki  Container image "gcr.io/kubeflow-images-public/tensorflow-1.8.0-notebook-gpu:v0.2.1" already present on machine
  Normal   Created           14s   kubelet, bubnicki  Created container
  Normal   Started           14s   kubelet, bubnicki  Started container
```

**Comment by jlewi** [comment]
Fantastic.

**Comment by AnnieWei58** [comment]
> The problem is your home directory is being backed by a persistent volume. The container is running as user jovyan and it looks like this doesn't have permissions to write to the PD.
> 
> Try doing the following
> 
> ```
> ks param set kubeflow-core jupyterNotebookPVCMount /home/jovyan/work
> ks apply ${ENV} -c ${KUBEFLOW_COMPONENT}
> ```
> 
> This will cause the PV to be mounted at /home/jovyan. Note that a consequence of this is that data in root of your home directory (/home/jovyan) won't be on PV and will be lost if your pod restarts.
> 
> Can you provide more information about cluster setup in perticular the permission model with respect to the default storage class. I'd like to figure out how to better address this use case.
> 
> /cc @pdmack

Hi,
I tried this line: 
> ks param set kubeflow-core jupyterNotebookPVCMount /home/jovyan/work
but, it gives me the following error:
![image](https://user-images.githubusercontent.com/24437370/62751835-c46fcc80-ba97-11e9-8ce2-805d0db64d95.png)

**Comment by AnnieWei58** [comment]
> The problem is your home directory is being backed by a persistent volume. The container is running as user jovyan and it looks like this doesn't have permissions to write to the PD.
> 
> Try doing the following
> 
> ```
> ks param set kubeflow-core jupyterNotebookPVCMount /home/jovyan/work
> ks apply ${ENV} -c ${KUBEFLOW_COMPONENT}
> ```
> 
> This will cause the PV to be mounted at /home/jovyan. Note that a consequence of this is that data in root of your home directory (/home/jovyan) won't be on PV and will be lost if your pod restarts.
> 
> Can you provide more information about cluster setup in perticular the permission model with respect to the default storage class. I'd like to figure out how to better address this use case.
> 
> /cc @pdmack

Hi @jlewi , I tried this line of code:
> ks param set kubeflow-core jupyterNotebookPVCMount /home/jovyan/work

-But it gives the following result:
![image](https://user-images.githubusercontent.com/24437370/62751985-48c24f80-ba98-11e9-8124-66cbbf8a0508.png)

**Comment by jlewi** [comment]
@AnnieWei58 If you have a question please open a new issue. I would also suggest trying 0.6 rather than 0.5.
