### ISSUE TITLE
[Test flake] unable to recognize XX: no matches for kind Workflow

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#1278]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/kubeflow_kubeflow/1229/kubeflow-presubmit/2728/

```
INFO|2018-07-27T18:25:13|/src/kubeflow/testing/py/kubeflow/testing/util.py|62| persistentVolumeClaim:
INFO|2018-07-27T18:25:13|/src/kubeflow/testing/py/kubeflow/testing/util.py|62| claimName: nfs-external
INFO|2018-07-27T18:25:14|/src/kubeflow/testing/py/kubeflow/testing/util.py|41| Running: ks apply kubeflow-presubmit-kubeflow-e2e-gke-1229-d837edc-2728-1a8f -c workflows 
cwd=/src/kubeflow/kubeflow/testing/workflows
INFO|2018-07-27T18:25:14|/src/kubeflow/testing/py/kubeflow/testing/util.py|56| Subprocess output:

INFO|2018-07-27T18:25:30|/src/kubeflow/testing/py/kubeflow/testing/util.py|62| level=error msg="handle object: merging object with existing state: unable to recognize \"/tmp/ksonnet-mergepatch556415580\": no matches for kind \"Workflow\" in version \"argoproj.io/v1alpha1\""
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 344, in <module>
```

**Comment by lluunn** [comment]
Weird, the workflow is running again. That failure seems temporary, but it causes presubmit failure.

#1229
