### ISSUE TITLE
How to spawn the jupyter container as a root user

### ISSUE THREAD

**Issue by YogeshSomawar** [kubeflow/kubeflow#1412]
Hi,

As part of my development, I would like to spawn the jupyter container as a root user. 
Is there any way to do so.
I tried to by changing the following in kubeform_spawner.py, 

> c.KubeSpawner.singleuser_uid = 0
> c.KubeSpawner.singleuser_fs_gid = 0

But didn't help, with this change container getting exited with following error :
checking if /home/jovyan volume needs init...
.../home/jovyan already has content...
...done
usermod: no changes
Execute the command as jovyan
[W 2018-08-24 08:44:41.445 SingleUserNotebookApp configurable:168] Config option `open_browser` not recognized by `SingleUserNotebookApp`.  Did you mean `browser`?
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'runtime_dir'

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "/opt/conda/bin/jupyterhub-singleuser", line 6, in <module>
    main()
  File "/opt/conda/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 495, in main
    return SingleUserNotebookApp.launch_instance(argv)
  File "/opt/conda/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "/opt/conda/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 402, in initialize
    return super().initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/opt/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1600, in initialize
    self.init_configurables()
  File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1293, in init_configurables
    connection_dir=self.runtime_dir,
  File "/opt/conda/lib/python3.6/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/opt/conda/lib/python3.6/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/opt/conda/lib/python3.6/site-packages/jupyter_core/application.py", line 99, in _runtime_dir_default
    ensure_dir_exists(rd, mode=0o700)
  File "/opt/conda/lib/python3.6/site-packages/jupyter_core/utils/__init__.py", line 13, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/opt/conda/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/opt/conda/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/opt/conda/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/opt/conda/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/jovyan/.local'
```
Could someboday assit me to spawn the jupyter container as a root user.

**Comment by pdmack** [comment]
Are you sure you need to be `root`? The `jovyan` user should be able to pip/conda install packages, if that's what you are after.

**Comment by YogeshSomawar** [comment]
Hello,

Yes, apt-get install.
Also, I tried to install hdfs3 by conda, it is also giving permission denied 
`conda install hdfs3 -c conda-forge -y 
`
```
krb5-1.14.6          |  4.0 MB | ####################################### | 100% 
libssh2-1.8.0        |  240 KB | ####################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: failed
ERROR conda.core.link:_execute(502): An error occurred while installing package 'conda-forge::bzip2-1.0.6-h470a237_2'.
PermissionError(13, 'Permission denied')
Attempting to roll back.

Rolling back transaction: done

PermissionError(13, 'Permission denied')
```

**Comment by pdmack** [comment]
The  `jovyan` user can install hdfs3 with pip using the unmodified uid and fs_gid.

For the apt-get installs you may just want to build your own custom TF notebook image from here:
https://github.com/kubeflow/kubeflow/tree/master/components/tensorflow-notebook-image
