### ISSUE TITLE
Jupyter Image Builds Are failing; Dependency issue related to TFMA?

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1576]
Building our Jupyter Docker Images is Failing. Here's the failure for the TF 1.8 CPU image.

```
Traceback (most recent call last):
 File "/opt/conda/envs/py2/bin/jupyter-nbextension", line 11, in <module>
   sys.exit(main())
 File "/opt/conda/envs/py2/lib/python2.7/site-packages/jupyter_core/application.py", line 266, in launch_instance
   return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
 File "/opt/conda/envs/py2/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
   app.start()
 File "/opt/conda/envs/py2/lib/python2.7/site-packages/notebook/nbextensions.py", line 988, in start
   super(NBExtensionApp, self).start()
 File "/opt/conda/envs/py2/lib/python2.7/site-packages/jupyter_core/application.py", line 255, in start
   self.subapp.start()
 File "/opt/conda/envs/py2/lib/python2.7/site-packages/notebook/nbextensions.py", line 716, in start
    self.install_extensions()
 File "/opt/conda/envs/py2/lib/python2.7/site-packages/notebook/nbextensions.py", line 695, in install_extensions
    **kwargs
 File "/opt/conda/envs/py2/lib/python2.7/site-packages/notebook/nbextensions.py", line 211, in install_nbextension_python
   m, nbexts = _get_nbextension_metadata(module)
 File "/opt/conda/envs/py2/lib/python2.7/site-packages/notebook/nbextensions.py", line 1122, in _get_nbextension_metadata
   m = import_item(module)
 File "/opt/conda/envs/py2/lib/python2.7/site-packages/traitlets/utils/importstring.py", line 42, in import_item
   return __import__(parts[0])
 File "/opt/conda/envs/py2/lib/python2.7/site-packages/tensorflow_model_analysis/__init__.py", line 22, in <module>
   from tensorflow_model_analysis.eval_saved_model import export
 File "/opt/conda/envs/py2/lib/python2.7/site-packages/tensorflow_model_analysis/eval_saved_model/export.py", line 40, in <module>
   class EvalInputReceiver(export_lib.SupervisedInputReceiver):
AttributeError: 'module' object has no attribute 'SupervisedInputReceiver'
```

My suspicion is that TFMA now depends on a newer version of TF.

**Comment by pdmack** [comment]
@jlewi correct TFMA 0.9.0 and higher require TF 1.9+, and actually 0.9.1 seems to want TF 1.10+

The older images would need to pin 0.6.

**Comment by pdmack** [comment]
Or INSTALL_TFMA=no in those version-configs

**Comment by richardsliu** [comment]
@pdmack I set INSTALL_TFMA to "no", but the presubmits are still showing the same errors: http://testing-argo.kubeflow.org/workflows/kubeflow-test-infra/kubeflow-presubmit-tf-notebook-release-1579-cd6dfa7-3423-52a9?tab=workflow&nodeId=kubeflow-presubmit-tf-notebook-release-1579-cd6dfa7-3423-52a9-1598222731&sidePanel=logs%3Akubeflow-presubmit-tf-notebook-release-1579-cd6dfa7-3423-52a9-1598222731%3A

See the logs under build-1-8-0-cpu.

**Comment by richardsliu** [comment]
Nevermind, I know why this happened.
