### ISSUE TITLE
Running Tensorflow Training on Minikube: Could not start gRPC server, Address already in use

### ISSUE THREAD

**Issue by tidylobster** [kubeflow/kubeflow#1931]
I'm trying to run a training with `tf.Estimators`. Everything starts properly, but, when I enter `tf.estimator.train_and_evaluate`, server cannot be started since the port is already in use. That's really strange, but I can't resolve it myself. Any help?

**Running code**
```python
# imports ...


def main():
    params = tf.contrib.training.HParams(**Config.model.to_dict())

    run_config = tf.estimator.RunConfig(
        model_dir=Config.train.model_dir,
        save_checkpoints_steps=Config.train.save_checkpoints_steps,
    )

    tf_config = os.environ.get('TF_CONFIG', '{}')
    tf_config_json = json.loads(tf_config)

    cluster = tf_config_json.get('cluster')
    job_name = tf_config_json.get('task', {}).get('type')
    task_index = tf_config_json.get('task', {}).get('index')

    cluster_spec = tf.train.ClusterSpec(cluster)
    server = tf.train.Server(cluster_spec,
        job_name=job_name,
        task_index=task_index)

    if job_name == "ps":
        tf.logging.info("Started server!")
        server.join()

    if job_name == "worker":
        with tf.Session(server.target):
            with tf.device(tf.train.replica_device_setter(
                    worker_device="/job:worker/task:%d" % task_index,
                    cluster=cluster)
                ):
                tf.logging.info("Initializing Estimator")
                conversation = Conversation()
                estimator = tf.estimator.Estimator(
                    model_fn=conversation.model_fn,
                    model_dir=Config.train.model_dir,
                    params=params,
                    config=run_config)
                        
                tf.logging.info("Initializing vocabulary")
                vocab = data_loader.load_vocab("vocab")
                Config.data.vocab_size = len(vocab)

                train_X, test_X, train_y, test_y = data_loader.make_train_and_test_set()
                train_input_fn, train_input_hook = data_loader.make_batch((train_X, train_y), batch_size=Config.model.batch_size)
                test_input_fn, test_input_hook = data_loader.make_batch((test_X, test_y), batch_size=Config.model.batch_size, scope="test")

                tf.logging.info("Initializing Specifications")
                train_spec = tf.estimator.TrainSpec(input_fn=train_input_fn, max_steps=1000)
                eval_spec = tf.estimator.EvalSpec(input_fn=test_input_fn)
                tf.logging.info("Run training")
                tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)


if __name__ == '__main__':
    tf.logging.set_verbosity(logging.INFO)

    parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('--config', type=str, default='config', help='config file name')
    args = parser.parse_args()

    # Print Config setting
    Config(args.config)
    print("Config: ", Config)
    if Config.get("description", None):
        print("Config Description")
        for key, value in Config.description.items():
            print(" - {}: {}".format(key, value))

    main()
```

**Logs from Worker Pod**
```
INFO:tensorflow:TF_CONFIG environment variable: {'cluster': {'master': ['job-ca853-master-0.default.svc.cluster.local:2222'], 'ps': ['job-ca853-ps-0.default.svc.cluster.local:2222'], 'worker': ['job-ca853-worker-0.default.svc.cluster.local:2222']}, 'task': {'type': 'worker', 'index': 0}}
2018-11-09 12:28:53.191714: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-11-09 12:28:53.198863: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:222] Initialize GrpcChannelCache for job master -> {0 -> job-ca853-master-0.default.svc.cluster.local:2222}
2018-11-09 12:28:53.198934: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:222] Initialize GrpcChannelCache for job ps -> {0 -> job-ca853-ps-0.default.svc.cluster.local:2222}
2018-11-09 12:28:53.198961: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:222] Initialize GrpcChannelCache for job worker -> {0 -> localhost:2222}
2018-11-09 12:28:53.201391: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:381] Started server with target: grpc://localhost:2222
INFO:tensorflow:Initializing Estimator
INFO:tensorflow:Using config: {'_model_dir': '/models/cornell_movie_dialogs', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': 1000, '_save_checkpoints_secs': None, '_session_config': device_filters: "/job:ps"
device_filters: "/job:worker/task:0"
allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f79a1d8c390>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 1, '_master': 'grpc://job-ca853-worker-0.default.svc.cluster.local:2222', '_evaluation_master': '', '_num_ps_replicas': 1, '_num_worker_replicas': 2, '_is_chief': False}
INFO:tensorflow:Initializing vocabulary
196667it [00:11, 16906.27it/s]
25007it [00:01, 17910.04it/s]
INFO:tensorflow:Initializing Specifications
INFO:tensorflow:Run training
INFO:tensorflow:Not using Distribute Coordinator.
INFO:tensorflow:Start Tensorflow server.
E1109 12:29:10.046257690       1 server_chttp2.cc:40]        {"created":"@1541766550.046208311","description":"No address added out of total 1 resolved","file":"external/grpc/src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":307,"referenced_errors":[{"created":"@1541766550.046203024","description":"Failed to add any wildcard listeners","file":"external/grpc/src/core/lib/iomgr/tcp_server_posix.cc","file_line":324,"referenced_errors":[{"created":"@1541766550.046145365","description":"OS Error","errno":97,"file":"external/grpc/src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":283,"os_error":"Address family not supported by protocol","syscall":"socket","target_address":"[::]:2222"},{"created":"@1541766550.046198734","description":"Unable to configure socket","fd":8,"file":"external/grpc/src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":214,"referenced_errors":[{"created":"@1541766550.046184669","description":"OS Error","errno":98,"file":"external/grpc/src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":187,"os_error":"Address already in use","syscall":"bind"}]}]}]}
Config:  Read config file name: ./config/cornell-movie-dialogs
{
    "data": {
        "base_path": "/data/cornell_movie_dialogs_corpus/",
        "conversation_fname": "movie_conversations.txt",
        "line_fname": "movie_lines.txt",
        "processed_path": "processed_cornell_movie_dialogs_data",
        "word_threshold": 2,
        "max_seq_length": 200,
        "testset_size": 25000,
        "sentence_diff": 0.33,
        "PAD_ID": 0,
        "UNK_ID": 1,
        "START_ID": 2,
        "EOS_ID": 3
    },
    "model": {
        "batch_size": 32,
        "num_layers": 3,
        "num_units": 512,
        "embed_dim": 256,
        "embed_share": true,
        "cell_type": "gru",
        "dropout": 0.2,
        "encoder_type": "bi",
        "attention_mechanism": "normed_bahdanau"
    },
    "train": {
        "learning_rate": 0.001,
        "sampling_probability": 0.25,
        "train_steps": 100000,
        "model_dir": "/models/cornell_movie_dialogs",
        "save_checkpoints_steps": 1000,
        "loss_hook_n_iter": 1000,
        "check_hook_n_iter": 1000,
        "min_eval_frequency": 1,
        "print_verbose": true,
        "debug": false
    },
    "predict": {
        "beam_width": 5,
        "length_penalty_weight": 1.0
    },
    "slack": {
        "webhook_url": ""
    }
}
load vocab ...
vocab size: 41829
make Training data and Test data Start....
load data from train_ids.enc, train_ids.dec...
load data from test_ids.enc, test_ids.dec...
train data count : 104032
test data count : 11637
shuffle dataset ...
sorted by inputs length and outputs length ...
Traceback (most recent call last):
  File "/src/main.py", line 139, in <module>
    main()
  File "/src/main.py", line 121, in main
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 471, in train_and_evaluate
    return executor.run()
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 637, in run
    getattr(self, task_to_run)()
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 647, in run_worker
    return self._start_distributed_training()
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 768, in _start_distributed_training
    self._start_std_server(config)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 756, in _start_std_server
    protocol=config.protocol)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/training/server_lib.py", line 148, in __init__
    self._server_def.SerializeToString(), status)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnknownError: Could not start gRPC server
```

**Manifest**
```yaml
apiVersion: "kubeflow.org/v1alpha2"
kind: "TFJob"
metadata: 
name: {{workflow.parameters.job-name}}
spec: 
tfReplicaSpecs:
Master:
  replicas: 1
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: tensorflow
        image: tidylobster/conversation-tensorflow
        imagePullPolicy: Always
        ports:
        - containerPort: 2222
        command: ["python3", "/src/main.py", "--config", {{workflow.parameters.config}}]
        volumeMounts:  
        - name: data
          mountPath: "/data"
        - name: models
          mountPath: "/model"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
        - name: models
          persistentVolumeClaim:
            claimName: models
PS:
  replicas: 1
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: tensorflow
        image: tidylobster/conversation-tensorflow
        imagePullPolicy: Always
        ports:
        - containerPort: 2222
        command: ["python3", "/src/main.py", "--config", {{workflow.parameters.config}}]
        volumeMounts:  
        - name: data
          mountPath: "/data"
        - name: models
          mountPath: "/model"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
        - name: models
          persistentVolumeClaim:
            claimName: models
Worker:
  replicas: 1
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: tensorflow
        image: tidylobster/conversation-tensorflow
        imagePullPolicy: Always
        ports:
        - containerPort: 2222
        command: ["python3", "/src/main.py", "--config", {{workflow.parameters.config}}]
        volumeMounts:  
        - name: data
          mountPath: "/data"
        - name: models
          mountPath: "/model"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
        - name: models
          persistentVolumeClaim:
            claimName: models
```

**Comment by jlewi** [comment]
@tidylobster Sorry no on ever responded to you. Were you ever able to get this resolved?

I don't the TFJob controller binds any ports. So I think it might an issue somewhere in your code?

**Comment by aidangomez** [comment]
I'm having the same issue @tidylobster, did you manage to track this down?

**Comment by tidylobster** [comment]
Hi, @aidangomez 

No, I haven't looked at this since then.
