### ISSUE TITLE
TF-Serving http-proxy error

### ISSUE THREAD

**Issue by zxsimple** [kubeflow/kubeflow#1979]
Follow [Kubernetes TensorFlow Model Server](https://github.com/kubeflow/kubeflow/blob/a8c0dda2f2d90bae67497652211cc6224c8f73cd/components/k8s-model-server/README.md) to setup inception model serving.

When I test with curl command I got internal 500 error.
```
(echo '{"instances": [{"image_contents": {"b64": "'; base64 ./inception-client/images/sleeping-pepper.jpg; echo '"}}]}') | curl -H "Content-Type: application/json" -X POST -d @-  localhost:8000/model/1/inception:predict
```

Check the log output of http-proxy pod I got the error:
```
[E 181120 12:23:46 web:1590] Uncaught exception POST /model/inception:predict (192.168.65.3)
    HTTPServerRequest(protocol='http', host='localhost:8000', method='POST', uri='/model/inception:predict', version='HTTP/1.1', remote_ip='192.168.65.3', headers={'Content-Length': '293440', 'Accept': '*/*', 'User-Agent': 'curl/7.54.0', 'Host': 'localhost:8000', 'Expect': '100-continue', 'Content-Type': 'application/json'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 1511, in _execute
        result = yield result
      File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 307, in wrapper
        yielded = next(result)
      File "/usr/src/app/server.py", line 241, in post
        values = [instance[input_column] for instance in instances]
    KeyError: u'inputs'
```

Please help.
@yupbank, @lluunn, @u2takey

**Comment by zxsimple** [comment]
What I found is that the code `/usr/src/app/server.py` is different inside of the pod to that in github latest branches. 
The docker image is `gcr.io/kubeflow-images-public/tf-model-server-http-proxy:v20180606-9dfda4f2`

**Comment by zxsimple** [comment]
Same problem after I upgrade the image to `tf-model-server-http-proxy:v20180918-faea44af`, still the problem just occur at line 247

```
245    inputs_type_map = signature.inputs
246    for input_column in input_columns:
247      values = [instance[input_column] for instance in instances]
248      request.inputs[input_column].CopyFrom(tf.make_tensor_proto(values, inputs_type_map[input_column].dtype))
```

**Comment by zxsimple** [comment]
Seems related to pull #334

**Comment by lluunn** [comment]
It should be a mismatch between model and input.
I think the model is expecting input to have key 'inputs', so one thing to try is to replace "image_contents" with "inputs"

Also, that README is somewhat outdated. You can find newer doc
[here](https://www.kubeflow.org/docs/guides/components/tfserving/), and a even newer but WIP
doc [here](https://www.kubeflow.org/docs/guides/components/tfserving_new/)

If you just want some model/input pair that's working, try
gs://kubeflow-examples-data/mnist
https://github.com/kubeflow/kubeflow/blob/master/components/k8s-model-server/test-data/mnist_input.json

**Comment by zxsimple** [comment]
After changing the json key I got another error:

The http-proxy side:
```
    HTTPServerRequest(protocol='http', host='localhost:8000', method='POST', uri='/model/inception:predict', version='HTTP/1.1', remote_ip='192.168.65.3', headers={'Content-Length': '293432', 'Accept': '*/*', 'User-Agent': 'curl/7.54.0', 'Host': 'localhost:8000', 'Expect': '100-continue', 'Content-Type': 'application/json'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 1511, in _execute
        result = yield result
      File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
        yielded = self.gen.throw(*exc_info)
      File "/usr/src/app/server.py", line 251, in post
        result = yield fwrap(stub.Predict.future(request, self.settings['rpc_timeout']))
      File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
    'AbortionError: AbortionError(code=StatusCode.INVALID_ARGUMENT, details="Could not parse example input, value: \'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xe1\x00*Exif\x00\x00II*\x00\x08\x00\x00\x00\x01\x001\x01\x02\x00\x07\x00\x00\x00\x1a\x00\x00\x00\x00\x00\x00\x00Google\x00\x00\xff\xe2\x0b\xf8ICC_PROFILE\x00\x01\x01\x00\x00\x0b\xe8\x00\x00\x00\x00\x02\x00\x00\x00mntrRGB XYZ
```

The tensorflow-serving side:
```
2018-11-20 13:05:11.363432: I tensorflow_serving/core/loader_harness.cc:86] Successfully loaded servable version {name: inception version: 1}
2018-11-20 13:05:11.369343: I tensorflow_serving/model_servers/server.cc:285] Running gRPC ModelServer at 0.0.0.0:9000 ...
2018-11-21 00:33:57.520180: W external/org_tensorflow/tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at example_parsing_ops.cc:144 : Invalid argument: Could not parse example input, value: '����
2018-11-21 00:37:26.255716: W external/org_tensorflow/tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at example_parsing_ops.cc:144 : Invalid argument: Could not parse example input, value: '����
2018-11-21 00:41:05.792550: W external/org_tensorflow/tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at example_parsing_ops.cc:144 : Invalid argument: Could not parse example input, value: '����
```

**Comment by jlewi** [comment]
@zxsimple Were you able to get past this?

The error indicates that it couldn't be able to parse the input.

This could mean

* Your input is not a properly serialized ExampleProto

@lluunn Any additional suggestions? Is this using the TFServing HTTP proxy or are now deprecated HTTP proxy?

**Comment by zxsimple** [comment]
No, I didn't dig into to check the serialization/ deserialization

**Comment by yupbank** [comment]
hey, sorry for later reply, but the error message is explaining itself. With you first try, change the “image_content” into “inputs” would help

And the second try should be because of you have mixed the :predict and :classify 

Hope that can help

**Comment by zxsimple** [comment]
@yupbank Thank you. I will close it.
