### ISSUE TITLE
Suggest KubeFlow to use ksonnet 0.13.1 as minimal version

### ISSUE THREAD

**Issue by cheyang** [kubeflow/kubeflow#2250]
I've tried to deploy kubeflow v0.4.0 in Kubernetes 1.12.4 with ksonnet in 0.11.0, and get nil pointer error. But after upgrading to 0.13.1, I'm able to install. 

```
++ ks init ks_app --skip-default-registries
INFO Using context "kubernetes-admin@kubernetes" from kubeconfig file "/root/.kube/config"
INFO Creating environment "default" with namespace "default", pointing to cluster at address "https://192.168.0.242:6443"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x456452]

goroutine 1 [running]:
github.com/ksonnet/ksonnet/vendor/github.com/ksonnet/ksonnet-lib/ksonnet-gen/ksonnet.parsePaths(0xc42073c300, 0x6, 0x1, 0xc)
  /Users/bryan/go/src/github.com/ksonnet/ksonnet/vendor/github.com/ksonnet/ksonnet-lib/ksonnet-gen/ksonnet/paths.go:33 +0x1f1
github.com/ksonnet/ksonnet/vendor/github.com/ksonnet/ksonnet-lib/ksonnet-gen/ksonnet.NewCatalog(0xc42073c300, 0xc4212a2d90, 0x1, 0x1, 0x40, 0x0, 0x0)
  /Users/bryan/go/src/github.com/ksonnet/ksonnet/vendor/github.com/ksonnet/ksonnet-lib/ksonnet-gen/ksonnet/catalog.go:76 +0x1de
github.com/ksonnet/ksonnet/vendor/github.com/ksonnet/ksonnet-lib/ksonnet-gen/ksonnet.GenerateLib(0xc420974060, 0xe, 0x0, 0x0, 0x0)
  /Users/bryan/go/src/github.com/ksonnet/ksonnet/vendor/github.com/ksonnet/ksonnet-lib/ksonnet-gen/ksonnet/ksonnet.go:25 +0xce
github.com/ksonnet/ksonnet/pkg/util/kslib.astBuilder(0xc420974060, 0xe, 0xc421bb8000, 0x3f0dc0, 0x3ffe00, 0x0, 0x0, 0x0)
  /Users/bryan/go/src/github.com/ksonnet/ksonnet/pkg/util/kslib/ksonnet.go:87 +0x40
github.com/ksonnet/ksonnet/pkg/util/kslib.Ksonnet(0xc421bb8000, 0x3f0dc0, 0x3ffe00, 0x0, 0x0, 0x0)
  /Users/bryan/go/src/github.com/ksonnet/ksonnet/pkg/util/kslib/ksonnet.go:83 +0x3fd
github.com/ksonnet/ksonnet/pkg/lib.(*Manager).GenerateLibData(0xc421336280, 0x1, 0x1dc69a0, 0x2a15f78)
  /Users/bryan/go/src/github.com/ksonnet/ksonnet/pkg/lib/lib.go:83 +0x8a
github.com/ksonnet/ksonnet/pkg/app.updateLibData(0x1dc69a0, 0x2a15f78, 0xc420aa2f70, 0xf, 0xc4212e0b80, 0x1b, 0x1, 0xc421437288, 0x43b4ab, 0xc42044f798, ...)
  /Users/bryan/go/src/github.com/ksonnet/ksonnet/pkg/app/app.go:128 +0xba
github.com/ksonnet/ksonnet/pkg/app.(*App010).AddEnvironment(0xc42142fa90, 0x187146a, 0x7, 0xc420aa2f70, 0xf, 0xc4209aeae0, 0x0, 0x1a4, 0x0)
  /Users/bryan/go/src/github.com/ksonnet/ksonnet/pkg/app/app010.go:62 +0x427
github.com/ksonnet/ksonnet/pkg/env.(*creator).Create(0xc4200762d0, 0xc4200762d0, 0x50)
  /Users/bryan/go/src/github.com/ksonnet/ksonnet/pkg/env/create.go:117 +0x979
github.com/ksonnet/ksonnet/pkg/env.Create(0x1dcb1a0, 0xc42142fa90, 0xc4208c43a0, 0x1a, 0x187146a, 0x7, 0x187146a, 0x7, 0xc420aa2f70, 0xf, ...)
  /Users/bryan/go/src/github.com/ksonnet/ksonnet/pkg/env/create.go:42 +0x157
github.com/ksonnet/ksonnet/pkg/appinit.(*initApp).Run(0xc4212a3980, 0x1, 0x1000001db1900)
  /Users/bryan/go/src/github.com/ksonnet/ksonnet/pkg/appinit/init.go:88 +0x452
github.com/ksonnet/ksonnet/pkg/appinit.Init(0x1dc69a0, 0x2a15f78, 0x7ffff05fe6f6, 0x6, 0xc4206d1200, 0x17, 0x0, 0x0, 0xc420aa2f70, 0xf, ...)
  /Users/bryan/go/src/github.com/ksonnet/ksonnet/pkg/appinit/init.go:33 +0x14a
github.com/ksonnet/ksonnet/pkg/actions.(*Init).Run(0xc420076000, 0xc420076000, 0x0)
  /Users/bryan/go/src/github.com/ksonnet/ksonnet/pkg/actions/init.go:106 +0x121
github.com/ksonnet/ksonnet/pkg/actions.RunInit(0xc42070c750, 0xc4206dc9c0, 0xe)
  /Users/bryan/go/src/github.com/ksonnet/ksonnet/pkg/actions/init.go:37 +0x5c
github.com/ksonnet/ksonnet/pkg/clicmd.runAction(0xe, 0xc42070c750, 0x188a651, 0x17)
  /Users/bryan/go/src/github.com/ksonnet/ksonnet/pkg/clicmd/actions.go:113 +0x66
github.com/ksonnet/ksonnet/pkg/clicmd.glob..func17(0x29d5da0, 0xc42089c080, 0x1, 0x2, 0x0, 0x0)
```

I suggest to update documentation to choose the minimal version as 0.13.1. Thanks.

**Comment by kunmingg** [comment]
Can you try 0.12.0?
ksonnet 0.13.1 has breaking API change.

**Comment by jlewi** [comment]
Thanks @cheyang 

I think using 0.13.1 at this point is a good solution.

**Comment by jlewi** [comment]
Anyone want to submit a PR updating relevant docs in kubeflow/website?

**Comment by stpabhi** [comment]
@jlewi I can work on it

**Comment by stpabhi** [comment]
https://github.com/kubeflow/website/pull/408
