### ISSUE TITLE
Calling `os.makedirs` fails even after we have check for directory existence.

### ISSUE THREAD

**Issue by ashahba** [kubeflow/kubeflow#2484]
Looks like there is some race condition that causes `os.makedires` calls to fail randomly even after we have just checked if directory exists prior to creation.
[here](http://testing-argo.kubeflow.org/workflows/kubeflow-test-infra/kubeflow-presubmit-kubeflow-e2e-minikube-2447-7bbe31e-5722-c39c?tab=workflow&nodeId=kubeflow-presubmit-kubeflow-e2e-minikube-2447-7bbe31e-5722-c39c-2534328948&sidePanel=logs%3Akubeflow-presubmit-kubeflow-e2e-minikube-2447-7bbe31e-5722-c39c-2534328948%3Amain) is one example and the error is:
```
W
Traceback (most recent call last):
 File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
   "__main__", fname, loader, pkg_name)
 File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
   exec code in run_globals
 File "/mnt/test-data-volume/kubeflow-presubmit-kubeflow-e2e-minikube-2447-7bbe31e-5722-c39c/src/kubeflow/kubeflow/testing/test_deploy.py", line 792, in <module>
   main()
 File "/mnt/test-data-volume/kubeflow-presubmit-kubeflow-e2e-minikube-2447-7bbe31e-5722-c39c/src/kubeflow/kubeflow/testing/test_deploy.py", line 756, in main
   os.makedirs(os.path.dirname(test_log))
 File "/usr/lib/python2.7/os.py", line 157, in makedirs
   mkdir(name, mode)
OSError: [Errno 17] File exists: '/mnt/test-data-volume/kubeflow-presubmit-kubeflow-e2e-minikube-2447-7bbe31e-5722-c39c/output/artifacts/logs'
```

**Comment by ashahba** [comment]
PR was merged and this one is can be safely closed now.
