### ISSUE TITLE
"ML - XGBoost - Training with Confusion Matrix" pipeline errors out during training

### ISSUE THREAD

**Issue by vswami78** [kubeflow/kubeflow#2881]
The error seen was:

Exception in thread "main" java.lang.NoSuchMethodError: org.apache.spark.scheduler.LiveListenerBus.removeListener(Ljava/lang/Object;)V
	at org.apache.spark.SparkParallelismTracker.safeExecute(SparkParallelismTracker.scala:84)
	at org.apache.spark.SparkParallelismTracker.execute(SparkParallelismTracker.scala:107)

In looking through such errors in connection with XGBoost from the past it - Spark version seemed to have played a role (https://github.com/dmlc/xgboost/issues/3266)

The Dataproc create_cluster in commons/util - chooses "image version 1.2" for dataproc which hosts SPARK_VERSION 2.2. 

However, I'm not sure if choosing a different image version would help though because when I
looked through the file "dataproc-startup-script_output" - I find that the SPARK_VERSION chosen for this is 2.3.2
<13>Mar 30 17:34:29 google-dataproc-startup[1161]: ++ SPARK_VERSION=2.3.2

Hope to see this resolved.

**Comment by vswami78** [comment]
Additional traceback details in case it is helpful

Traceback (most recent call last):
  File "/ml/train.py", line 73, in <module>
    main()
  File "/ml/train.py", line 65, in main
    _utils.wait_for_job(api, args.project, args.region, job_id)
  File "/ml/common/_utils.py", line 78, in wait_for_job
    raise Exception(result['status']['details'])
