### ISSUE TITLE
jupyter-web-app Jinja2 error 

### ISSUE THREAD

**Issue by pdmack** [kubeflow/kubeflow#2958]
Link from dashboard to notebooks gives a 500. jupyter-web-app flask app seems to fail with a Jinja2 error.
 
![Screen Shot 2019-04-06 at 7 21 42 PM](https://user-images.githubusercontent.com/2380545/55676336-47daa080-58a1-11e9-98ce-bacdc2f64a45.png)

```
10.128.4.20 - - [06/Apr/2019 23:09:27] "GET / HTTP/1.1" 500 -
[2019-04-06 23:14:35,421] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/kubeflow_jupyter/default/app.py", line 166, in home
    'notebooks.html', prefix=prefix(), title='Notebooks', namespaces=nmsps)
  File "/usr/local/lib/python3.6/dist-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/app/kubeflow_jupyter/default/templates/notebooks.html", line 16, in template
    <option value="{{ ns }}" {{ ns == 'kubeflow'|yesno:"selected" }}>{{ ns }}</option>
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/usr/local/lib/python3.6/dist-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/usr/local/lib/python3.6/dist-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/usr/local/lib/python3.6/dist-packages/jinja2/parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/usr/local/lib/python3.6/dist-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/usr/local/lib/python3.6/dist-packages/jinja2/parser.py", line 199, in parse_for
    body = self.parse_statements(('name:endfor', 'name:else'))
  File "/usr/local/lib/python3.6/dist-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/parser.py", line 876, in subparse
    self.stream.expect('variable_end')
  File "/usr/local/lib/python3.6/dist-packages/jinja2/lexer.py", line 384, in expect
    self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got ':'
10.128.4.20 - - [06/Apr/2019 23:14:35] "GET / HTTP/1.1" 500 -
```

**Comment by jlewi** [comment]
Possibly related to this PR?
https://github.com/kubeflow/kubeflow/commit/00e1320721b1643062b2842706cc1eb4bc2a36a3

**Comment by jlewi** [comment]
I tried: gcr.io/kubeflow-images-public/jupyter-web-app:v-latest-base-00e132-1114287775101751296

And it seemed to work.

**Comment by kimwnasptd** [comment]
@pdmack This was because of a previous PR, but @avdaredevil has resolved this with [00e1320](https://github.com/kubeflow/kubeflow/pull/2951/files).
We've been updating quite frequently the `v0.5.0` image tag of jupyter-web-app. I guess when the webapp's Pod was created, the current v0.5.0 was the one with that error?

As @jlewi noted, this should be resolved in `gcr.io/kubeflow-images-public/jupyter-web-app:v-latest-base-00e132-1114287775101751296` which is also the current `v0.5.0`. 

If your Pod is using the image ` gcr.io/kubeflow-images-public/jupyter-web-app:v0.5.0` then you can delete the Pod and it will use the correct image once it gets recreated.

**Comment by pdmack** [comment]
Yep, newer `v0.5.0` has appeared. Thanks @kimwnasptd @jlewi !
Very snazzy new UI, well done.
I'll pour one out for JupyterHub...

**Comment by lp-pl** [comment]
I met the same problem：

![2019-04-23 15-58-10 的屏幕截图](https://user-images.githubusercontent.com/10861802/56565129-3bb14b80-65e2-11e9-95e0-70b87d344b43.png)
The  logs are as follows:
```
* Serving Flask app "kubeflow_jupyter.default.app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
10.244.0.1 - - [23/Apr/2019 07:55:38] "GET / HTTP/1.1" 200 -
10.244.0.1 - - [23/Apr/2019 07:55:38] "GET /api/namespaces/kubeflow/notebooks HTTP/1.1" 200 -
10.244.0.1 - - [23/Apr/2019 07:55:40] "GET /api/namespaces/kubeflow/notebooks HTTP/1.1" 200 -
[2019-04-23 07:55:40,927] ERROR in app: Exception on /new [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/kubeflow_jupyter/default/app.py", line 136, in new_notebook
    if api.get_default_storageclass() != "":
  File "/app/kubeflow_jupyter/common/api.py", line 105, in get_default_storageclass
    is_default = annotations.get(key, False)
AttributeError: 'NoneType' object has no attribute 'get'
10.244.0.1 - - [23/Apr/2019 07:55:40] "GET /new?namespace=kubeflow HTTP/1.1" 500 -
```

**Comment by lp-pl** [comment]
@jlewi @kimwnasptd  Could you help me ？Thanks

**Comment by lp-pl** [comment]
Excuse me, I have solved the problem, Thanks .It was because of my wrong storageclass...

**Comment by kimwnasptd** [comment]
Hi @lp-pl, you bumped into a small issue in the web app. 

When checking the StorageClasses, the backend wouldn't check if an object doesn't have any annotations and tries to look for a specific key nevertheless.

I will make a small PR to fix this. Thank you for reporting it!

**Comment by lp-pl** [comment]
Well, I understand. Thanks @kimwnasptd
