### ISSUE TITLE
Jupyter pod is running while the jupuyterhub web stuck there

### ISSUE THREAD

**Issue by dyoung23** [kubeflow/kubeflow#3015]
I submit a jupyter pod,and it will be running soon after that.But the jupyterhub web always stuck at _Your server is starting up You will be redirected automatically when it's ready for you_ until it's timeout after 30mins. How can I deal with it?
```
NAME                                                  READY   STATUS             RESTARTS   AGE
ambassador-6bccfd8447-j7jpj                           3/3     Running            0          3d
ambassador-6bccfd8447-p6zrt                           3/3     Running            0          25d
ambassador-6bccfd8447-ptn4l                           3/3     Unknown            0          8d
ambassador-6bccfd8447-qq6vc                           3/3     Running            0          25d
argo-ui-7b6585d85d-c2px9                              1/1     Running            0          35d
centraldashboard-6b67b6fb66-vlv7s                     1/1     Running            0          20d
jupyter-admin                                         1/1     Running            0          1d

```
the log in jupyterhub pod is as below
```
[E 2019-04-13 07:26:25.313 JupyterHub base:940] Preventing implicit spawn for admin because last spawn failed: pod/jupyter-admin did not start in 1800 seconds!
[E 2019-04-13 07:26:25.314 JupyterHub web:1621] Uncaught exception GET /hub/user/admin/ (192.168.106.183)
    HTTPServerRequest(protocol='http', host='192.168.13.55:32300', method='GET', uri='/hub/user/admin/', version='HTTP/1.1', remote_ip='192.168.106.183')
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/tornado/web.py", line 1543, in _execute
        result = yield result
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 942, in get
        raise copy.copy(exc).with_traceback(exc.__traceback__)
      File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 936, in error_callback
        future.result()
      File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 936, in error_callback
        future.result()
      File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 936, in error_callback
        future.result()
      [Previous line repeated 1 more times]
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 625, in finish_user_spawn
        await spawn_future
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/user.py", line 486, in spawn
        raise e
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/user.py", line 406, in spawn
        url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/opt/conda/lib/python3.6/site-packages/kubespawner/spawner.py", line 995, in start
        timeout=self.start_timeout
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/utils.py", line 155, in exponential_backoff
        raise TimeoutError(fail_message)
    TimeoutError: pod/jupyter-admin did not start in 1800 seconds!
    
[E 2019-04-13 07:26:25.316 JupyterHub log:150] {
      "X-Forwarded-Host": "192.168.13.55:32300",
      "X-Forwarded-Port": "32300",
      "X-Forwarded-For": "192.168.106.183",
      "Content-Length": "0",
      "X-Envoy-Original-Path": "/hub/user/admin/",
      "X-Envoy-Expected-Rq-Timeout-Ms": "300000",
      "X-Request-Id": "c7cb0ed2-34c8-431d-8a67-0503eedf78ad",
      "X-Forwarded-Proto": "http,http",
      "Cookie": "jupyterhub-hub-login=\"2|1:0|10:1554974510|20:jupyterhub-hub-login|44:ZDI0OWY5YjVlODM3NGU4N2JjNzNmODQ2MjBjZTQzZmM=|640b9afec507c05455beee963231fdd72ee4f16160dba853b830499e351b0181\"",
      "Accept-Language": "zh-CN,zh;q=0.9",
      "Accept-Encoding": "gzip, deflate",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36",
      "Upgrade-Insecure-Requests": "1",
      "Cache-Control": "max-age=0",
      "Host": "192.168.13.55:32300",
      "Connection": "close"
    }
[E 2019-04-13 07:26:25.317 JupyterHub log:158] 500 GET /hub/user/admin/ (admin@192.168.106.183) 458.73ms

```

**Comment by jlewi** [comment]
Can you provide the logs from the `jupyter-admin` pod?

**Comment by dyoung23** [comment]
the logs from jupyter-admin pod:
```
[root@ppf-1 ~]# kubectl logs jupyter-admin -n kf
+ [[  --ip="0.0.0.0" --port=8888 --allow-root != *\-\-\i\p\=* ]]
+ '[' '!' -z '' ']'
+ '[' '!' -z '' ']'
+ '[' '!' -z '' ']'
+ '[' '!' -z '' ']'
+ '[' '!' -z '' ']'
+ '[' '!' -z '' ']'
+ '[' '!' -z '' ']'
+ . /usr/local/bin/pvc-check.sh
++ SRC_CONF=/tmp/jupyter_notebook_config.py
++ WORK_DIR=/home/jovyan/work
++ CONF_DIR=/home/jovyan/.jupyter
++ echo 'checking if /home/jovyan volume needs init...'
checking if /home/jovyan volume needs init...
+++ ls --ignore=lost+found -A /home/jovyan
.../home/jovyan already has content...
...done
++ '[' .local ']'
++ echo '.../home/jovyan already has content...'
++ echo ...done
+ '[' -z '' ']'
+ set +e
+ source activate py2
++ _CONDA_ROOT=/opt/conda
++ . /opt/conda/etc/profile.d/conda.sh
+++ _CONDA_EXE=/opt/conda/bin/conda
+++ _CONDA_ROOT=/opt/conda
+++ _conda_set_vars
+++ '[' -n x ']'
+++ _CONDA_SHELL_FLAVOR=bash
+++ '[' -z x ']'
+++ '[' -z '' ']'
+++ PS1=
+++ '[' -z '' ']'
+++ export CONDA_SHLVL=0
+++ CONDA_SHLVL=0
++ _conda_activate py2
++ '[' -n '' ']'
++ local ask_conda
+++ PS1=
+++ /opt/conda/bin/conda shell.posix activate py2
++ ask_conda='PS1='\''(py2) '\''
\export CONDA_DEFAULT_ENV='\''py2'\''
\export CONDA_EXE='\''/opt/conda/bin/conda'\''
\export CONDA_PREFIX='\''/opt/conda/envs/py2'\''
\export CONDA_PROMPT_MODIFIER='\''(py2) '\''
\export CONDA_PYTHON_EXE='\''/opt/conda/bin/python'\''
\export CONDA_SHLVL='\''1'\''
\export PATH='\''/opt/conda/envs/py2/bin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'\'''
++ eval 'PS1='\''(py2) '\''
\export CONDA_DEFAULT_ENV='\''py2'\''
\export CONDA_EXE='\''/opt/conda/bin/conda'\''
\export CONDA_PREFIX='\''/opt/conda/envs/py2'\''
\export CONDA_PROMPT_MODIFIER='\''(py2) '\''
\export CONDA_PYTHON_EXE='\''/opt/conda/bin/python'\''
\export CONDA_SHLVL='\''1'\''
\export PATH='\''/opt/conda/envs/py2/bin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'\'''
+++ PS1='(py2) '
+++ export CONDA_DEFAULT_ENV=py2
+++ CONDA_DEFAULT_ENV=py2
+++ export CONDA_EXE=/opt/conda/bin/conda
+++ CONDA_EXE=/opt/conda/bin/conda
+++ export CONDA_PREFIX=/opt/conda/envs/py2
+++ CONDA_PREFIX=/opt/conda/envs/py2
+++ export 'CONDA_PROMPT_MODIFIER=(py2) '
+++ CONDA_PROMPT_MODIFIER='(py2) '
+++ export CONDA_PYTHON_EXE=/opt/conda/bin/python
+++ CONDA_PYTHON_EXE=/opt/conda/bin/python
+++ export CONDA_SHLVL=1
+++ CONDA_SHLVL=1
+++ export PATH=/opt/conda/envs/py2/bin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+++ PATH=/opt/conda/envs/py2/bin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
++ _conda_hashr
++ case "$_CONDA_SHELL_FLAVOR" in
++ hash -r
+ jupyter nbextension install --py --user --symlink tensorflow_model_analysis
Traceback (most recent call last):
  File "/opt/conda/envs/py2/bin/jupyter-nbextension", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/envs/py2/lib/python2.7/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/conda/envs/py2/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/opt/conda/envs/py2/lib/python2.7/site-packages/notebook/nbextensions.py", line 988, in start
    super(NBExtensionApp, self).start()
  File "/opt/conda/envs/py2/lib/python2.7/site-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/opt/conda/envs/py2/lib/python2.7/site-packages/notebook/nbextensions.py", line 716, in start
    self.install_extensions()
  File "/opt/conda/envs/py2/lib/python2.7/site-packages/notebook/nbextensions.py", line 695, in install_extensions
    **kwargs
  File "/opt/conda/envs/py2/lib/python2.7/site-packages/notebook/nbextensions.py", line 211, in install_nbextension_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/opt/conda/envs/py2/lib/python2.7/site-packages/notebook/nbextensions.py", line 1122, in _get_nbextension_metadata
    m = import_item(module)
  File "/opt/conda/envs/py2/lib/python2.7/site-packages/traitlets/utils/importstring.py", line 42, in import_item
    return __import__(parts[0])
ImportError: No module named tensorflow_model_analysis
+ jupyter nbextension enable --py --user tensorflow_model_analysis
Traceback (most recent call last):
  File "/opt/conda/envs/py2/bin/jupyter-nbextension", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/envs/py2/lib/python2.7/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/conda/envs/py2/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/opt/conda/envs/py2/lib/python2.7/site-packages/notebook/nbextensions.py", line 988, in start
    super(NBExtensionApp, self).start()
  File "/opt/conda/envs/py2/lib/python2.7/site-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/opt/conda/envs/py2/lib/python2.7/site-packages/notebook/nbextensions.py", line 896, in start
    self.toggle_nbextension_python(self.extra_args[0])
  File "/opt/conda/envs/py2/lib/python2.7/site-packages/notebook/nbextensions.py", line 872, in toggle_nbextension_python
    logger=self.log)
  File "/opt/conda/envs/py2/lib/python2.7/site-packages/notebook/nbextensions.py", line 483, in enable_nbextension_python
    logger=logger)
  File "/opt/conda/envs/py2/lib/python2.7/site-packages/notebook/nbextensions.py", line 380, in _set_nbextension_state_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/opt/conda/envs/py2/lib/python2.7/site-packages/notebook/nbextensions.py", line 1122, in _get_nbextension_metadata
    m = import_item(module)
  File "/opt/conda/envs/py2/lib/python2.7/site-packages/traitlets/utils/importstring.py", line 42, in import_item
    return __import__(parts[0])
ImportError: No module named tensorflow_model_analysis
+ set -e
+ . /usr/local/bin/start.sh jupyterhub-singleuser '--ip="0.0.0.0"' --port=8888 --allow-root
++ set -e
+++ id -u
++ '[' 1000 == 0 ']'
++ [[ ! -z 1000 ]]
+++ id -u
++ [[ 1000 != \1\0\0\0 ]]
++ [[ ! -z '' ]]
++ [[ '' == \1 ]]
++ [[ '' == \y\e\s ]]
++ echo 'Execute the command'
++ exec jupyterhub-singleuser '--ip="0.0.0.0"' --port=8888 --allow-root
Execute the command
[I 2019-04-11 09:52:20.408 SingleUserNotebookApp extension:161] JupyterLab extension loaded from /opt/conda/lib/python3.6/site-packages/jupyterlab
[I 2019-04-11 09:52:20.408 SingleUserNotebookApp extension:162] JupyterLab application directory is /opt/conda/share/jupyter/lab
[I 2019-04-11 09:52:20.411 SingleUserNotebookApp singleuser:406] Starting jupyterhub-singleuser server version 0.9.4
[I 2019-04-11 09:52:20.424 SingleUserNotebookApp notebookapp:1712] Serving notebooks from local directory: /home/jovyan
[I 2019-04-11 09:52:20.424 SingleUserNotebookApp notebookapp:1712] The Jupyter Notebook is running at:
[I 2019-04-11 09:52:20.424 SingleUserNotebookApp notebookapp:1712] http://(jupyter-admin or 127.0.0.1):8888/user/admin/
[I 2019-04-11 09:52:20.424 SingleUserNotebookApp notebookapp:1713] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
```

**Comment by jlewi** [comment]
@dyoung23 What happens if you try connecting to the notebook itself bypassing JupyterHub?

Right now this looks like a JupyterHub issue and not a Kubeflow issue. Did you check the Kubespawner and JupyterHub GitHub issues to see if the was a similar issue already?

It looks like our JupyterHub image in 0.4 is using Kube spawner 0.9.0
https://github.com/kubeflow/kubeflow/blob/8212d72f5a4d5edb2345cd6e93c6231c15db2976/components/jupyterhub/docker/Dockerfile#L18

I took a quick look at the Kubespawner code
https://github.com/jupyterhub/kubespawner/blob/ca82253a78ba46ea34933b75110c84ef460550f0/kubespawner/spawner.py#L1641

0.5 no longer uses JupyterHub; so you might have better luck with 0.5.

**Comment by dyoung23** [comment]
@jlewi Thanks for your reply.
I can't find anyething useful in Kubespawner and JupyterHub GitHub issues except one issue which fixed it by restart the hub pod,and it doesn't work for me.

And I don't know how to connect to the notebook bypassing JupyterHub,I think I only can connect the notebook in its container.

**Comment by jlewi** [comment]
@dyoung23 Do you want to try 0.5? In 0.5 we no longer use JupyterHub; so that might fix the problem for you.

**Comment by dyoung23** [comment]
@jlewi Thanks.I will try it later.
But something strange happen on me,it works currently and I do nothing these days.

**Comment by jlewi** [comment]
Glad to hear it @dyoung23; I'll go ahead and close this.
