### ISSUE TITLE
Failed to connect to my Hub at http://jupyter-0:8081/hub/api

### ISSUE THREAD

**Issue by cbchouinard** [kubeflow/kubeflow#3099]
When doing a fresh install of Microk8s + kubeflow, we can spawn Jupyter server without problems. But when we restart the machine, we get this error when trying to spawn. 

```
Execute the command
++ exec jupyterhub-singleuser '--ip="0.0.0.0"' --port=8888 --allow-root
[W 2019-04-24 14:40:01.762 SingleUserNotebookApp configurable:168] Config option `open_browser` not recognized by `SingleUserNotebookApp`.  Did you mean `browser`?
[I 2019-04-24 14:40:01.970 SingleUserNotebookApp extension:168] JupyterLab extension loaded from /opt/conda/lib/python3.6/site-packages/jupyterlab
[I 2019-04-24 14:40:01.970 SingleUserNotebookApp extension:169] JupyterLab application directory is /opt/conda/share/jupyter/lab
[I 2019-04-24 14:40:01.972 SingleUserNotebookApp singleuser:406] Starting jupyterhub-singleuser server version 0.9.4
[E 2019-04-24 14:40:21.993 SingleUserNotebookApp singleuser:389] Failed to connect to my Hub at http://jupyter-0:8081/hub/api (attempt 1/5). Is it running?
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 386, in check_hub_version
        resp = await client.fetch(self.hub_api_url)
    tornado.simple_httpclient.HTTPTimeoutError: Timeout while connecting
[E 2019-04-24 14:40:44.017 SingleUserNotebookApp singleuser:389] Failed to connect to my Hub at http://jupyter-0:8081/hub/api (attempt 2/5). Is it running?
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 386, in check_hub_version
        resp = await client.fetch(self.hub_api_url)
    tornado.simple_httpclient.HTTPTimeoutError: Timeout while connecting
```

Running on Ubuntu, using snap to install Microk8s 1.13.

**Comment by jlewi** [comment]
Closing due to lack of response.
