### ISSUE TITLE
Kubeflow on EKS not starting jupyter notebooks

### ISSUE THREAD

**Issue by amarrella** [kubeflow/kubeflow#3332]
Hello, 
I'm playing around with a Kubeflow installation on EKS following the instructions in https://www.kubeflow.org/docs/aws/deploy/install-kubeflow/ 

Everything seems to work fine, but when I try to start a jupyter notebook server and i click "SPAWN" the request returns a 500.

Checking the logs in the jupyter-web-app pod I see the following:
```
[2019-05-22 15:31:20,934] ERROR in app: Exception on /api/namespaces/kubeflow/notebooks [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/kubeflow_jupyter/default/app.py", line 40, in post_notebook
    poddefaultLabels = api.get_poddefaults_labels(namespace)
  File "/app/kubeflow_jupyter/common/api.py", line 123, in get_poddefaults_labels
    ns, "poddefaults")['items']
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/apis/custom_objects_api.py", line 1432, in list_namespaced_custom_object
    (data) = self.list_namespaced_custom_object_with_http_info(group, version, namespace, plural, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/apis/custom_objects_api.py", line 1538, in list_namespaced_custom_object_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 155, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 342, in request
    headers=headers)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/rest.py", line 231, in GET
    query_params=query_params)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Audit-Id': 'db5efa14-8ccd-4921-a2ac-8c885afe154b', 'Content-Type': 'text/plain; charset=utf-8', 'X-Content-Type-Options': 'nosniff', 'Date': 'Wed, 22 May 2019 15:31:20 GMT', 'Content-Length': '19'})
HTTP response body: 404 page not found
```

So to me it seems it's trying to hit an endpoint in the Kubernetes api that doesn't exist (404). 
I'm using the [current master kubeflow](https://github.com/kubeflow/kubeflow/commit/ea43dfacf8216481ca2f1d9fcf90fc972392a6af) with Kubernetes v1.12 on EKS. I'm running a very simple setup in dedicated VPC, the only caveat is that i'm using dedicated IAM roles as I can't let eksctl create them on-demand unfortunately.

Can anyone help me debug the issue? 

Thanks a lot for this project and thank you in advance for your help!
Alessandro

**Comment by Jeffwan** [comment]
Looks like it's better to use a stable version for EKS. I will make some changes and cherry-pick to v0.5-branch. Then I will update documentation to use v0.5-branch later. This will give more stable environment.

**Comment by Jeffwan** [comment]
I will also check why notebook can not connected on master and come back to you later

**Comment by amarrella** [comment]
> Looks like it's better to use a stable version for EKS. I will make some changes and cherry-pick to v0.5-branch. Then I will update documentation to use v0.5-branch later. This will give more stable environment.

Hi @Jeffwan , thanks for looking into this. The v0.5.1 binary seems broken as it doesn't support the `--provider aws`. The v0.5.1 version source seems to have some conflict with Istio and Ambassador, making the ambassador pods continuously crash. I'll open separate issues for those.

**Comment by Jeffwan** [comment]
@amarrella I mean use v0.5-branch kfctl.sh. 

```
export KUBEFLOW_SRC=/tmp/kubeflow-aws
unset KUBEFLOW_TAG # in case you set this env.
export KUBEFLOW_VERSION=v0.5-branch
mkdir -p ${KUBEFLOW_SRC} && cd ${KUBEFLOW_SRC}
curl https://raw.githubusercontent.com/kubeflow/kubeflow/${KUBEFLOW_VERSION}/scripts/download.sh | bash
```

And then edit `${KUBEFLOW_SRC}/scripts/aws/util.sh` to add following changes before your `apply k8s`. I will make this PR cherry-picked back to 0.5. 

https://github.com/kubeflow/kubeflow/pull/3340/files

**Comment by Jeffwan** [comment]
```
jquery.min.js:2 POST http://xxxx.us-west-2.elb.amazonaws.com/jupyter/api/namespaces/kubeflow/notebooks 500 (Internal Server Error)
```

I can reproduce this issue in master branch, Let me check what is changed on note book controller side.

**Comment by Jeffwan** [comment]
https://github.com/kubeflow/kubeflow/commit/cee39dbcfec7303ac61d3fbb08031acdaec0886f#diff-90e7312f4e78e471ec9f0e7c91db6845

@zabbasi For aws, we have not integrated with admission-webhook. Could you check if that's why we see 404 for notebooks resources?  I check crds and I do see this here.

**Comment by zabbasi** [comment]
@Jeffwan if you are using  the updated image jupyter-web-app it has dependency to PodDefaults which is installed in admission-webhook componnet. Just check the log of jupyter-web-app  to see what the problem is.

**Comment by Jeffwan** [comment]
@amarrella Can you change to elder version temporarily?

```
kubectl -n kubeflow edit deployment jupyter-web-app

change image to `gcr.io/kubeflow-dev/jupyter-web-app:v0-43-g810b0b46`
```

Lastest change for PodDefault and AdmissionController is not compatible with current AWS settings

**Comment by amarrella** [comment]
> @amarrella I mean use v0.5-branch kfctl.sh.
export KUBEFLOW_SRC=/tmp/kubeflow-aws
unset KUBEFLOW_TAG # in case you set this env.
export KUBEFLOW_VERSION=v0.5-branch
mkdir -p ${KUBEFLOW_SRC} && cd ${KUBEFLOW_SRC}
curl https://raw.githubusercontent.com/kubeflow/kubeflow/${KUBEFLOW_VERSION}/scripts/download.sh | bash
And then edit ${KUBEFLOW_SRC}/scripts/aws/util.sh to add following changes before your apply k8s. I will make this PR cherry-picked back to 0.5.
https://github.com/kubeflow/kubeflow/pull/3340/files

This worked 👍

**Comment by graykode** [comment]
> export KUBEFLOW_VERSION=v0.5-branch

NOT `export KUBEFLOW_VERSION=v0.5-branch`
`export KUBEFLOW_VERSION=0.5-branch` is right and 
do `curl https://raw.githubusercontent.com/kubeflow/kubeflow/v0.5-branch/scripts/download.sh | bash`.

because in https://raw.githubusercontent.com/kubeflow/kubeflow/v0.5-branch/scripts/download.sh, character is added. `KUBEFLOW_TAG=v${KUBEFLOW_VERSION}` `v`

**Comment by Jeffwan** [comment]
@graykode Thanks for pointing this out. I think I unset `KUBEFLOW_TAG` and didn't figure out this issue. I will file a PR to make the change. `v0.5-branch` in the curl url also need to be parameterized. I will stick to KUBEFLOW_TAG.

```
export KUBEFLOW_SRC=/tmp/kubeflow-aws
export KUBEFLOW_TAG=v0.5-branch
mkdir -p ${KUBEFLOW_SRC} && cd ${KUBEFLOW_SRC}
curl https://raw.githubusercontent.com/kubeflow/kubeflow/${KUBEFLOW_TAG}/scripts/download.sh | bash
```

**Comment by graykode** [comment]
@Jeffwan Nice

**Comment by michael-balint** [comment]
Seeing the same issue in a recent on-prem deployment of K8s + Kubeflow. `KUBEFLOW_TAG` set to `v0.5-branch` does not help the situation. Any other thoughts?

```
$ kubectl -n kubeflow logs jupyter-web-app-864f9cdf8c-jkqkg
 * Serving Flask app "kubeflow_jupyter.default.app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
/usr/local/lib/python3.6/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.2) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
10.233.75.33 - - [11/Jun/2019 01:28:15] "GET / HTTP/1.1" 200 -
10.233.75.33 - - [11/Jun/2019 01:28:15] "GET /static/css/main.css HTTP/1.1" 200 -
10.233.75.33 - - [11/Jun/2019 01:28:15] "GET /static/css/dialog.css HTTP/1.1" 200 -
10.233.75.33 - - [11/Jun/2019 01:28:15] "GET /static/js/dialog.js HTTP/1.1" 200 -
10.233.75.33 - - [11/Jun/2019 01:28:15] "GET /static/js/notebooks.js HTTP/1.1" 200 -
10.233.75.33 - - [11/Jun/2019 01:28:16] "GET /api/namespaces/kubeflow/notebooks HTTP/1.1" 200 -
10.233.75.33 - - [11/Jun/2019 01:28:17] "GET /api/namespaces/kubeflow/notebooks HTTP/1.1" 200 -
10.233.75.33 - - [11/Jun/2019 01:28:18] "GET /api/namespaces/kubeflow/notebooks HTTP/1.1" 200 -
10.233.75.33 - - [11/Jun/2019 01:28:19] "GET /api/namespaces/kubeflow/notebooks HTTP/1.1" 200 -
10.233.102.170 - - [11/Jun/2019 01:28:21] "GET /api/namespaces/kubeflow/notebooks HTTP/1.1" 200 -
10.233.102.170 - - [11/Jun/2019 01:28:23] "GET /api/namespaces/kubeflow/notebooks HTTP/1.1" 200 -
10.233.102.170 - - [11/Jun/2019 01:28:24] "GET /new?namespace=kubeflow HTTP/1.1" 200 -
[2019-06-11 01:28:35,200] ERROR in app: Exception on /api/namespaces/kubeflow/notebooks [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/kubeflow_jupyter/default/app.py", line 40, in post_notebook
    poddefaultLabels = api.get_poddefaults_labels(namespace)
  File "/app/kubeflow_jupyter/common/api.py", line 123, in get_poddefaults_labels
    ns, "poddefaults")['items']
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/apis/custom_objects_api.py", line 1432, in list_namespaced_custom_object
    (data) = self.list_namespaced_custom_object_with_http_info(group, version, namespace, plural, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/apis/custom_objects_api.py", line 1538, in list_namespaced_custom_object_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 155, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 342, in request
    headers=headers)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/rest.py", line 231, in GET
    query_params=query_params)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Content-Type': 'text/plain; charset=utf-8', 'X-Content-Type-Options': 'nosniff', 'Date': 'Tue, 11 Jun 2019 01:28:35 GMT', 'Content-Length': '19'})
HTTP response body: 404 page not found


10.233.102.170 - - [11/Jun/2019 01:28:35] "POST /api/namespaces/kubeflow/notebooks HTTP/1.1" 500 -
```

**Comment by Jeffwan** [comment]
This issue has been fixed by the above PR I filed.  We can close this issue. Let me know any issues there.

/close
