### ISSUE TITLE
libcublas.so.10.0 missing on tensorflow-2.0.0a-notebook-gpu

### ISSUE THREAD

**Issue by valeriano-manassero** [kubeflow/kubeflow#3357]
I got a microk8s 1.13 on Ubuntu 8.04 LTS.

On the host I have:
`NVIDIA-SMI 410.104      Driver Version: 410.104      CUDA Version: 10.0`
I enabled gpu on microk8s and deployed Kubeflow v 0.5.0

I started a notebook with image `tensorflow-1.13.1-notebook-gpu` and everything is ok.

If I try to use image `tensorflow-2.0.0a-notebook-gpu` and I got this issue when `import tensorflow as tf`

This is the error:
```
ImportError: Traceback (most recent call last):
  File "/opt/conda/envs/py2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/opt/conda/envs/py2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/opt/conda/envs/py2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory
```

I'm confused since two images should share same base:
https://github.com/zabbasi/kubeflow/blob/master/components/tensorflow-notebook-image/versions/2.0.0a0gpu/version-config.json
https://github.com/zabbasi/kubeflow/blob/master/components/tensorflow-notebook-image/versions/1.13.1gpu/version-config.json

Any clue?

**Comment by jsnowacki** [comment]
I have the same thing using this image on GCP.

**Comment by zhangzewen** [comment]
I have the same thing using this image on kubernetes cluster

### k8s: 1.14.3,  kubeflow: 0.5.0

#### GPU node  info
```
> cat /etc/centos-release
CentOS Linux release 7.4.1708 (Core)
>  uname -a
Linux nb-lab-aitest1 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux


> /usr/local/cuda-10.0/bin/nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
> /usr/local/cuda-10.1/bin/nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Apr_24_19:10:27_PDT_2019
Cuda compilation tools, release 10.1, V10.1.168
> /usr/local/cuda/bin/nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Apr_24_19:10:27_PDT_2019
Cuda compilation tools, release 10.1, V10.1.168
```

#### GPU docker info

```
> docker version
Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        d7080c1
 Built:             Wed Feb 20 02:26:51 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       d7080c1
  Built:            Wed Feb 20 02:28:17 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

**Comment by jbottum** [comment]
@valeriano-manassero did you make progress on this ?

**Comment by valeriano-manassero** [comment]
> @valeriano-manassero did you make progress on this ?

I'm currently using a custom image I created. Since I was thinking new images were coming up fast with new versions of TF, I didn't prepared anything to share. If you need it, I can try to create something on github in some days.
