### ISSUE TITLE
Ambassador can't watch services at the cluster level.

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#373]
I'm using our dev deployment; dev.kubeflow.org and ambassador isn't working for me. The logs show the following error

```
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Audit-Id': '3de26b8c-301f-4488-9e3d-3d47ca2e0bec', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Wed, 07 Mar 2018 02:03:13 GMT', 'Content-Length': '320'})
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"services is forbidden: User \\"system:serviceaccount:kubeflow:ambassador\\" cannot watch services at the cluster scope: Unknown user \\"system:serviceaccount:kubeflow:ambassador\\"","reason":"Forbidden","details":{"kind":"services"},"code":403}\n'

2018-03-07 02:03:13 kubewatch 0.22.0 ERROR: could not watch for Kubernetes service changes
Traceback (most recent call last):
  File "/application/kubewatch.py", line 479, in main
    watch_loop(restarter)
  File "/application/kubewatch.py", line 382, in watch_loop
    for evt in watched:
  File "/usr/lib/python3.6/site-packages/kubernetes/watch/watch.py", line 115, in stream
    resp = func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 15124, in list_service_for_all_namespaces
    (data) = self.list_service_for_all_namespaces_with_http_info(**kwargs)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 15220, in list_service_for_all_namespaces_with_http_info
    collection_formats=collection_formats)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 335, in call_api
    _preload_content, _request_timeout)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 148, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 371, in request
    headers=headers)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/rest.py", line 250, in GET
    query_params=query_params)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/rest.py", line 240, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (403)
```

dev.kubeflow.org was working a couple weeks ago; I demo'd it at index.

It looks like an RBAC issue with ambassador; not sure why it would have changed. I think we did upgrade Ambassador at some point but not sure if that change happened in the dev cluster.

**Comment by jlewi** [comment]
Looks like this cluster is still using 0.22

```
quay.io/datawire/ambassador:0.22.0
```

Head now uses 0.26.0
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/core/ambassador.libsonnet#L14

**Comment by jlewi** [comment]
I see the cluster role

```
kubectl get clusterrole -o yaml ambassador
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: 2018-02-10T01:52:54Z
  name: ambassador
  resourceVersion: "6926"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/ambassador
  uid: 1c3bcb00-0e05-11e8-af40-42010a800fd0
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - update
  - patch
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
```

**Comment by jlewi** [comment]
ClusterRoleBinding is misconfigured

```
kubectl get clusterrolebinding ambassador -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: 2018-02-10T01:51:55Z
  name: ambassador
  resourceVersion: "2277146"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/ambassador
  uid: f903bad0-0e04-11e8-af40-42010a800fd0
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ambassador
subjects:
- kind: ServiceAccount
  name: ambassador
  namespace: agwl-experimental-issue-summarization-serving
```
The service account namespace should be kubeflow.

I think @ankushagarwal deployed an experimental deployment in a different namespace `agwl-experimental-issue-summarization-serving` and this ended up overriding the clusterrolebinding because clusterrolebindings aren't namespace scoped.

**Comment by jlewi** [comment]
If we do

```
kubectl --v=7 -n kubeflow get clusterrolebinding 
```

We see that the URL is

```
 GET https://35.184.183.224/apis/rbac.authorization.k8s.io/v1/clusterrolebindings
```

So its not namespace scoped.

**Comment by jlewi** [comment]
Recreate the clusterolebinding manually

```
kubectl create clusterrolebinding kubeflow-ambassador --clusterrole=ambassador --serviceaccount=kubeflow:ambassador
```
This fixed the issue.
