### ISSUE TITLE
v0.6.1 pod default issue

### ISSUE THREAD

**Issue by zhenghuiwang** [kubeflow/kubeflow#3770]
When creating a new notebook in `kubeflow-{user}` namespace after installation of v0.6.1, I see this error. But notebook can be created

```
500: There was an error trying to connect to the backend API. Http failure response for https://v061-rc2-mac.endpoints.zhenghui-kubeflow.cloud.goog/jupyter/api/namespaces/kubeflow-zhenghui/poddefaults: 500 OK
```

**Comment by jlewi** [comment]
@zhenghuiwang Where are you seeing the error?

@kimwnasptd Is this coming from the jupyter web-app trying to list PodDefaults to display in the UI?

**Comment by kimwnasptd** [comment]
@zhenghuiwang could you give us the logs from the `jupyter-web-app-deployment` Pod?

**Comment by zhenghuiwang** [comment]
Three relevant logs:
```
2019-07-29T17:22:34.727855921Z [2019-07-29 17:22:34,727] ERROR in app: Exception on /api/namespaces/kubeflow-zhenghui/poddefaults [GET]
 E 
  undefined


2019-07-29T17:22:34.727889728Z Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/kubeflow_jupyter/common/base_app.py", line 45, in get_poddefaults
    desc = pd["spec"]["desc"]
KeyError: 'desc'
 E 
  undefined

![Error report](https://user-images.githubusercontent.com/8263977/62068636-4552dc80-b1eb-11e9-8b02-22ec8fb665dd.png)

2019-07-29T17:22:34.728044213Z 10.40.1.29 - - [29/Jul/2019 17:22:34] "GET /api/namespaces/kubeflow-zhenghui/poddefaults HTTP/1.1" 500 -
 E 
  undefined
```

**Comment by zhenghuiwang** [comment]
![Screen shot](https://user-images.githubusercontent.com/8263977/62068652-4d128100-b1eb-11e9-9c7a-b24583dd4376.png)

**Comment by kimwnasptd** [comment]
@zhenghuiwang this is because (at least) one of the `PodDefaults` in the Namespace doesn't have a desc field. I was under the assumption that this field would be necessary and not optional, but by checking the [code](https://github.com/kubeflow/kubeflow/blob/master/components/admission-webhook/pkg/apis/settings/v1alpha1/poddefault_types.go#L38) turns out it is not.

Could you check which `PodDefault` is the one without a `desc`  and give it one? This should resolve the issue.

@jlewi would it make more sense to make this field `required` or should the webapp use the `PodDefault`'s label as a description, if the desc field is omitted?

**Comment by jlewi** [comment]
@kimwnasptd I think it would be good if the web app could support the case where description is not provided.

Would it make sense if no description is provided to just use the PodDefault's name?

**Comment by kimwnasptd** [comment]
ACK, I'll make a PR for the webapp to use the PodDefault's name in case the `desc` is not present.
