### ISSUE TITLE
Can't upgrade kubeflow 0.5.1 to 0.6.1

### ISSUE THREAD

**Issue by samuelthan** [kubeflow/kubeflow#3819]
/kind bug

**What steps did you take and what happened:**
Installed vanilla kubeflow version 0.5.1 on AWS EKS.

After successfull installation of 0.5.1, attempt upgrade to 0.6.1 referencing https://www.kubeflow.org/docs/other-guides/upgrade/

Downloaded new version via
`curl -OL https://github.com/kubeflow/kubeflow/releases/download/v0.6.1/kfctl_v0.6.1_darwin.tar.gz`

`export PATH=$PATH:/Users/username/tools/kubeflow/0.6.1
export KUBEFLOW_VERSION=v0.6.1
export KFAPP=kfapp
kfctl init ${KFAPP} --version=${KUBEFLOW_VERSION} --package-manager=kustomize@${KUBEFLOW_VERSION}

 cd ${KFAPP}
 kfctl generate all -V`

The above execute without problem. The following step returns a bunch of errors:
` 
kfctl apply all -V
`

_Error recieved:_
`NFO[0000] Downloading /tmp/kubeflow-aws/kfapp/app.yaml to /var/folders/s5/qfb6dpnj3yq57jr23kdgq5nj4pxscs/T/078119267/app.yaml  filename="v1alpha1/application_types.go:334"
INFO[0000] Writing stripped KfDef to /tmp/kubeflow-aws/kfapp/app.yaml  filename="v1alpha1/application_types.go:626"
INFO[0000] Downloading /tmp/kubeflow-aws/kfapp/app.yaml to /var/folders/s5/qfb6dpnj3yq57jr23kdgq5nj4pxscs/T/099988838/app.yaml  filename="v1alpha1/application_types.go:334"
INFO[0000] Initializing a default restConfig for Kubernetes  filename="kustomize/kustomize.go:248"
WARN[0000] could not open /Users/USERNAME/.kube/kubeconfig_ai-eks-cluster:/Users/USERNAME/.kube/kube-config-eks Error stat /Users/USERNAME/.kube/kubeconfig_ai-eks-cluster:/Users/USERNAME/.kube/kube-config-eks: no such file or directory  filename="apps/group.go:234"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5db16c1]

goroutine 1 [running]:
k8s.io/client-go/v2/kubernetes.NewForConfig(0x0, 0x0, 0x0, 0x0)
	/tmp/v2/k8s.io/client-go/kubernetes/clientset.go:447 +0x51
github.com/kubeflow/kubeflow/bootstrap/v2/pkg/apis/apps.GetClientset(0x0, 0x0)
	/Users/zhenghui/kubeflow/kubeflow/bootstrap/v2/pkg/apis/apps/group.go:262 +0x5d
github.com/kubeflow/kubeflow/bootstrap/v2/pkg/kfapp/kustomize.(*kustomize).Apply(0xc0002bcb40, 0x652c70a, 0x3, 0x0, 0x0)
	/Users/zhenghui/kubeflow/kubeflow/bootstrap/v2/pkg/kfapp/kustomize/kustomize.go:263 +0x234
github.com/kubeflow/kubeflow/bootstrap/pkg/kfapp/coordinator.(*coordinator).Apply.func2(0x0, 0x0)
	/Users/zhenghui/kubeflow/kubeflow/bootstrap/pkg/kfapp/coordinator/coordinator.go:749 +0x12e
github.com/kubeflow/kubeflow/bootstrap/pkg/kfapp/coordinator.(*coordinator).Apply(0xc000512040, 0x652c626, 0x3, 0x0, 0x0)
	/Users/zhenghui/kubeflow/kubeflow/bootstrap/pkg/kfapp/coordinator/coordinator.go:782 +0x229
github.com/kubeflow/kubeflow/bootstrap/cmd/kfctl/cmd.glob..func1(0x7d13ba0, 0xc000547ba0, 0x1, 0x2, 0x0, 0x0)
	/Users/zhenghui/kubeflow/kubeflow/bootstrap/cmd/kfctl/cmd/apply.go:46 +0x4cb
github.com/spf13/cobra.(*Command).execute(0x7d13ba0, 0xc000547b80, 0x2, 0x2, 0x0, 0x0)
	/Users/zhenghui/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762 +0xb4a
github.com/spf13/cobra.(*Command).ExecuteC(0x7d13e00, 0x7d13ba0, 0x0, 0x0)
	/Users/zhenghui/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x6bb
github.com/spf13/cobra.(*Command).Execute(0x7d13e00, 0x0, 0x0)
	/Users/zhenghui/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800 +0x3b
github.com/kubeflow/kubeflow/bootstrap/cmd/kfctl/cmd.Execute(0x695cc10, 0x17)
	/Users/zhenghui/kubeflow/kubeflow/bootstrap/cmd/kfctl/cmd/root.go:61 +0x6d
main.main()
	/Users/zhenghui/kubeflow/kubeflow/bootstrap/cmd/kfctl/main.go:36 +0x39
`

**What did you expect to happen:**
Upgrade to complete

**Anything else you would like to add:**

**Environment:**
- kfctl version: kfctl v0.6.1-rc.2-1-g3a37cbc6
- Kubernetes platform: AWS EKS
- Kubernetes version: `Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T14:25:20Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"darwin/amd64"}`
- OS: MacOS X

**Comment by samuelthan** [comment]
Discovered that the issue is at my bash profile end.

My bash profile had this 

`export KUBECONFIG=/Users/USERNAME/.kube/kubeconfig_ai-eks-cluster:/Users/USERNAME/.kube/kube-config-eks`

After cleaning it up to look like this 

`export KUBECONFIG=/Users/USERNAME/.kube/kubeconfig_ai-eks-cluster`

I
