### ISSUE TITLE
central dashboard  (RC) takes a really long time to load

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3915]
/kind bug

I'm testing out the upcoming central dashboard
gcr.io/kubeflow-images-public/centraldashboard:v20190808-v0.6.2-rc.0-0-g65583158

When I first go to the page I get a blank screen even though chrome tools shows a bunch of successful requests.

It looks like the following request is returning a 502

```
vendor.bundle.js:765 GET https://jlewi-0-6-2-rc.endpoints.jlewi-dev.cloud.goog/api/workgroup/exists 502
send @ vendor.bundle.js:765
generateRequest @ vendor.bundle.js:765
(anonymous) @ vendor.bundle.js:765
(anonymous) @ vendor.bundle.js:1
window.MutationObserver.observe.characterData @ vendor.bundle.js:1
characterData (async)
run @ vendor.bundle.js:1
async @ vendor.bundle.js:1051
_nameChanged @ vendor.bundle.js:1051
L @ vendor.bundle.js:825
w @ vendor.bundle.js:825
M @ vendor.bundle.js:825
_propertiesChanged @ vendor.bundle.js:825
_flushProperties @ vendor.bundle.js:1657
_flushProperties @ vendor.bundle.js:825
ready @ vendor.bundle.js:825
ready @ vendor.bundle.js:825
ready @ vendor.bundle.js:1051
ready @ vendor.bundle.js:1051
ready @ vendor.bundle.js:1657
_enableProperties @ vendor.bundle.js:1657
connectedCallback @ vendor.bundle.js:825
connectedCallback @ vendor.bundle.js:825
connectedCallback @ vendor.bundle.js:1051
connectedCallback @ vendor.bundle.js:1051
(anonymous) @ vendor.bundle.js:686
i @ app.bundle.js:1
371 @ app.bundle.js:1
i @ app.bundle.js:1
t @ app.bundle.js:1
280 @ app.bundle.js:1
(anonymous) @ app.bundle.js:1
(anonymous) @ app.bundle.js:1
(anonymous) @ app.bundle.js:1
```
And takes 1 minute.

if I wait the page successfully renders

I do have a profile

```
kubectl get profiles
NAME             AGE
kubeflow-jlewi   30m
```

/assign @avdaredevil

**Comment by jlewi** [comment]
I'm not able to select any namespaces. 

I also do not see any admin option to create profiles.

**Comment by jlewi** [comment]
kfam server is running and shows no errrors in logs

```
kubectl -n kubeflow logs profiles-deployment-85c56cc7c-v2hwq kfam
time="2019-08-16T04:14:29Z" level=info msg="Server started"
```

**Comment by jlewi** [comment]
Here's the virtual service for kfam

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: 2019-08-16T04:13:18Z
  generation: 1
  name: kfam
  namespace: kubeflow
  resourceVersion: "4557"
  selfLink: /apis/networking.istio.io/v1alpha3/namespaces/kubeflow/virtualservices/kfam
  uid: 2d55574c-bfdc-11e9-82c7-42010a8e010d
spec:
  gateways:
  - kubeflow-gateway
  hosts:
  - '*'
  http:
  - headers:
      request:
        add:
          x-forwarded-prefix: /kfam
    match:
    - uri:
        prefix: /kfam/
    rewrite:
      uri: /kfam/
    route:
    - destination:
        host: profiles-kfam.kubeflow.svc.cluster.local
        port:
          number: 8081
```

So is the URL wrong?

**Comment by jlewi** [comment]
I think that's a red herring; I think the client side JS talks to the centraldashboard backend.

Here are the logs for the centraldashboard

```
. (rejection id: 24)
(node:29) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:8084
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
(node:29) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 25)
(node:29) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:8084
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
(node:29) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 26)
```

**Comment by jlewi** [comment]
I think this is the issue with the centraldashboard relying on environment variables to set the URL of the backend.

I deleted the centraldashboard pod.

Now centraldashboard starts and I see the following in the logs

```
> kubeflow-centraldashboard@0.0.2 start /app
> npm run serve


> kubeflow-centraldashboard@0.0.2 serve /app
> node dist/server.js

Initializing Kubernetes configuration
Using Profiles service at http://10.55.255.198:8081/kfam
Server listening on port http://localhost:8082
```

Now I'm able to load the centraldasbhoard without delay 
and I can see my namespace.

**Comment by jlewi** [comment]
Duplication of #3915

**Comment by jlewi** [comment]
Duplicate of #3915
