### ISSUE TITLE
Failed to start Ambassador on Gravity K8S distribution

### ISSUE THREAD

**Issue by vakrat1** [kubeflow/kubeflow#4700]
I'm trying to deploy the stable/ambassador helm chart onto Gravity distribution of K8S.
While K8S is trying to load Ambassador's pod the following error message is being thrown:

`kubectl logs -f pod/ambassador-69b784f9d5-xzmg8`

`2020-01-28 21:10:23 kubewatch [9 TMainThread] 0.86.1 DEBUG: looking up ID for namespace default`

`2020-01-28 21:10:23 kubewatch [9 TMainThread] 0.86.1 DEBUG: cluster ID URL is d6e_id://3a11dee4-acbd-4d41-9247-cf3cf0d9e93a/default`

`Traceback (most recent call last):
  File "/ambassador/kubewatch.py", line 270, in <module>
    main()
  File "/usr/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/ambassador/kubewatch.py", line 235, in main
    if not check_ingresses():
  File "/ambassador/kubewatch.py", line 122, in check_ingresses
    k8s_v1b1.list_ingress_for_all_namespaces()
  File "/usr/lib/python3.7/site-packages/kubernetes/client/apis/extensions_v1beta1_api.py", line 2765, in list_ingress_for_all_namespaces
    (data) = self.list_ingress_for_all_namespaces_with_http_info(**kwargs)
  File "/usr/lib/python3.7/site-packages/kubernetes/client/apis/extensions_v1beta1_api.py", line 2862, in list_ingress_for_all_namespaces_with_http_info
    collection_formats=collection_formats)
  File "/usr/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 163, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "/usr/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 236, in deserialize
    return self.__deserialize(data, response_type)
  File "/usr/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 276, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 622, in __deserialize_model
    instance = klass(**kwargs)
  File "/usr/lib/python3.7/site-packages/kubernetes/client/models/v1beta1_ingress_list.py", line 60, in __init__
    self.items = items
  File "/usr/lib/python3.7/site-packages/kubernetes/client/models/v1beta1_ingress_list.py", line 110, in items
    raise ValueError("Invalid value for items, must not be None")
ValueError: Invalid value for items, must not be None`

`2020-01-28 21:10:24 AMBASSADOR INFO could not determine cluster-id; exiting`

**Comment by jlewi** [comment]
Ambassador is no longer part of Kubeflow and it sounds like you are installing it yourself.

I would suggest using Ambassador's forums to get help with Ambassador.
