### ISSUE TITLE
Parsing error when attempting to upload pipeline using kfp SDK

### ISSUE THREAD

**Issue by akchinSTC** [kubeflow/kubeflow#4830]
/kind bug

**What steps did you take and what happened:**

When attempting to submit a pipeline compiled with the kfp SDK (0.2.0) to a kubeflow v1.0 deployment using the kfp python client -> upload_pipeline method I get a parsing error as follows:
```
Traceback (most recent call last):
  File "/Users/akchin@us.ibm.com/miniconda3/envs/py37/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-9200d7fc99e6>", line 1, in <module>
    response = client.upload_pipeline("my-pipeline.zip", pipeline_name="testme4")
  File "/Users/akchin@us.ibm.com/miniconda3/envs/py37/lib/python3.7/site-packages/kfp/_client.py", line 484, in upload_pipeline
    response = self._upload_api.upload_pipeline(pipeline_package_path, name=pipeline_name)
  File "/Users/akchin@us.ibm.com/miniconda3/envs/py37/lib/python3.7/site-packages/kfp_server_api/api/pipeline_upload_service_api.py", line 55, in upload_pipeline
    (data) = self.upload_pipeline_with_http_info(uploadfile, **kwargs)  # noqa: E501
  File "/Users/akchin@us.ibm.com/miniconda3/envs/py37/lib/python3.7/site-packages/kfp_server_api/api/pipeline_upload_service_api.py", line 135, in upload_pipeline_with_http_info
    collection_formats=collection_formats)
  File "/Users/akchin@us.ibm.com/miniconda3/envs/py37/lib/python3.7/site-packages/kfp_server_api/api_client.py", line 330, in call_api
    _preload_content, _request_timeout)
  File "/Users/akchin@us.ibm.com/miniconda3/envs/py37/lib/python3.7/site-packages/kfp_server_api/api_client.py", line 169, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "/Users/akchin@us.ibm.com/miniconda3/envs/py37/lib/python3.7/site-packages/kfp_server_api/api_client.py", line 241, in deserialize
    return self.__deserialize(data, response_type)
  File "/Users/akchin@us.ibm.com/miniconda3/envs/py37/lib/python3.7/site-packages/kfp_server_api/api_client.py", line 280, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/Users/akchin@us.ibm.com/miniconda3/envs/py37/lib/python3.7/site-packages/kfp_server_api/api_client.py", line 624, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/Users/akchin@us.ibm.com/miniconda3/envs/py37/lib/python3.7/site-packages/kfp_server_api/api_client.py", line 280, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/Users/akchin@us.ibm.com/miniconda3/envs/py37/lib/python3.7/site-packages/kfp_server_api/api_client.py", line 624, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/Users/akchin@us.ibm.com/miniconda3/envs/py37/lib/python3.7/site-packages/kfp_server_api/api_client.py", line 278, in __deserialize
    return self.__deserialize_datatime(data)
  File "/Users/akchin@us.ibm.com/miniconda3/envs/py37/lib/python3.7/site-packages/kfp_server_api/api_client.py", line 590, in __deserialize_datatime
    return parse(string)
  File "/Users/akchin@us.ibm.com/miniconda3/envs/py37/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/Users/akchin@us.ibm.com/miniconda3/envs/py37/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 646, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "/Users/akchin@us.ibm.com/miniconda3/envs/py37/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 725, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "/Users/akchin@us.ibm.com/miniconda3/envs/py37/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 207, in split
    return list(cls(s))
  File "/Users/akchin@us.ibm.com/miniconda3/envs/py37/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 76, in __init__
    '{itype}'.format(itype=instream.__class__.__name__))
TypeError: Parser must be a string or character stream, not dict
```

**What did you expect to happen:**
The submission to succeed and server response object containing pipleine id and other information to be returned.

**Anything else you would like to add:**
Doing some digging, I encountered this bug with the same symptoms utilizing the CLI vs using the python client. 
https://github.com/kubeflow/pipelines/issues/2764
and associated PR: https://github.com/kubeflow/pipelines/pull/2876/files

The fix was merged on the 29th of Jan but the 0.2.0 release was cut on the 20th. So it only made it into the 0.2.1 release.

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): v1.0
- kfctl version: (use `kfctl version`): kfctl v1.0-0-g94c35cf
- Kubernetes platform: (e.g. `minikube`) minikube
- Kubernetes version: (use `kubectl version`): 1.15.2
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.4 LTS

**Comment by Tomcli** [comment]
https://github.com/kubeflow/pipelines/blob/00a2cad3cfa81fc6b6b00b4f15a9faf5cbfe5d59/sdk/python/setup.py#L35
It looks like the kfp has dependency for kfp-server-api <=0.1.40 and 0.1.40 is the version that having this issue.

**Comment by JohanWork** [comment]
I have continued to debug this error with @NikeNano  and it seams that there is one timestamp that is a unix-timestamp and therefore it crashes. Believe the error originates from the swagger files, by changing in the api_clien.py file that is generate from the swagger fil. You can get it to work, but the true fix is in the swagger file. My knowledge here is very limited however.

**Comment by apryiomka** [comment]
does anyone have a workaround for this, i cannot really use the UI since the pipeline is uploaded as part of CI/Cd process?

**Comment by akchinSTC** [comment]
> does anyone have a workaround for this, i cannot really use the UI since the pipeline is uploaded as part of CI/Cd process?

I pinned to an older version of kfp-server-api when compiling. 
`kfp-server-api==0.1.18.3`

**Comment by dilzeem** [comment]
I am also getting this error with `kfp-server-api=0.3.0`

the pipeline uploads, but still get this error

**Comment by JohanWork** [comment]
I have been able to get it to work with a stand alone deployment with 0.3.0

**Comment by dilzeem** [comment]
I am deploying via kubeflow with aws .... i tried changing the manifest to have v 0.3.0 but it didn't seem to fix it for some reason. 

Its seems like they are aware of it here: 
#https://github.com/kubeflow/manifests/issues/984
