### ISSUE TITLE
Requirements.txt missing from pip package

### ISSUE THREAD

**Issue by bomerzz** [kubeflow/kubeflow#5035]
/kind bug

pip install kubeflow-fairing
Collecting kubeflow-fairing
  Downloading https://files.pythonhosted.org/packages/ab/7a/45aa727f59386aa0bccd1314c4c3837352eb04c43836c25871fbc372abca/kubeflow-fairing-0.7.2.tar.gz (98kB)
    100% |████████████████████████████████| 102kB 913kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-HVs6FX/kubeflow-fairing/setup.py", line 3, in <module>
        with open('requirements.txt') as f:
    IOError: [Errno 2] No such file or directory: 'requirements.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-HVs6FX/kubeflow-fairing/

Within the tar.gz the requirements.txt is missing and not packaged together

**Comment by bomerzz** [comment]
Wrong repo. My bad
