### ISSUE TITLE
Spark operator within Kubeflow

### ISSUE THREAD

**Issue by marwanfahmi** [kubeflow/kubeflow#5043]
Hello,

I'm trying to execute a Spark job in a Kubeflow pipeline using a resourceOp, I'm using Kubeflow on GCP instance running a private GKE. I have an issue getting this to work in the KF namespace, I get a java socket closed message, however, when I try to install the operator in another namespace and execute the job manually it works. The KF pipeline runs in the KF namespace.

What could be preventing the Spark operator to create a pod and run it in the KF namespace? Any help would be very much appreciated. Thanks.

**Comment by jlewi** [comment]
Are you able to run spark jobs in the KF namespace directly without using pipelines to launch the spark job?

I'm unclear about the connection is between the java socket closed error and the spark operator not being able to create a pod. What is the connection between these two? What is reporting the java socket closed and how does this relate to pod creation?

/cc @holdenk

**Comment by holdenk** [comment]
Can you send the error logs from the operator? I'm a bit confused by what you're experiencing.

**Comment by marwanfahmi** [comment]
Hi @holdenk & @jlewi,

Basically, I have the operator installed into the KF namespace. When I try to execute a spark job using this operator it fails with error:

`Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: Operation: [create]  for kind: [Pod]  with name: [null]  in namespace: [kubeflow]  failed.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:72)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:337)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:330)
	at org.apache.spark.deploy.k8s.submit.Client$$anonfun$run$2.apply(KubernetesClientApplication.scala:141)
	at org.apache.spark.deploy.k8s.submit.Client$$anonfun$run$2.apply(KubernetesClientApplication.scala:140)
	at org.apache.spark.util.Utils$.tryWithResource(Utils.scala:2543)
	at org.apache.spark.deploy.k8s.submit.Client.run(KubernetesClientApplication.scala:140)
	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication$$anonfun$run$5.apply(KubernetesClientApplication.scala:250)
	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication$$anonfun$run$5.apply(KubernetesClientApplication.scala:241)
	at org.apache.spark.util.Utils$.tryWithResource(Utils.scala:2543)
	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.run(KubernetesClientApplication.scala:241)
	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.start(KubernetesClientApplication.scala:204)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:845)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)`

However, when I install the operator in another namespace, it works with no issues. I've attached the operator log. Please let me know if any further clarification is required.

[operator.log](https://github.com/kubeflow/kubeflow/files/4723089/operator.log)

**Comment by hellodk** [comment]
Did this worked for you?
