### ISSUE TITLE
Unable to Install MiniKF 

### ISSUE THREAD

**Issue by naveensrinivasan** [kubeflow/kubeflow#5415]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
- Followed the instruction for installing the MiniKF on OSX. 
- Vagrant plugin is installed for `vagrant-persistent-storage`

**What did you expect to happen:**
- Installation of MiniKF

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
```
An unexpected exception has occurred
Line: /home/vagrant/provision.py:1822
Type: EnvironmentError
Reason: No extra disk found. Please attach at least one extra disk to this instance, apart from its boot disk

The logfile `/home/vagrant/provision.log' may contain more information on this error, including a backtrace.

*** MiniKF provisioning tool terminated. Press Enter to restart, Ctrl-C to exit... ***
```
```
^C
2020-11-17T10:38:20.208059-0800 provision.py pid=1450/tid=1450/pytid=140480264292096 blkutils:306 [INFO] Ignoring non-disk block device `/dev/sda1'
2020-11-17T10:38:20.210951-0800 provision.py pid=1450/tid=1450/pytid=140480264292096 cmdutils:829 [INFO] [kVUiNX_K43c] Started command with PID 2978: lsblk -n -p -o TYPE -d /dev/sda
2020-11-17T10:38:20.212285-0800 provision.py pid=1450/tid=2979/pytid=140480150021888 cmdutils:536 [INFO] [kVUiNX_K43c] Command exited with ret: 0
2020-11-17T10:38:20.217103-0800 provision.py pid=1450/tid=1450/pytid=140480264292096 cmdutils:829 [INFO] [5kNqwsimesw] Started command with PID 2982: blockdev --getsz /dev/sda
2020-11-17T10:38:20.217910-0800 provision.py pid=1450/tid=2983/pytid=140480150021888 cmdutils:536 [INFO] [5kNqwsimesw] Command exited with ret: 0
2020-11-17T10:38:20.218699-0800 provision.py pid=1450/tid=1450/pytid=140480264292096 provision:1821 [CRITICAL] No extra disk found. Please attach at least one extra disk to this instance, apart from its boot disk
2020-11-17T10:38:20.222934-0800 provision.py pid=1450/tid=1450/pytid=140480264292096 cli:149 [CRITICAL] An unexpected exception has occured
2020-11-17T10:38:20.224064-0800 provision.py pid=1450/tid=1450/pytid=140480264292096 cli:150 [CRITICAL] Traceback (most recent call last):\n  File "build/bdist.linux-x86_64/egg/rok_tasks/frontend/cli.py", line 131, in run\n  File "/home/vagrant/provision.py", line 3923, in main\n    provision_storage(use_thin_provisioning)\n  File "/home/vagrant/provision.py", line 692, in wrapper\n    ret = func(*args, **kwargs)\n  File "/home/vagrant/provision.py", line 1822, in provision_storage\n    raise EnvironmentError(msg)\nEnvironmentError: No extra disk found. Please attach at least one extra disk to this instance, apart from its boot disk\n
2020-11-17T10:38:26.840147-0800 provision.py pid=3007/tid=3007/pytid=139987219564288 fileutils:308 [INFO] Successfully created directory '/home/vagrant/.minikf'
2020-11-17T10:38:26.840697-0800 provision.py pid=3007/tid=3007/pytid=139987219564288 question:515 [INFO] Used answer from preseeds for question `question/unattended_execution (Answer: no)': `no'
2020-11-17T10:38:26.840815-0800 provision.py pid=3007/tid=3007/pytid=139987219564288 base:306 [INFO] Welcome to the MiniKF Provisioning tool.\n\nAbout to provision:\n* Docker\n* Minikube\n* Kubeflow\n* Rok\n\nThis can take up to 30', depending on the quality of your network connection.
```

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: (use `kfctl version`):
- Kubernetes platform: (e.g. `minikube`)
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`): OSX
- vagrant version: 2.2.13
- vagrant plugin list
   - vagrant-persistent-storage (0.0.49, global)

**Comment by jbottum** [comment]
@naveensrinivasan Hi Naveen, did you get this resolved?  How much ram do you have on your server?
