### ISSUE TITLE
Multiple Pods stucks in CrashLoopBackOff 

### ISSUE THREAD

**Issue by anneum** [kubeflow/kubeflow#5468]
/kind bug

**What steps did you take and what happened:**
Installed Kubeflow on an onpremise kubenetes cluster.
Multiple Pods stuck in CrashLoopBackOff
ml-pipeline-viewer-controller-deployment
katib-db-manager
katib-mysql

**What did you expect to happen:**
Expect that the pods start normal

**Anything else you would like to add:**

**Environment:**

- Kubeflow version: build version v1beta1
- kfctl version: kfctl v1.2.0-0-gbc038f9
- Kubernetes platform: OnPremise Cluster
- Kubernetes version: v1.17.0
- OS: Ubuntu 18.04.5 LTS

Kubeflow 1.2 deployed via [deepops](https://github.com/NVIDIA/deepops/blob/master/docs/k8s-cluster/kubeflow.md) Script  behind a corporate proxy on an onpremise cluster with two nodes.

Dont get it why the pods doesnt came up normaly. I tried different sql version for katib-mysql as i seen in another issue.
Since I have been struggling with this error for days and have already repeatedly roll out the Kubeflow installation several times any help is appreciated.

### katib-db-manager
```
Name:         katib-db-manager-6c88c68d79-6snxk
Namespace:    kubeflow
Priority:     0
Node:         
Start Time:   Fri, 18 Dec 2020 09:51:32 +0000
Labels:       app=katib
              app.kubernetes.io/component=katib
              app.kubernetes.io/name=katib-controller
              component=db-manager
              pod-template-hash=6c88c68d79
Annotations:  sidecar.istio.io/inject: false
Status:       Running
IP:           10.233.109.174
IPs:
  IP:           10.233.109.174
Controlled By:  ReplicaSet/katib-db-manager-6c88c68d79
Containers:
  katib-db-manager:
    Container ID:  docker://4dbffc611ba96d68f8bad62a6963544f4aa744cf1d375ad70798f85beb4d53c6
    Image:         docker.io/kubeflowkatib/katib-db-manager:v1beta1-a96ff59
    Image ID:      docker-pullable://kubeflowkatib/katib-db-manager@sha256:c4718dcc37ca5d4a0985314d4657b9c4357109265b823165f593bfb1c8ecc2f4
    Port:          6789/TCP
    Host Port:     0/TCP
    Command:
      ./katib-db-manager
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Fri, 18 Dec 2020 10:27:23 +0000
      Finished:     Fri, 18 Dec 2020 10:28:24 +0000
    Ready:          False
    Restart Count:  11
    Liveness:       exec [/bin/grpc_health_probe -addr=:6789] delay=10s timeout=1s period=60s #success=1 #failure=5
    Readiness:      exec [/bin/grpc_health_probe -addr=:6789] delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment:
      DB_NAME:      mysql
      DB_PASSWORD:  <set to the key 'MYSQL_ROOT_PASSWORD' in secret 'katib-mysql-secrets'>  Optional: false
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-5vvg8 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  default-token-5vvg8:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-5vvg8
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  41m                  default-scheduler  Successfully assigned kubeflow/katib-db-manager-6c88c68d79-6snxk to 
  Warning  Unhealthy  38m (x2 over 39m)    kubelet            Liveness probe failed: timeout: failed to connect service ":6789" within 1s
  Normal   Pulled     38m (x3 over 40m)    kubelet            Container image "docker.io/kubeflowkatib/katib-db-manager:v1beta1-a96ff59" already present on machine
  Normal   Created    38m (x3 over 40m)    kubelet            Created container katib-db-manager
  Normal   Started    38m (x3 over 40m)    kubelet            Started container katib-db-manager
  Warning  Unhealthy  10m (x48 over 40m)   kubelet            Readiness probe failed: timeout: failed to connect service ":6789" within 1s
  Warning  BackOff    28s (x142 over 38m)  kubelet            Back-off restarting failed container
```

```
kubectl -nkubeflow logs katib-db-manager-6c88c68d79-6snxk
E1218 10:39:50.481923       1 mysql.go:62] Ping to Katib db failed: dial tcp 10.233.28.55:3306: connect: connection refused
E1218 10:39:55.473955       1 mysql.go:62] Ping to Katib db failed: dial tcp 10.233.28.55:3306: connect: connection refused
E1218 10:40:00.501934       1 mysql.go:62] Ping to Katib db failed: dial tcp 10.233.28.55:3306: connect: connection refused
E1218 10:40:05.493921       1 mysql.go:62] Ping to Katib db failed: dial tcp 10.233.28.55:3306: connect: connection refused
E1218 10:40:10.481945       1 mysql.go:62] Ping to Katib db failed: dial tcp 10.233.28.55:3306: connect: connection refused
E1218 10:40:15.473935       1 mysql.go:62] Ping to Katib db failed: dial tcp 10.233.28.55:3306: connect: connection refused
E1218 10:40:20.501949       1 mysql.go:62] Ping to Katib db failed: dial tcp 10.233.28.55:3306: connect: connection refused
E1218 10:40:25.493786       1 mysql.go:62] Ping to Katib db failed: dial tcp 10.233.28.55:3306: connect: connection refused
E1218 10:40:30.481967       1 mysql.go:62] Ping to Katib db failed: dial tcp 10.233.28.55:3306: connect: connection refused
E1218 10:40:35.473947       1 mysql.go:62] Ping to Katib db failed: dial tcp 10.233.28.55:3306: connect: connection refused
E1218 10:40:40.497801       1 mysql.go:62] Ping to Katib db failed: dial tcp 10.233.28.55:3306: connect: connection refused
E1218 10:40:45.489989       1 mysql.go:62] Ping to Katib db failed: dial tcp 10.233.28.55:3306: connect: connection refused
F1218 10:40:45.490077       1 main.go:83] Failed to open db connection: DB open failed: Timeout waiting for DB conn successfully opened.
goroutine 1 [running]:
github.com/kubeflow/katib/vendor/k8s.io/klog.stacks(0xc0001b8500, 0xc0001e8000, 0x89, 0xd0)
        /go/src/github.com/kubeflow/katib/vendor/k8s.io/klog/klog.go:830 +0xb9
github.com/kubeflow/katib/vendor/k8s.io/klog.(*loggingT).output(0xc72b20, 0xc000000003, 0xc0001abb90, 0xc14079, 0x7, 0x53, 0x0)
        /go/src/github.com/kubeflow/katib/vendor/k8s.io/klog/klog.go:781 +0x2da
github.com/kubeflow/katib/vendor/k8s.io/klog.(*loggingT).printf(0xc72b20, 0x3, 0x92bfcd, 0x20, 0xc0001b1f48, 0x1, 0x1)
        /go/src/github.com/kubeflow/katib/vendor/k8s.io/klog/klog.go:678 +0x153
github.com/kubeflow/katib/vendor/k8s.io/klog.Fatalf(...)
        /go/src/github.com/kubeflow/katib/vendor/k8s.io/klog/klog.go:1209
main.main()
        /go/src/github.com/kubeflow/katib/cmd/db-manager/v1beta1/main.go:83 +0x166
```

### katib-mysql
```
Name:         katib-mysql-858f68f588-grp6g
Namespace:    kubeflow
Priority:     0
Node:         
Start Time:   Fri, 18 Dec 2020 10:36:06 +0000
Labels:       app=katib
              app.kubernetes.io/component=katib
              app.kubernetes.io/name=katib-controller
              component=mysql
              pod-template-hash=858f68f588
Annotations:  sidecar.istio.io/inject: false
Status:       Running
IP:           10.233.123.139
IPs:
  IP:           10.233.123.139
Controlled By:  ReplicaSet/katib-mysql-858f68f588
Containers:
  katib-mysql:
    Container ID:  docker://b99417fd01dbf5254bccb9813c697a770276d7075da13ededd9a475cd135acf6
    Image:         mysql:8
    Image ID:      docker-pullable://mysql@sha256:365e891b22abd3336d65baefc475b4a9a1e29a01a7b6b5be04367fcc9f373bb7
    Port:          3306/TCP
    Host Port:     0/TCP
    Args:
      --datadir
      /var/lib/mysql/datadir
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Fri, 18 Dec 2020 10:36:44 +0000
      Finished:     Fri, 18 Dec 2020 10:36:50 +0000
    Ready:          False
    Restart Count:  2
    Liveness:       exec [/bin/bash -c mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}] delay=30s timeout=5s period=10s #success=1 #failure=3
    Readiness:      exec [/bin/bash -c mysql -D ${MYSQL_DATABASE} -u root -p${MYSQL_ROOT_PASSWORD} -e 'SELECT 1'] delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment:
      MYSQL_ROOT_PASSWORD:         <set to the key 'MYSQL_ROOT_PASSWORD' in secret 'katib-mysql-secrets'>  Optional: false
      MYSQL_ALLOW_EMPTY_PASSWORD:  true
      MYSQL_DATABASE:              katib
    Mounts:
      /var/lib/mysql from katib-mysql (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-5vvg8 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  katib-mysql:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  katib-mysql
    ReadOnly:   false
  default-token-5vvg8:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-5vvg8
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  64s                default-scheduler  Successfully assigned kubeflow/katib-mysql-858f68f588-grp6g to 
  Normal   Pulled     27s (x3 over 63s)  kubelet            Container image "mysql:8" already present on machine
  Normal   Created    26s (x3 over 63s)  kubelet            Created container katib-mysql
  Normal   Started    26s (x3 over 63s)  kubelet            Started container katib-mysql
  Warning  Unhealthy  20s (x2 over 49s)  kubelet            Readiness probe failed: mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 104
  Warning  BackOff  10s (x4 over 49s)  kubelet  Back-off restarting failed container
```
```
kubectl -nkubeflow logs katib-mysql-858f68f588-grp6g
2020-12-18 10:38:12+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.22-1debian10 started.
2020-12-18 10:38:12+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2020-12-18 10:38:12+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.22-1debian10 started.
2020-12-18T10:38:13.171114Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.22) starting as process 1
2020-12-18T10:38:13.304511Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2020-12-18T10:38:15.094813Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
mysqld: Table 'mysql.plugin' doesn't exist
2020-12-18T10:38:15.296856Z 0 [ERROR] [MY-010735] [Server] Could not open the mysql.plugin table. Please perform the MySQL upgrade procedure.
2020-12-18T10:38:15.308564Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
2020-12-18T10:38:15.469915Z 0 [Warning] [MY-010015] [Repl] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
2020-12-18T10:38:15.795620Z 0 [Warning] [MY-010015] [Repl] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
2020-12-18T10:38:15.846982Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
2020-12-18T10:38:15.847322Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
2020-12-18T10:38:15.853171Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
2020-12-18T10:38:15.853917Z 0 [Warning] [MY-010441] [Server] Failed to open optimizer cost constant tables
2020-12-18T10:38:15.854514Z 0 [ERROR] [MY-013129] [Server] A message intended for a client cannot be sent there as no client-session is attached. Therefore, we're sending the information to the error-log instead: MY-001146 - Table 'mysql.component' doesn't exist
2020-12-18T10:38:15.854856Z 0 [Warning] [MY-013129] [Server] A message intended for a client cannot be sent there as no client-session is attached. Therefore, we're sending the information to the error-log instead: MY-003543 - The mysql.component table is missing or has an incorrect definition.
2020-12-18T10:38:15.855953Z 0 [ERROR] [MY-010326] [Server] Fatal error: Can't open and lock privilege tables: Table 'mysql.user' doesn't exist
2020-12-18T10:38:15.856335Z 0 [ERROR] [MY-010952] [Server] The privilege system failed to initialize correctly. For complete instructions on how to upgrade MySQL to a new version please see the 'Upgrading MySQL' section from the MySQL manual.
2020-12-18T10:38:15.857101Z 0 [ERROR] [MY-010119] [Server] Aborting
2020-12-18T10:38:18.168788Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.22)  MySQL Community Server - GPL.
```

### ml-pipeline-viewer-controller-deployment
```
Name:         ml-pipeline-viewer-controller-deployment-978d7b46c-kpwj4
Namespace:    kubeflow
Priority:     0
Node:         
Start Time:   Fri, 18 Dec 2020 10:15:23 +0000
Labels:       app=ml-pipeline-viewer-crd
              app.kubernetes.io/component=pipelines-viewer
              app.kubernetes.io/name=pipelines-viewer
              pod-template-hash=978d7b46c
Annotations:  sidecar.istio.io/inject: false
Status:       Running
IP:           10.233.109.183
IPs:
  IP:           10.233.109.183
Controlled By:  ReplicaSet/ml-pipeline-viewer-controller-deployment-978d7b46c
Containers:
  ml-pipeline-viewer-controller:
    Container ID:   docker://6677f8b1bf4ba92116c9eacb4339a30ac0e482890e702f58bb507a5f273f9b8b
    Image:          gcr.io/ml-pipeline/viewer-crd-controller:0.2.5
    Image ID:       docker-pullable://gcr.io/ml-pipeline/viewer-crd-controller@sha256:cab368acde5f9d2b19fe21f5fe967ab332cb62bda4e982b15b82ac0e9dc96e93
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Fri, 18 Dec 2020 10:36:43 +0000
      Finished:     Fri, 18 Dec 2020 10:36:43 +0000
    Ready:          False
    Restart Count:  9
    Environment:
      POD_NAMESPACE:  kubeflow (v1:metadata.namespace)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from ml-pipeline-viewer-crd-service-account-token-48kqt (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  ml-pipeline-viewer-crd-service-account-token-48kqt:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ml-pipeline-viewer-crd-service-account-token-48kqt
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  23m                   default-scheduler  Successfully assigned kubeflow/ml-pipeline-viewer-controller-deployment-978d7b46c-kpwj4 to 
  Normal   Pulled     21m (x4 over 22m)     kubelet            Successfully pulled image "gcr.io/ml-pipeline/viewer-crd-controller:0.2.5"
  Normal   Created    21m (x4 over 22m)     kubelet            Created container ml-pipeline-viewer-controller
  Normal   Started    21m (x4 over 22m)     kubelet            Started container ml-pipeline-viewer-controller
  Normal   Pulling    21m (x5 over 22m)     kubelet            Pulling image "gcr.io/ml-pipeline/viewer-crd-controller:0.2.5"
  Warning  BackOff    2m42s (x92 over 22m)  kubelet            Back-off restarting failed container
```

```
kubectl -nkubeflow logs ml-pipeline-viewer-controller-deployment-978d7b46c-kpwj4
W1218 10:36:43.341534       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
runtime: mlock of signal stack failed: 12
runtime: increase the mlock limit (ulimit -l) or
runtime: update your kernel to 5.3.15+, 5.4.2+, or 5.5+
fatal error: mlock failed

runtime stack:
runtime.throw(0x12223db, 0xc)
        /usr/local/go/src/runtime/panic.go:1112 +0x72
runtime.mlockGsignal(0xc000602f00)
        /usr/local/go/src/runtime/os_linux_x86.go:72 +0x107
runtime.mpreinit(0xc000030000)
        /usr/local/go/src/runtime/os_linux.go:341 +0x78
runtime.mcommoninit(0xc000030000)
        /usr/local/go/src/runtime/proc.go:630 +0x108
runtime.allocm(0xc00004e000, 0x12a4658, 0x0)
        /usr/local/go/src/runtime/proc.go:1390 +0x14e
runtime.newm(0x12a4658, 0xc00004e000)
        /usr/local/go/src/runtime/proc.go:1704 +0x39
runtime.startm(0x0, 0xc000494401)
        /usr/local/go/src/runtime/proc.go:1869 +0x12a
runtime.wakep(...)
        /usr/local/go/src/runtime/proc.go:1953
runtime.resetspinning()
        /usr/local/go/src/runtime/proc.go:2415 +0x93
runtime.schedule()
        /usr/local/go/src/runtime/proc.go:2527 +0x2de
runtime.park_m(0xc0002efb00)
        /usr/local/go/src/runtime/proc.go:2690 +0x9d
runtime.mcall(0x20000)
        /usr/local/go/src/runtime/asm_amd64.s:318 +0x5b
```
```
 kubectl get sc
NAME                   PROVISIONER                                       RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
nfs-client (default)   cluster.local/nfs-client-provisioner-1607695020   Delete          Immediate           true                   6d20h
kubectl get pv -A
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                     STORAGECLASS   REASON   AGE
pvc-13b47fcd-7a8a-4a07-8524-393d1ca5e943   20Gi       RWO            Delete           Bound    kubeflow/mysql-pv-claim   nfs-client              53m
pvc-374170ce-2a54-4118-97d9-45f8c5386584   10Gi       RWO            Delete           Bound    kubeflow/katib-mysql      nfs-client              53m
pvc-b40b07d0-00a9-4848-8d0f-d3efd8d13e73   10Gi       RWO            Delete           Bound    kubeflow/metadata-mysql   nfs-client              53m
pvc-f2bd4269-1b4f-48c1-9185-715bcf42e01a   20Gi       RWO            Delete           Bound    kubeflow/minio-pv-claim   nfs-client              53m
kubectl get pvc -A
NAMESPACE   NAME             STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
kubeflow    katib-mysql      Bound    pvc-374170ce-2a54-4118-97d9-45f8c5386584   10Gi       RWO            nfs-client     53m
kubeflow    metadata-mysql   Bound    pvc-b40b07d0-00a9-4848-8d0f-d3efd8d13e73   10Gi       RWO            nfs-client     53m
kubeflow    minio-pv-claim   Bound    pvc-f2bd4269-1b4f-48c1-9185-715bcf42e01a   20Gi       RWO            nfs-client     53m
kubeflow    mysql-pv-claim   Bound    pvc-13b47fcd-7a8a-4a07-8524-393d1ca5e943   20Gi       RWO            nfs-client     53m
```

**Comment by anneum** [comment]
New information: The environment variables are set correctly. 
It seems, that the katib database are not created and the mysql password is not set.
Because of this the Liveness and Readiness is not fulfilled.
```
kubectl -nkubeflow exec -it katib-mysql-858f68f588-k9nm8 -- /bin/bash
root@katib-mysql-858f68f588-k9nm8:/# mysql
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 29
Server version: 8.0.22 MySQL Community Server - GPL

Copyright (c) 2000, 2020, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| sys                |
+--------------------+
4 rows in set (0.00 sec)

mysql> exit
Bye
root@katib-mysql-858f68f588-k9nm8:/# echo $MYSQL_ROOT_PASSWORD
test
root@katib-mysql-858f68f588-k9nm8:/# echo $MYSQL_DATABASE
katib
root@katib-mysql-858f68f588-k9nm8:/# mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
mysqladmin: connect to server at 'localhost' failed
error: 'Access denied for user 'root'@'localhost' (using password: YES)'
root@katib-mysql-858f68f588-k9nm8:/# mysql -D ${MYSQL_DATABASE} -u root -p${MYSQL_ROOT_PASSWORD} -e 'SELECT 1'
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
root@katib-mysql-858f68f588-k9nm8:/# mysql -D ${MYSQL_DATABASE} -u root -e 'SELECT 1'
ERROR 1049 (42000): Unknown database 'katib'
root@katib-mysql-858f68f588-k9nm8:/# mysql -u root -e 'SELECT 1'
+---+
| 1 |
+---+
| 1 |
+---+
```

**Comment by anneum** [comment]
For the ml-pipeline-viewer-controller-deployment the solution is to change the image from **viewer-crd-controller:0.2.5** to **viewer-crd-controller:0.2.4**.
Solution found in [https://github.com/NVIDIA/deepops/issues/771](https://github.com/NVIDIA/deepops/issues/771)

The two katib pods have still problems.

**Comment by DavidSpek** [comment]
@anneum It isn't really a solution, but I have found deleting the  katib-db-manager and  katib-mysql deployments and the katib PVC, then rerunning `kfctl apply -V -f <your_kdef.yaml>` allows them to come up properly.

**Comment by anneum** [comment]
> 
> 
> @anneum It isn't really a solution, but I have found deleting the katib-db-manager and katib-mysql deployments and the katib PVC, then rerunning `kfctl apply -V -f <your_kdef.yaml>` allows them to come up properly.

@DavidSpek Thanks for your help. I have tested it but unfortunately the error still exists.

**Comment by PatrickGhosn** [comment]
What size is your cluster? I found anything less than 8 CPUs  does not run unless you reduce the requested cpu for each service in the yaml files.

**Comment by anneum** [comment]
@PatrickGhosn the cluster have 20 cores distributed over 4 CPUs.
I can't find anything about the requested CPU in the description of the service. 
Can you tell me where I can find these?

**Comment by PatrickGhosn** [comment]
On GKE it should show in the node pool details. 
![image](https://user-images.githubusercontent.com/33845447/104165969-be0b2000-5402-11eb-8006-fc5a51f964d5.png)

Not sure about other platforms.

**Comment by anneum** [comment]
Thank you @PatrickGhosn
In the dashboard I can see that only 15% of the cores are reserved.

**Comment by anneum** [comment]
Solved in https://github.com/kubeflow/katib/issues/1415
