### ISSUE TITLE
Presubmit failure: No such file or directory XXX/.kube/config

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#562]
File "/mnt/test-data-volume/kubeflow-presubmit-tf-serving-image-558-86aca5f-982-d273/src/kubeflow/kubeflow/testing/test_deploy.py", line 80, in create_k8s_client
    util.load_kube_config(persist_config=False)
  File "/mnt/test-data-volume/kubeflow-presubmit-tf-serving-image-558-86aca5f-982-d273/src/kubeflow/testing/py/kubeflow/testing/util.py", line 487, in load_kube_config
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/config/kube_config.py", line 315, in _get_kube_config_loader_for_yaml_file
    with open(filename) as f:
IOError: [Errno 2] No such file or directory: '/mnt/test-data-volume/kubeflow-presubmit-tf-serving-image-558-86aca5f-982-d273/.kube/config'

It failed in #558, which should be unrelated.

This should be related to #523 
cc @jlewi

**Comment by lluunn** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/kubeflow_kubeflow/558/kubeflow-presubmit/993/

Another failure
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/mnt/test-data-volume/kubeflow-presubmit-tf-serving-image-558-86aca5f-993-0247/src/kubeflow/kubeflow/testing/test_deploy.py", line 657, in <module>
    main()
  File "/mnt/test-data-volume/kubeflow-presubmit-tf-serving-image-558-86aca5f-993-0247/src/kubeflow/kubeflow/testing/test_deploy.py", line 647, in main
    wrap_test(args)
  File "/mnt/test-data-volume/kubeflow-presubmit-tf-serving-image-558-86aca5f-993-0247/src/kubeflow/kubeflow/testing/test_deploy.py", line 307, in wrap_test
    test_util.wrap_test(run, test_case)
  File "/mnt/test-data-volume/kubeflow-presubmit-tf-serving-image-558-86aca5f-993-0247/src/kubeflow/testing/py/kubeflow/testing/test_util.py", line 82, in wrap_test
    test_func()
  File "/mnt/test-data-volume/kubeflow-presubmit-tf-serving-image-558-86aca5f-993-0247/src/kubeflow/kubeflow/testing/test_deploy.py", line 305, in run
    args.func(args)
  File "/mnt/test-data-volume/kubeflow-presubmit-tf-serving-image-558-86aca5f-993-0247/src/kubeflow/kubeflow/testing/test_deploy.py", line 248, in deploy_model
    api_client = create_k8s_client(args)
  File "/mnt/test-data-volume/kubeflow-presubmit-tf-serving-image-558-86aca5f-993-0247/src/kubeflow/kubeflow/testing/test_deploy.py", line 80, in create_k8s_client
    util.load_kube_config(persist_config=False)
  File "/mnt/test-data-volume/kubeflow-presubmit-tf-serving-image-558-86aca5f-993-0247/src/kubeflow/testing/py/kubeflow/testing/util.py", line 487, in load_kube_config
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/config/kube_config.py", line 315, in _get_kube_config_loader_for_yaml_file
    with open(filename) as f:
IOError: [Errno 2] No such file or directory: '/mnt/test-data-volume/kubeflow-presubmit-tf-serving-image-558-86aca5f-993-0247/.kube/config'

**Comment by jlewi** [comment]
@lluunn Your workflow needs to run one of the steps that get credentials and create a .kube file

For GKE it should be 
https://github.com/kubeflow/kubeflow/blob/master/testing/test_deploy.py#L547

For minikube it should be deploy minikube.

Those steps should copy the config to ${TEST_DIR}/.kube/config

**Comment by lluunn** [comment]
Thanks Jeremy!
