### ISSUE TITLE
Unable to access kubeflow pipelines via kfp.Client() after 1.3

### ISSUE THREAD

**Issue by nickozilla** [kubeflow/kubeflow#5989]
/kind bug

**What steps did you take and what happened:**
After deploying kubeflow 1.3 to our cluster the kfp.Client() function we had been previously using to upload pipelines and run them has been blocked from succeeding. Now when we call the kfp.Client() using the same params as before, the client fails and is unable to pass the healthz check, always resulting in a 404.

**What did you expect to happen:**
A pipeline file to be uploaded into the environment, and run under a predefined namespace

**Anything else you would like to add:**
Error logs from creating the client:

```
ERROR:root:Failed to get healthz info attempt 1 of 5.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/kfp/_client.py", line 333, in get_kfp_healthz
    response = self._healthz_api.get_healthz()
  File "/usr/local/lib/python3.9/site-packages/kfp_server_api/api/healthz_service_api.py", line 63, in get_healthz
    return self.get_healthz_with_http_info(**kwargs)  # noqa: E501
  File "/usr/local/lib/python3.9/site-packages/kfp_server_api/api/healthz_service_api.py", line 134, in get_healthz_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.9/site-packages/kfp_server_api/api_client.py", line 364, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.9/site-packages/kfp_server_api/api_client.py", line 188, in __call_api
    raise e
  File "/usr/local/lib/python3.9/site-packages/kfp_server_api/api_client.py", line 181, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.9/site-packages/kfp_server_api/api_client.py", line 389, in request
    return self.rest_client.GET(url,
  File "/usr/local/lib/python3.9/site-packages/kfp_server_api/rest.py", line 230, in GET
    return self.request("GET", url,
  File "/usr/local/lib/python3.9/site-packages/kfp_server_api/rest.py", line 224, in request
    raise ApiException(http_resp=r)
kfp_server_api.exceptions.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Content-Length': '134', 'Content-Type': 'text/html; charset=UTF-8', 'Date': 'Thu, 17 Jun 2021 12:43:32 GMT', 'Alt-Svc': 'clear'})
HTTP response body: <!doctype html><meta charset="utf-8"><meta name=viewport content="width=device-width, initial-scale=1"><title>404</title>404 Not Found

ERROR:root:Failed to get healthz info attempt 2 of 5.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/kfp/_client.py", line 333, in get_kfp_healthz
    response = self._healthz_api.get_healthz()
  File "/usr/local/lib/python3.9/site-packages/kfp_server_api/api/healthz_service_api.py", line 63, in get_healthz
    return self.get_healthz_with_http_info(**kwargs)  # noqa: E501
  File "/usr/local/lib/python3.9/site-packages/kfp_server_api/api/healthz_service_api.py", line 134, in get_healthz_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.9/site-packages/kfp_server_api/api_client.py", line 364, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.9/site-packages/kfp_server_api/api_client.py", line 188, in __call_api
    raise e
  File "/usr/local/lib/python3.9/site-packages/kfp_server_api/api_client.py", line 181, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.9/site-packages/kfp_server_api/api_client.py", line 389, in request
    return self.rest_client.GET(url,
  File "/usr/local/lib/python3.9/site-packages/kfp_server_api/rest.py", line 230, in GET
    return self.request("GET", url,
  File "/usr/local/lib/python3.9/site-packages/kfp_server_api/rest.py", line 224, in request
    raise ApiException(http_resp=r)
kfp_server_api.exceptions.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Content-Length': '134', 'Content-Type': 'text/html; charset=UTF-8', 'Date': 'Thu, 17 Jun 2021 12:43:37 GMT', 'Alt-Svc': 'clear'})
HTTP response body: <!doctype html><meta charset="utf-8"><meta name=viewport content="width=device-width, initial-scale=1"><title>404</title>404 Not Found

ERROR:root:Failed to get healthz info attempt 3 of 5.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/kfp/_client.py", line 333, in get_kfp_healthz
    response = self._healthz_api.get_healthz()
  File "/usr/local/lib/python3.9/site-packages/kfp_server_api/api/healthz_service_api.py", line 63, in get_healthz
    return self.get_healthz_with_http_info(**kwargs)  # noqa: E501
  File "/usr/local/lib/python3.9/site-packages/kfp_server_api/api/healthz_service_api.py", line 134, in get_healthz_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.9/site-packages/kfp_server_api/api_client.py", line 364, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.9/site-packages/kfp_server_api/api_client.py", line 188, in __call_api
    raise e
  File "/usr/local/lib/python3.9/site-packages/kfp_server_api/api_client.py", line 181, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.9/site-packages/kfp_server_api/api_client.py", line 389, in request
    return self.rest_client.GET(url,
  File "/usr/local/lib/python3.9/site-packages/kfp_server_api/rest.py", line 230, in GET
    return self.request("GET", url,
  File "/usr/local/lib/python3.9/site-packages/kfp_server_api/rest.py", line 224, in request
    raise ApiException(http_resp=r)
kfp_server_api.exceptions.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Content-Length': '134', 'Content-Type': 'text/html; charset=UTF-8', 'Date': 'Thu, 17 Jun 2021 12:43:43 GMT', 'Alt-Svc': 'clear'})
HTTP response body: <!doctype html><meta charset="utf-8"><meta name=viewport content="width=device-width, initial-scale=1"><title>404</title>404 Not Found

ERROR:root:Failed to get healthz info attempt 4 of 5.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/kfp/_client.py", line 333, in get_kfp_healthz
    response = self._healthz_api.get_healthz()
  File "/usr/local/lib/python3.9/site-packages/kfp_server_api/api/healthz_service_api.py", line 63, in get_healthz
    return self.get_healthz_with_http_info(**kwargs)  # noqa: E501
  File "/usr/local/lib/python3.9/site-packages/kfp_server_api/api/healthz_service_api.py", line 134, in get_healthz_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.9/site-packages/kfp_server_api/api_client.py", line 364, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.9/site-packages/kfp_server_api/api_client.py", line 188, in __call_api
    raise e
  File "/usr/local/lib/python3.9/site-packages/kfp_server_api/api_client.py", line 181, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.9/site-packages/kfp_server_api/api_client.py", line 389, in request
    return self.rest_client.GET(url,
  File "/usr/local/lib/python3.9/site-packages/kfp_server_api/rest.py", line 230, in GET
    return self.request("GET", url,
  File "/usr/local/lib/python3.9/site-packages/kfp_server_api/rest.py", line 224, in request
    raise ApiException(http_resp=r)
kfp_server_api.exceptions.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Content-Length': '134', 'Content-Type': 'text/html; charset=UTF-8', 'Date': 'Thu, 17 Jun 2021 12:43:48 GMT', 'Alt-Svc': 'clear'})
HTTP response body: <!doctype html><meta charset="utf-8"><meta name=viewport content="width=device-width, initial-scale=1"><title>404</title>404 Not Found

ERROR:root:Failed to get healthz info attempt 5 of 5.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/kfp/_client.py", line 333, in get_kfp_healthz
    response = self._healthz_api.get_healthz()
  File "/usr/local/lib/python3.9/site-packages/kfp_server_api/api/healthz_service_api.py", line 63, in get_healthz
    return self.get_healthz_with_http_info(**kwargs)  # noqa: E501
  File "/usr/local/lib/python3.9/site-packages/kfp_server_api/api/healthz_service_api.py", line 134, in get_healthz_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.9/site-packages/kfp_server_api/api_client.py", line 364, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.9/site-packages/kfp_server_api/api_client.py", line 188, in __call_api
    raise e
  File "/usr/local/lib/python3.9/site-packages/kfp_server_api/api_client.py", line 181, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.9/site-packages/kfp_server_api/api_client.py", line 389, in request
    return self.rest_client.GET(url,
  File "/usr/local/lib/python3.9/site-packages/kfp_server_api/rest.py", line 230, in GET
    return self.request("GET", url,
  File "/usr/local/lib/python3.9/site-packages/kfp_server_api/rest.py", line 224, in request
    raise ApiException(http_resp=r)
kfp_server_api.exceptions.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Content-Length': '134', 'Content-Type': 'text/html; charset=UTF-8', 'Date': 'Thu, 17 Jun 2021 12:43:53 GMT', 'Alt-Svc': 'clear'})
HTTP response body: <!doctype html><meta charset="utf-8"><meta name=viewport content="width=device-width, initial-scale=1"><title>404</title>404 Not Found


Traceback (most recent call last):
  File "/home/jenkins/agent/workspace/BI_kubeflow_demo_Nick_fix-upload/scripts/pipeline_build_upload_run.py", line 371, in <module>
    main(cl_args)
  File "/home/jenkins/agent/workspace/BI_kubeflow_demo_Nick_fix-upload/scripts/pipeline_build_upload_run.py", line 356, in main
    client = JenkinsKfpClient(client_options, args.build_dir, args.pipeline_dir, args.tag_value)
  File "/home/jenkins/agent/workspace/BI_kubeflow_demo_Nick_fix-upload/scripts/pipeline_build_upload_run.py", line 51, in __init__
    self._create_client()
  File "/home/jenkins/agent/workspace/BI_kubeflow_demo_Nick_fix-upload/scripts/pipeline_build_upload_run.py", line 83, in _create_client
    self.client = kfp.Client(
  File "/usr/local/lib/python3.9/site-packages/kfp/_client.py", line 158, in __init__
    if not self._context_setting['namespace'] and self.get_kfp_healthz().multi_user is True:
  File "/usr/local/lib/python3.9/site-packages/kfp/_client.py", line 331, in get_kfp_healthz
    raise TimeoutError('Failed getting healthz endpoint after {} attempts.'.format(max_attempts))
TimeoutError: Failed getting healthz endpoint after 5 attempts.
```

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 1.3
- kfctl version: (use `kfctl version`):  
- Kubernetes platform: GKE -  1.19.9-gke.1900
- Kubernetes version: (use `kubectl version`):  ```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.9-gke.1900", GitCommit:"008fd38bf3dc201bebdd4fe26edf9bf87478309a", GitTreeState:"clean", BuildDate:"2021-04-14T09:22:08Z", GoVersion:"go1.15.8b5", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`):

**Comment by nickozilla** [comment]
Nevermind, this is caused by an issue in our project network configuration, closing now

**Comment by TDehaene** [comment]
@nickozilla : we are facing the same issue, what network configuration was giving you troubles?

**Comment by Hongbo-Miao** [comment]
I got a similar error. I posted details at https://stackoverflow.com/questions/76601980/got-errorrootfailed-to-get-healthz-info-attempt-1-of-5-when-deploy-pipeline/76601981#76601981
Hopefully it helps some people save some time! 😃

**Comment by Hongbo-Miao** [comment]
@TDehaene I got a similar error. I posted details at https://stackoverflow.com/questions/76601980/got-errorrootfailed-to-get-healthz-info-attempt-1-of-5-when-deploy-pipeline
Hopefully it helps some people save some time! 😃
