### ISSUE TITLE
Could not start jupyter backend service

### ISSUE THREAD

**Issue by jkl0898** [kubeflow/kubeflow#6405]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I was followed the guide: https://github.com/kubeflow/kubeflow/tree/master/components/crud-web-apps/jupyter
to start the backend service of jupyter-web. as follow:

![image](https://user-images.githubusercontent.com/14175165/159236798-1a276c75-d36e-4e09-b35c-b7d55900e05c.png)

The error occur when running the command : 
```
make -C backend run-dev  
```

Have a advice:
This command should be run at backend/ folder. the guide needs to tell user go to the backend/ folder firstly.

When running the command, the error is:
```
[2022-03-21 17:34:51 +0800] [17421] [INFO] Starting gunicorn 20.1.0
[2022-03-21 17:34:51 +0800] [17421] [INFO] Listening at: http://0.0.0.0:5000 (17421)
[2022-03-21 17:34:51 +0800] [17421] [INFO] Using worker: sync
[2022-03-21 17:34:51 +0800] [17424] [INFO] Booting worker with pid: 17424
[2022-03-21 17:34:51 +0800] [17431] [INFO] Booting worker with pid: 17431
[2022-03-21 17:34:51 +0800] [17439] [INFO] Booting worker with pid: 17439
[2022-03-21 17:34:51 +0800] [17424] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/tmp/kubeflow/components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/apis.py", line 5, in <module>
    config.load_incluster_config()
  File "/tmp/kubeflow/components/crud-web-apps/jupyter/backend/web-apps-dev/lib/python3.7/site-packages/kubernetes/config/incluster_config.py", line 96, in load_incluster_config
    cert_filename=SERVICE_CERT_FILENAME).load_and_set()
  File "/tmp/kubeflow/components/crud-web-apps/jupyter/backend/web-apps-dev/lib/python3.7/site-packages/kubernetes/config/incluster_config.py", line 47, in load_and_set
    self._load_config()
  File "/tmp/kubeflow/components/crud-web-apps/jupyter/backend/web-apps-dev/lib/python3.7/site-packages/kubernetes/config/incluster_config.py", line 53, in _load_config
    raise ConfigException("Service host/port is not set.")
kubernetes.config.config_exception.ConfigException: Service host/port is not set.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/kubeflow/components/crud-web-apps/jupyter/backend/web-apps-dev/lib/python3.7/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/tmp/kubeflow/components/crud-web-apps/jupyter/backend/web-apps-dev/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/tmp/kubeflow/components/crud-web-apps/jupyter/backend/web-apps-dev/lib/python3.7/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/tmp/kubeflow/components/crud-web-apps/jupyter/backend/web-apps-dev/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/tmp/kubeflow/components/crud-web-apps/jupyter/backend/web-apps-dev/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/tmp/kubeflow/components/crud-web-apps/jupyter/backend/web-apps-dev/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/tmp/kubeflow/components/crud-web-apps/jupyter/backend/web-apps-dev/lib/python3.7/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/tmp/miniconda3/envs/python37/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/kubeflow/components/crud-web-apps/jupyter/backend/entrypoint.py", line 4, in <module>
    from apps import default, rok
  File "/tmp/kubeflow/components/crud-web-apps/jupyter/backend/apps/default/__init__.py", line 3, in <module>
    from kubeflow.kubeflow.crud_backend import config, logging
  File "/tmp/kubeflow/components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/__init__.py", line 8, in <module>
    from .errors import bp as errors_bp
  File "/tmp/kubeflow/components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/errors/__init__.py", line 5, in <module>
    from . import handlers  # noqa F401, E402
  File "/tmp/kubeflow/components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/errors/handlers.py", line 7, in <module>
    from .. import api
  File "/tmp/kubeflow/components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/__init__.py", line 1, in <module>
    from .apis import *  # noqa F401, F403
  File "/tmp/kubeflow/components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/apis.py", line 7, in <module>
    config.load_kube_config()
  File "/tmp/kubeflow/components/crud-web-apps/jupyter/backend/web-apps-dev/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 645, in load_kube_config
    persist_config=persist_config)
  File "/tmp/kubeflow/components/crud-web-apps/jupyter/backend/web-apps-dev/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 613, in _get_kube_config_loader_for_yaml_file
    **kwargs)
  File "/tmp/kubeflow/components/crud-web-apps/jupyter/backend/web-apps-dev/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 153, in __init__
    self.set_active_context(active_context)
  File "/tmp/kubeflow/components/crud-web-apps/jupyter/backend/web-apps-dev/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 173, in set_active_context
    context_name = self._config['current-context']
  File "/tmp/kubeflow/components/crud-web-apps/jupyter/backend/web-apps-dev/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 495, in __getitem__
    v = self.safe_get(key)
  File "/tmp/kubeflow/components/crud-web-apps/jupyter/backend/web-apps-dev/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 491, in safe_get
    key in self.value):
TypeError: argument of type 'NoneType' is not iterable
[2022-03-21 17:34:51 +0800] [17424] [INFO] Worker exiting (pid: 17424)
[2022-03-21 17:34:51 +0800] [17431] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/tmp/kubeflow/components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/apis.py", line 5, in <module>
    config.load_incluster_config()
  File "/tmp/kubeflow/components/crud-web-apps/jupyter/backend/web-apps-dev/lib/python3.7/site-packages/kubernetes/config/incluster_config.py", line 96, in load_incluster_config
    cert_filename=SERVICE_CERT_FILENAME).load_and_set()
  File "/tmp/kubeflow/components/crud-web-apps/jupyter/backend/web-apps-dev/lib/python3.7/site-packages/kubernetes/config/incluster_config.py", line 47, in load_and_set
    self._load_config()
  File "/tmp/kubeflow/components/crud-web-apps/jupyter/backend/web-apps-dev/lib/python3.7/site-packages/kubernetes/config/incluster_config.py", line 53, in _load_config
    raise ConfigException("Service host/port is not set.")
kubernetes.config.config_exception.ConfigException: Service host/port is not set.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/kubeflow/components/crud-web-apps/jupyter/backend/web-apps-dev/lib/python3.7/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/tmp/kubeflow/components/crud-web-apps/jupyter/backend/web-apps-dev/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/tmp/kubeflow/components/crud-web-apps/jupyter/backend/web-apps-dev/lib/python3.7/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/tmp/kubeflow/components/crud-web-apps/jupyter/backend/web-apps-dev/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/tmp/kubeflow/components/crud-web-apps/jupyter/backend/web-apps-dev/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/tmp/kubeflow/components/crud-web-apps/jupyter/backend/web-apps-dev/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/tmp/kubeflow/components/crud-web-apps/jupyter/backend/web-apps-dev/lib/python3.7/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/tmp/miniconda3/envs/python37/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/kubeflow/components/crud-web-apps/jupyter/backend/entrypoint.py", line 4, in <module>
    from apps import default, rok
  File "/tmp/kubeflow/components/crud-web-apps/jupyter/backend/apps/default/__init__.py", line 3, in <module>
    from kubeflow.kubeflow.crud_backend import config, logging
  File "/tmp/kubeflow/components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/__init__.py", line 8, in <module>
    from .errors import bp as errors_bp
  File "/tmp/kubeflow/components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/errors/__init__.py", line 5, in <module>
    from . import handlers  # noqa F401, E402
  File "/tmp/kubeflow/components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/errors/handlers.py", line 7, in <module>
    from .. import api
  File "/tmp/kubeflow/components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/__init__.py", line 1, in <module>
    from .apis import *  # noqa F401, F403
  File "/tmp/kubeflow/components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/apis.py", line 7, in <module>
    config.load_kube_config()
  File "/tmp/kubeflow/components/crud-web-apps/jupyter/backend/web-apps-dev/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 645, in load_kube_config
    persist_config=persist_config)
  File "/tmp/kubeflow/components/crud-web-apps/jupyter/backend/web-apps-dev/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 613, in _get_kube_config_loader_for_yaml_file
    **kwargs)
  File "/tmp/kubeflow/components/crud-web-apps/jupyter/backend/web-apps-dev/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 153, in __init__
    self.set_active_context(active_context)
  File "/tmp/kubeflow/components/crud-web-apps/jupyter/backend/web-apps-dev/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 173, in set_active_context
    context_name = self._config['current-context']
  File "/tmp/kubeflow/components/crud-web-apps/jupyter/backend/web-apps-dev/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 495, in __getitem__
    v = self.safe_get(key)
  File "/tmp/kubeflow/components/crud-web-apps/jupyter/backend/web-apps-dev/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 491, in safe_get
    key in self.value):
```

**What did you expect to happen:**

The jupyter-web backend service started normally

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
local vitual machine 

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): v1.4-branch
- kfctl version: (use `kfctl version`): - 
- Kubernetes platform: (e.g. `minikube`): -
- Kubernetes version: (use `kubectl version`): 1.19.x
- OS (e.g. from `/etc/os-release`):

**Comment by yooki0328** [comment]
> 

how to fix it？

**Comment by jkl0898** [comment]
> > 
> 
> how to fix it？

Hi， not solved yet.  and now not work on it. if you have solved it , welcome to share your solutions. Thanks!

**Comment by juliusvonkohout** [comment]
/close

You might want to join the CNCF slack and #kubeflow-notebooks
