### ISSUE TITLE
Kubeflow Pipeline pip Install Error on Ubuntu 20.04

### ISSUE THREAD

**Issue by joesan** [kubeflow/kubeflow#6465]
/kind bug

I was just following the installation documentation to get the Kubeflow Pipeline Python SDK installed on my Ubuntu 20.04 machine

But I ran into the following error:

```
joesan@joesan-InfinityBook-S-14-v5:~/Projects/Private/ml-projects/housing-price-prediction-kfp$ pip install kfp --upgrade --user
Collecting kfp
  Using cached kfp-1.8.12.tar.gz (301 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [44 lines of output]
      running egg_info
      creating /tmp/pip-pip-egg-info-llb4v9nb/kfp.egg-info
      writing /tmp/pip-pip-egg-info-llb4v9nb/kfp.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-pip-egg-info-llb4v9nb/kfp.egg-info/dependency_links.txt
      writing entry points to /tmp/pip-pip-egg-info-llb4v9nb/kfp.egg-info/entry_points.txt
      writing requirements to /tmp/pip-pip-egg-info-llb4v9nb/kfp.egg-info/requires.txt
      writing top-level names to /tmp/pip-pip-egg-info-llb4v9nb/kfp.egg-info/top_level.txt
      writing manifest file '/tmp/pip-pip-egg-info-llb4v9nb/kfp.egg-info/SOURCES.txt'
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-bq6gjht_/kfp_42c911a696de4f64b51167638b3ce902/setup.py", line 154, in <module>
          'kfp=kfp.__main__:main'
        File "/home/joesan/.pyenv/versions/3.7.8/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/joesan/.pyenv/versions/3.7.8/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "/home/joesan/.pyenv/versions/3.7.8/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/home/joesan/.pyenv/versions/3.7.8/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/home/joesan/.pyenv/versions/3.7.8/lib/python3.7/site-packages/setuptools/dist.py", line 1214, in run_command
          super().run_command(command)
        File "/home/joesan/.pyenv/versions/3.7.8/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/home/joesan/.pyenv/versions/3.7.8/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 308, in run
          self.find_sources()
        File "/home/joesan/.pyenv/versions/3.7.8/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 315, in find_sources
          mm.run()
        File "/home/joesan/.pyenv/versions/3.7.8/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 550, in run
          self.add_defaults()
        File "/home/joesan/.pyenv/versions/3.7.8/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 590, in add_defaults
          rcfiles = list(walk_revctrl())
        File "/home/joesan/.pyenv/versions/3.7.8/lib/python3.7/site-packages/setuptools/command/sdist.py", line 18, in walk_revctrl
          for item in ep.load()(dirname):
        File "/home/joesan/.pyenv/versions/3.7.8/lib/python3.7/site-packages/setuptools_scm/integration.py", line 70, in find_files
          command = ep.load()
        File "/home/joesan/.pyenv/versions/3.7.8/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2470, in load
          self.require(*args, **kwargs)
        File "/home/joesan/.pyenv/versions/3.7.8/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2493, in require
          items = working_set.resolve(reqs, env, installer, extras=self.extras)
        File "/home/joesan/.pyenv/versions/3.7.8/lib/python3.7/site-packages/pkg_resources/__init__.py", line 800, in resolve
          raise VersionConflict(dist, req).with_context(dependent_req)
      pkg_resources.ContextualVersionConflict: (pyparsing 3.0.6 (/home/joesan/.pyenv/versions/3.7.8/lib/python3.7/site-packages), Requirement.parse('pyparsing<3,>=2.0.2'), {'packaging'})
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
joesan@joesan-InfinityBook-S-14-v5:~/Projects/Private/ml-projects/housing-price-prediction-kfp$ which python
/home/joesan/.pyenv/shims/python
joesan@joesan-InfinityBook-S-14-v5:~/Projects/Private/ml-projects/housing-price-prediction-kfp$ which pyenv
/opt/softwares/pyenv/bin/pyenv
joesan@joesan-InfinityBook-S-14-v5:~/Projects/Private/ml-projects/housing-price-prediction-kfp$ 
```

**Comment by pythonking6** [comment]
what is going on with this?

**Comment by juliusvonkohout** [comment]
/close

There has been no activity for a long time. Please reopen if necessary.
