### ISSUE TITLE
Can't build vscode-notebook due to ms-python package

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/kubeflow#6553]
The GH job for building all images failed because vscode image could not be build https://github.com/kubeflow/kubeflow/runs/7135471829?check_suite_focus=true

```bash
Installing extensions...
Server returned 404
[2022-06-30T16:35:29.222Z] error vscode Failed Installing Extensions: ms-python.python
[2022-06-30T16:35:29.224Z] error vscode Error: Failed Installing Extensions: ms-python.python
    at O.installExtensions (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:19:42)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /usr/lib/code-server/lib/vscode/out/vs/server/entry.js:36:90861
    at async M (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:36:94206)
    at async process.<anonymous> (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:36:103823)
The command '/bin/bash -c code-server --install-extension "ms-python.python@${CODESERVER_PYTHON_VERSION}"' returned a non-zero code: 1
```

This is a blocker for the release https://github.com/kubeflow/manifests/issues/2199 cc @annajung 

/assign @thesuperzapper

**Comment by annajung** [comment]
I couldn't find the core problem to why the version is missing, but I found a possible workaround based on https://github.com/coder/code-server/issues/2626#issuecomment-799368771

```
RUN curl -# -L -o /tmp/ms-python-release.vsix "https://github.com/microsoft/vscode-python/releases/download/${CODESERVER_PYTHON_VERSION}/ms-python-release.vsix"
RUN code-server --install-extension /tmp/ms-python-release.vsix

# Not necessary -- used to test the version
RUN code-server --list-extensions --show-versions
```

I did test it locally and was able to build it successfully

**Comment by kimwnasptd** [comment]
@annajung that looks like the way to go! Nice!

Can you submit a PR for this? I can review. We can use `master` and I'll cherry pick to the release branch as well
