### ISSUE TITLE
I can not create notebook server in kubeflow1.5 on GKE k8s v1.23.5-gke.2400

### ISSUE THREAD

**Issue by bankentan** [kubeflow/kubeflow#6566]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I can not create notebook server in kubeflow1.5 on GKE k8s  v1.23.5-gke.2400

I use kubeflow/manifests v1.5-branch to deploy kubeflow, when I deploy notebook-controller encountered below issue
```
[root@test manifests]# /root/kustomize/kustomize build apps/jupyter/notebook-controller/upstream/overlays/kubeflow | kubectl apply -f -
serviceaccount/notebook-controller-service-account unchanged
role.rbac.authorization.k8s.io/notebook-controller-leader-election-role unchanged
clusterrole.rbac.authorization.k8s.io/notebook-controller-kubeflow-notebooks-admin configured
clusterrole.rbac.authorization.k8s.io/notebook-controller-kubeflow-notebooks-edit unchanged
clusterrole.rbac.authorization.k8s.io/notebook-controller-kubeflow-notebooks-view unchanged
clusterrole.rbac.authorization.k8s.io/notebook-controller-role configured
rolebinding.rbac.authorization.k8s.io/notebook-controller-leader-election-rolebinding unchanged
clusterrolebinding.rbac.authorization.k8s.io/notebook-controller-role-binding unchanged
configmap/notebook-controller-config-m44cmb547t unchanged
service/notebook-controller-service unchanged
deployment.apps/notebook-controller-deployment unchanged
error: resource mapping not found for name: "notebooks.kubeflow.org" namespace: "" from "STDIN": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
```

After I change notebook CustomResourceDefinition apiextensions.k8s.io version from v1beta1 to v1, notebook-controller can success to deploy.
But I can not create notebook in kubeflow UI , below logs is from jupyter-web-app
```
2022-07-10 10:04:01,462 | kubeflow.kubeflow.crud_backend.authn | INFO | Handling request for user: user@example.com
2022-07-10 10:04:01,469 | kubeflow.kubeflow.crud_backend.csrf | INFO | Skipping CSRF check for safe method: GET
2022-07-10 10:04:01,480 | kubeflow.kubeflow.crud_backend.errors.handlers | ERROR | Caught and unhandled Exception!
2022-07-10 10:04:01,481 | kubeflow.kubeflow.crud_backend.errors.handlers | ERROR | 'spec'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/src/apps/common/routes/get.py", line 47, in get_notebooks
    contents = [utils.notebook_dict_from_k8s_obj(nb) for nb in notebooks]
  File "/src/apps/common/routes/get.py", line 47, in <listcomp>
    contents = [utils.notebook_dict_from_k8s_obj(nb) for nb in notebooks]
  File "/src/apps/common/utils.py", line 117, in notebook_dict_from_k8s_obj
    cntr = notebook["spec"]["template"]["spec"]["containers"][0]
KeyError: 'spec'
10.216.4.29 - - [10/Jul/2022:10:04:01 +0000] "GET /api/namespaces/kubeflow-user-example-com/notebooks HTTP/1.1" 500 118 "https://34.142.109.216:30650/jupyter/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"
```

I try to use this yaml file to create notebook by manually
```
apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  generation: 1
  labels:
    app: yongjiakentan
  name: yongjiakentan
  namespace: kubeflow-user-example-com
spec:
  template:
    spec:
      containers:
      - env: []
        image: kubeflownotebookswg/jupyter-tensorflow-full:master-6e4ad3b4
        name: yongjiakentan
        resources:
          requests:
            cpu: "0.5"
            memory: 1.0Gi
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
      serviceAccountName: default-editor
      ttlSecondsAfterFinished: 300
      volumes:
      - emptyDir:
          medium: Memory
        name: dshm
```

The spec field is empty
```
apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kubeflow.org/v1","kind":"Notebook","metadata":{"annotations":{},"generation":1,"labels":{"app":"yongjiakentan"},"name":"yongjiakentan","namespace":"kubeflow-user-example-com"},"spec":{"template":{"spec":{"containers":[{"env":[],"image":"kubeflownotebookswg/jupyter-tensorflow-full:master-6e4ad3b4","name":"yongjiakentan","resources":{"requests":{"cpu":"0.5","memory":"1.0Gi"}},"volumeMounts":[{"mountPath":"/dev/shm","name":"dshm"}]}],"serviceAccountName":"default-editor","ttlSecondsAfterFinished":300,"volumes":[{"emptyDir":{"medium":"Memory"},"name":"dshm"}]}}}}
  creationTimestamp: "2022-07-10T10:08:16Z"
  generation: 1
  labels:
    app: yongjiakentan
  name: yongjiakentan
  namespace: kubeflow-user-example-com
  resourceVersion: "12068236"
  uid: 7bd3bdde-a855-434e-b513-2aabbf870201
spec:
  template:
    spec: {}
```

**What did you expect to happen:**
I want to deploy kubeflow1.5 version to GKE k8s 1.23.5 version, and use notebook service in kubeflow UI

**Environment:**
- Kubeflow version v1.5
- GKE version v1.23.5-gke.2400
- kustomize  v3.8.5

**Comment by juliusvonkohout** [comment]
/close

There has been no activity for a long time. Please reopen if necessary.
