### ISSUE TITLE
Segfault in bootstrapper while processing .kube

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#657]
```
 /opt/kubeflow/bootstraper --app-dir=/home/jlewi/kf-apps/test-app0413
{"filename":"app/server.go:106","level":"info","msg":"Reading config from file: /home/jlewi/.kube/config","time":"2018-04-13T20:32:04Z"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xfbf5bc]

goroutine 1 [running]:
github.com/kubeflow/kubeflow/bootstrap/cmd/bootstrap/app.modifyGcloudCommand(0xc420559910, 0x0, 0x0)
	/home/jlewi/go/src/github.com/kubeflow/kubeflow/bootstrap/cmd/bootstrap/app/server.go:68 +0xbc
github.com/kubeflow/kubeflow/bootstrap/cmd/bootstrap/app.getClusterConfig(0xc4201b37a0, 0x0, 0x4, 0xc42044a5b0, 0x2)
	/home/jlewi/go/src/github.com/kubeflow/kubeflow/bootstrap/cmd/bootstrap/app/server.go:119 +0x291
github.com/kubeflow/kubeflow/bootstrap/cmd/bootstrap/app.Run(0xc42029d950, 0xc4202a51a0, 0x13aa9c0)
	/home/jlewi/go/src/github.com/kubeflow/kubeflow/bootstrap/cmd/bootstrap/app/server.go:193 +0x4b
main.main()
	/home/jlewi/go/src/github.com/kubeflow/kubeflow/bootstrap/cmd/bootstrap/main.go:45 +0x6b

```

/assign @kunmingg

**Comment by kunmingg** [comment]
@jlewi cannot recreate from my side, any special formatting for ```/home/jlewi/.kube/config```?

**Comment by ankushagarwal** [comment]
I am facing the same issue as well

**Comment by kunmingg** [comment]
@ankushagarwal Can you add your error message? and which branch are you using?
Thanks!

**Comment by kunmingg** [comment]
Got it, thanks! Lucky i don't have minikube locally.
