### ISSUE TITLE
Executor pods terminate while using spark in client mode

### ISSUE THREAD

**Issue by satish-dops94** [kubeflow/kubeflow#6645]
### While creating a spark session in client mode from the kubeflow notebook my driver pods get created but executor pods keep on getting created and terminated within a fraction of a second. 

**Logs**:

```
+ CMD=(${JAVA_HOME}/bin/java "${SPARK_EXECUTOR_JAVA_OPTS[@]}" -Xms$SPARK_EXECUTOR_MEMORY -Xmx$SPARK_EXECUTOR_MEMORY -cp "$SPARK_CLASSPATH:$SPARK_DIST_CLASSPATH" org.apache.spark.executor.CoarseGrainedExecutorBackend --driver-url $SPARK_DRIVER_URL --executor-id $SPARK_EXECUTOR_ID --cores $SPARK_EXECUTOR_CORES --app-id $SPARK_APPLICATION_ID --hostname $SPARK_EXECUTOR_POD_IP --resourceProfileId $SPARK_RESOURCE_PROFILE_ID)
+ exec /usr/bin/tini -s -- /usr/local/openjdk-11/bin/java -Dspark.driver.blockManager.port=7079 -Dspark.driver.port=7078 -Xms1024m -Xmx1024m -cp '/opt/spark/conf::/opt/spark/jars/*:' org.apache.spark.executor.CoarseGrainedExecutorBackend --driver-url spark://CoarseGrainedScheduler@spark-pi-pa-1652986745596-driver-svc.v1-satish.svc:7078 --executor-id 6 --cores 1 --app-id spark-12e93c7823ba4ecd86ff0872158ba422 --hostname 192.168.41.241 --resourceProfileId 0
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
22/05/19 19:00:05 INFO CoarseGrainedExecutorBackend: Started daemon with process name: 16@spark-pi-pa-1652986745596-exec-6
22/05/19 19:00:05 INFO SignalUtils: Registering signal handler for TERM
22/05/19 19:00:05 INFO SignalUtils: Registering signal handler for HUP
22/05/19 19:00:05 INFO SignalUtils: Registering signal handler for INT
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/opt/spark/jars/spark-unsafe_2.12-3.1.1.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
22/05/19 19:00:05 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
22/05/19 19:00:05 INFO SecurityManager: Changing view acls to: 185
22/05/19 19:00:05 INFO SecurityManager: Changing modify acls to: 185
22/05/19 19:00:05 INFO SecurityManager: Changing view acls groups to:
22/05/19 19:00:05 INFO SecurityManager: Changing modify acls groups to:
22/05/19 19:00:05 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(185); groups with view permissions: Set(); users  with modify permissions: Set(185); groups with modify permissions: Set()
Exception in thread "main" java.lang.reflect.UndeclaredThrowableException
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1761)
	at org.apache.spark.deploy.SparkHadoopUtil.runAsSparkUser(SparkHadoopUtil.scala:61)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$.run(CoarseGrainedExecutorBackend.scala:393)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$.main(CoarseGrainedExecutorBackend.scala:382)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend.main(CoarseGrainedExecutorBackend.scala)
Caused by: org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$.$anonfun$run$9(CoarseGrainedExecutorBackend.scala:413)
	at scala.runtime.java8.JFunction1$mcVI$sp.apply(JFunction1$mcVI$sp.java:23)
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:877)
	at scala.collection.immutable.Range.foreach(Range.scala:158)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:876)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$.$anonfun$run$7(CoarseGrainedExecutorBackend.scala:411)
	at org.apache.spark.deploy.SparkHadoopUtil$$anon$1.run(SparkHadoopUtil.scala:62)
	at org.apache.spark.deploy.SparkHadoopUtil$$anon$1.run(SparkHadoopUtil.scala:61)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.security.auth.Subject.doAs(Unknown Source)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1746)
	... 4 more
Caused by: java.io.IOException: Failed to connect to spark-pi-pa-1652986745596-driver-svc.v1-satish.svc/192.168.41.63:7078
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:287)
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
	at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
	at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
	at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: spark-pi-pa-1652986745596-driver-svc.v1-satish.svc/192.168.41.63:7078
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**spark config file**:
```
def create_sparksession(notebook_namespace="v1-satish",
                        driver_port=None,
                        app_name="pyspark-app",
                        num_exec=1,
                        exec_image="<exec image>",
                        pods_namespace="v1-satish",
                        ui_port=None,
                        driver_pod_sa="spark",
                        exec_memory="1g",
                        exec_cores=1,
                        iam_role="<role arn>"):
    """
    pods_namespace: The namespace that will be used for running the driver and executor pods.
    my_namespace: Need to provide the namespace you are in.
    driver_pod_sa: Service account that is used when running the driver pod.
    The driver pod uses this service account when requesting executor pods from the API server.
    """
    if driver_port == None:
        driver_port = np.random.randint(29000, 30000)
    if ui_port == None:
        ui_port = np.random.randint(4000, 5000)

    # set default python3 in driver and exec pods
    os.environ["PYSPARK_PYTHON"] = "python3"
    os.environ["PYSPARK_DRIVER_PYTHON"] = "python3"

    # creating spark config
    pod_hostname = os.environ.get("HOSTNAME")
    driver_host = socket.gethostbyname(pod_hostname)

    sparkSession = SparkSession.builder \
        .master("k8s://https://kubernetes.default.svc.cluster.local:443") \
        .config("spark.app.name", app_name) \
        .config("spark.submit.deployMode", "client") \
        .config("spark.executor.heartbeatInterval", 1000) \
        .config("spark.network.timeout", 50000) \
        .config("spark.kubernetes.authenticate.driver.serviceAccountName", driver_pod_sa) \
        .config("spark.kubernetes.authenticate.executor.serviceAccountName", driver_pod_sa) \
        .config("spark.kubernetes.namespace", pods_namespace) \
        .config("spark.driver.pod.name", pod_hostname) \
        .config("spark.kubernetes.allocation.driver.readinessTimeout", 20) \
        .config("spark.executor.instances", str(num_exec)) \
        .config("spark.kubernetes.container.image", exec_image) \
        .config("spark.driver.host", driver_host) \
        .config("spark.driver.port", driver_port) \
        .config("spark.kubernetes.executor.annotation.iam.amazonaws.com/role", iam_role) \
        .config("spark.kubernetes.driver.annotation.iam.amazonaws.com/role", iam_role) \
        .config("spark.executor.extraJavaOptions", "-Dcom.amazonaws.services.s3.enableV4=true") \
        .config("spark.driver.extraJavaOptions", "-Dcom.amazonaws.services.s3.enableV4=true") \
        .config("spark.kubernetes.executor.annotation.sidecar.istio.io/inject", "false") \
        .config("spark.kubernetes.driver.annotation.sidecar.istio.io/inject", "false") \
        .config("spark.kubernetes.executor.annotation.traffic.sidecar.istio.io/excludeOutboundPorts", "7078,7079") \
        .config("spark.kubernetes.driver.annotation.traffic.sidecar.istio.io/excludeInboundPorts", "7078,7079") \
        .config("spark.executor.memory", exec_memory) \
        .config("spark.executor.cores", exec_cores) \
        .config("spark.ui.port", ui_port) \
        .config("spark.kubernetes.dynamicAllocation.deleteGracePeriod", 20) \
        .config("spark.kubernetes.container.image.pullPolicy", "Always") \
        .config("spark.kubernetes.driver.podTemplateFile", "/home/jovyan/driver.yaml") \
        .config("spark.kubernetes.executor.podTemplateFile", "/home/jovyan/driver.yaml") \
        .getOrCreate()
    sc = sparkSession.sparkContext
    hadoopConf = sc._jsc.hadoopConfiguration()
    hadoopConf.set("fs.s3a.impl", "org.apache.hadoop.fs.s3a.S3AFileSystem")
    hadoopConf.set("com.amazonaws.services.s3.enableV4", "true")
    hadoopConf.set("fs.s3a.endpoint", "s3.ap-south-1.amazonaws.com")
    hadoopConf.set("fs.s3a.aws.credentials.provider", "com.amazonaws.auth.WebIdentityTokenCredentialsProvider")
    hadoopConf.set("fs.s3a.aws.credentials.provider.role.arn", "<role arn>")
    return sparkSession
```

Note: I am using the spark operator also in the cluster and am able to run a spark application in cluster mode.

**Comment by satish-dops94** [comment]
Any suggestions?

**Comment by juliusvonkohout** [comment]
/close

There has been no activity for a long time. Please reopen if necessary.
Please also consult the Kubeflow slack channel for support questions.
