### ISSUE TITLE
Kubeflow visualization issue 

### ISSUE THREAD

**Issue by sidnaik1975** [kubeflow/kubeflow#6840]
Kubeflow cannot render the visualizations by reading artifact from minio .  getting below error in ui server pod 

Getting storage artifact at: minio: mlpipeline/artifacts/nlu-v2-common-pipeline-ltt5k/2022/12/09/nlu-v2-common-pipeline-ltt5k-3366828351/concat-all_preds.tgz
GET /pipeline/artifacts/get?source=minio&peek=256&bucket=mlpipeline&key=artifacts%2Fnlu-v2-common-pipeline-ltt5k%2F2022%2F12%2F09%2Fnlu-v2-common-pipeline-ltt5k-1285719387%2Fmain.log
Getting storage artifact at: minio: mlpipeline/artifacts/nlu-v2-common-pipeline-ltt5k/2022/12/09/nlu-v2-common-pipeline-ltt5k-1285719387/main.log
GET /pipeline/artifacts/get?source=minio&peek=256&bucket=mlpipeline&key=artifacts%2Fnlu-v2-common-pipeline-ltt5k%2F2022%2F12%2F09%2Fnlu-v2-common-pipeline-ltt5k-1285719387%2Fmlpipeline-ui-metadata.tgz
Getting storage artifact at: minio: mlpipeline/artifacts/nlu-v2-common-pipeline-ltt5k/2022/12/09/nlu-v2-common-pipeline-ltt5k-1285719387/mlpipeline-ui-metadata.tgz
S3Error: 503
    at getError (/server/node_modules/minio/dist/main/transformers.js:138:15)
    at /server/node_modules/minio/dist/main/transformers.js:158:14
    at DestroyableTransform._flush (/server/node_modules/minio/dist/main/transformers.js:80:10)
    at DestroyableTransform.prefinish (/server/node_modules/readable-stream/lib/_stream_transform.js:138:10)
    at DestroyableTransform.emit (events.js:400:28)
    at prefinish (/server/node_modules/readable-stream/lib/_stream_writable.js:619:14)
    at finishMaybe (/server/node_modules/readable-stream/lib/_stream_writable.js:627:5)
    at endWritable (/server/node_modules/readable-stream/lib/_stream_writable.js:638:3)
    at DestroyableTransform.Writable.end (/server/node_modules/readable-stream/lib/_stream_writable.js:594:41)
    at IncomingMessage.onend (internal/streams/readable.js:670:10) {
  code: 'UnknownError',
  amzRequestid: null,
  amzId2: null,
  amzBucketRegion: null
}

**Comment by kimwnasptd** [comment]
Hey @sidnaik1975, could you open this issue in the kubeflow/pipelines repo?

**Comment by juliusvonkohout** [comment]
/close

There has been no activity for a long time. Please reopen if necessary.
Please also consult the Kubeflow slack channel for support questions.
