### ISSUE TITLE
Making authenticated get_run request from within a kubeflow component

### ISSUE THREAD

**Issue by SebastianScherer88** [kubeflow/kubeflow#6879]
/kind question

**Question:**
I'm trying to programmatically access the output of another pipeline's run. For example, say pipeline A has just finished running. My pipeline - pipeline B - needs to access the S3 location of some of pipeline A's run's outputs.

My plan was to write some custom code to make a request via the `kfp.Client`'s `get_run` method from inside the first component of pipeline B, parsing the returned run meta data and extract the S3 location paths:

```
run_meta_data = client.get_run(run_id=run_id)

text_data_s3 = get_component_output_from_run_meta_data(run_meta_data,
                                                    node_name='load-text-data',
                                                    output_name='text-data-csv')
```
 My custom parsing logic works fine, however making the request from outside a pipeline and inside a pipeline gives different results - see below.

Problem: The `get_run` method fails when being run inside the component of pipeline B. The logs indicate that the request is not authenticated to extract run meta data:

```
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: 
https://pip.pypa.io/warnings/venv
Creating client
ERROR:root:Failed to read a token from file '/var/run/secrets/kubeflow/pipelines/token' ([Errno 2] No such file or directory: '/var/run/secrets/kubeflow/pipelines/token').
WARNING:root:Failed to set up default credentials. Proceeding without credentials...
Created: {client}
Result pipeline: {'created_at': datetime.datetime(2022, 12, 15, 18, 48, 28, tzinfo=tzlocal()),
 'default_version': {'code_source_url': None,
                     'created_at': datetime.datetime(2022, 12, 15, 18, 48, 28, tzinfo=tzlocal()),
                     'description': None,
                     'id': '0bb67112-38b9-46c2-8f9d-5669ee92e391',
                     'name': 'download_preprocess_split_pipeline',
                     'package_url': None,
                     'parameters': [{'name': 'dataset',
                                     'value': 'vodafone_dataset:latest'}],
                     'resource_references': [{'key': {'id': '0bb67112-38b9-46c2-8f9d-5669ee92e391',
                                                      'type': 'PIPELINE'},
                                              'name': None,
                                              'relationship': 'OWNER'}]},
 'description': None,
 'error': None,
 'id': '0bb67112-38b9-46c2-8f9d-5669ee92e391',
 'name': 'download_preprocess_split_pipeline',
 'parameters': [{'name': 'dataset', 'value': 'vodafone_dataset:latest'}],
 'resource_references': None,
 'url': None}
Traceback (most recent call last):
  File "/tmp/tmp.rFEwlldpAv", line 23, in <module>
    _outputs = get_run_metadata(**_parsed_args)
  File "/tmp/tmp.rFEwlldpAv", line 15, in get_run_metadata
    test_run = client.get_run(run_id='2697ed7e-31be-4770-b024-1ef24af4b113')
  File "/usr/local/lib/python3.7/site-packages/kfp/_client.py", line 1232, in get_run
    return self._run_api.get_run(run_id=run_id)
  File "/usr/local/lib/python3.7/site-packages/kfp_server_api/api/run_service_api.py", line 435, in get_run
    return self.get_run_with_http_info(run_id, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.7/site-packages/kfp_server_api/api/run_service_api.py", line 529, in get_run_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.7/site-packages/kfp_server_api/api_client.py", line 369, in call_api
    _preload_content, _request_timeout, _host)
  File "/usr/local/lib/python3.7/site-packages/kfp_server_api/api_client.py", line 188, in __call_api
    raise e
  File "/usr/local/lib/python3.7/site-packages/kfp_server_api/api_client.py", line 185, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.7/site-packages/kfp_server_api/api_client.py", line 393, in request
    headers=headers)
  File "/usr/local/lib/python3.7/site-packages/kfp_server_api/rest.py", line 234, in GET
    query_params=query_params)
  File "/usr/local/lib/python3.7/site-packages/kfp_server_api/rest.py", line 224, in request
    raise ApiException(http_resp=r)
kfp_server_api.exceptions.ApiException: (500)
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'content-type': 'application/json', 'date': 'Fri, 06 Jan 2023 21:46:13 GMT', 'x-envoy-upstream-service-time': '7', 'server': 'istio-envoy', 'x-envoy-decorator-operation': 'ml-pipeline.kubeflow.svc.cluster.local:8888/*', 'transfer-encoding': 'chunked'})
HTTP response body: {"error":"Internal error: Unauthenticated: Request header error: there is no user identity header.: Request header error: there is no user identity header.\nFailed to authorize with API resource references\ngithub.com/kubeflow/pipelines/backend/src/common/util.Wrap\n\t/go/src/github.com/kubeflow/pipelines/backend/src/common/util/error.go:279\ngithub.com/kubeflow/pipelines/backend/src/apiserver/server.(*RunServer).canAccessRun\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/server/run_server.go:390\ngithub.com/kubeflow/pipelines/backend/src/apiserver/server.(*RunServer).GetRun\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/server/run_server.go:151\ngithub.com/kubeflow/pipelines/backend/api/go_client._RunService_GetRun_Handler.func1\n\t/go/src/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:2180\nmain.apiServerInterceptor\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/interceptor.go:30\ngithub.com/kubeflow/pipelines/backend/api/go_client._RunService_GetRun_Handler\n\t/go/src/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:2182\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1286\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1609\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:934\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357\nFailed to authorize the request\ngithub.com/kubeflow/pipelines/backend/src/common/util.Wrap\n\t/go/src/github.com/kubeflow/pipelines/backend/src/common/util/error.go:279\ngithub.com/kubeflow/pipelines/backend/src/apiserver/server.(*RunServer).GetRun\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/server/run_server.go:153\ngithub.com/kubeflow/pipelines/backend/api/go_client._RunService_GetRun_Handler.func1\n\t/go/src/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:2180\nmain.apiServerInterceptor\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/interceptor.go:30\ngithub.com/kubeflow/pipelines/backend/api/go_client._RunService_GetRun_Handler\n\t/go/src/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:2182\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1286\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1609\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:934\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357","code":13,"message":"Internal error: Unauthenticated: Request header error: there is no user identity header.: Request header error: there is no user identity header.\nFailed to authorize with API resource references\ngithub.com/kubeflow/pipelines/backend/src/common/util.Wrap\n\t/go/src/github.com/kubeflow/pipelines/backend/src/common/util/error.go:279\ngithub.com/kubeflow/pipelines/backend/src/apiserver/server.(*RunServer).canAccessRun\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/server/run_server.go:390\ngithub.com/kubeflow/pipelines/backend/src/apiserver/server.(*RunServer).GetRun\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/server/run_server.go:151\ngithub.com/kubeflow/pipelines/backend/api/go_client._RunService_GetRun_Handler.func1\n\t/go/src/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:2180\nmain.apiServerInterceptor\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/interceptor.go:30\ngithub.com/kubeflow/pipelines/backend/api/go_client._RunService_GetRun_Handler\n\t/go/src/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:2182\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1286\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1609\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:934\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357\nFailed to authorize the request\ngithub.com/kubeflow/pipelines/backend/src/common/util.Wrap\n\t/go/src/github.com/kubeflow/pipelines/backend/src/common/util/error.go:279\ngithub.com/kubeflow/pipelines/backend/src/apiserver/server.(*RunServer).GetRun\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/server/run_server.go:153\ngithub.com/kubeflow/pipelines/backend/api/go_client._RunService_GetRun_Handler.func1\n\t/go/src/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:2180\nmain.apiServerInterceptor\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/interceptor.go:30\ngithub.com/kubeflow/pipelines/backend/api/go_client._RunService_GetRun_Handler\n\t/go/src/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:2182\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1286\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1609\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:934\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357","details":[{"@type":"type.googleapis.com/api.Error","error_message":"Internal error: Unauthenticated: Request header error: there is no user identity header.: Request header error: there is no user identity header.\nFailed to authorize with API resource references\ngithub.com/kubeflow/pipelines/backend/src/common/util.Wrap\n\t/go/src/github.com/kubeflow/pipelines/backend/src/common/util/error.go:279\ngithub.com/kubeflow/pipelines/backend/src/apiserver/server.(*RunServer).canAccessRun\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/server/run_server.go:390\ngithub.com/kubeflow/pipelines/backend/src/apiserver/server.(*RunServer).GetRun\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/server/run_server.go:151\ngithub.com/kubeflow/pipelines/backend/api/go_client._RunService_GetRun_Handler.func1\n\t/go/src/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:2180\nmain.apiServerInterceptor\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/interceptor.go:30\ngithub.com/kubeflow/pipelines/backend/api/go_client._RunService_GetRun_Handler\n\t/go/src/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:2182\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1286\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1609\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:934\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357\nFailed to authorize the request\ngithub.com/kubeflow/pipelines/backend/src/common/util.Wrap\n\t/go/src/github.com/kubeflow/pipelines/backend/src/common/util/error.go:279\ngithub.com/kubeflow/pipelines/backend/src/apiserver/server.(*RunServer).GetRun\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/server/run_server.go:153\ngithub.com/kubeflow/pipelines/backend/api/go_client._RunService_GetRun_Handler.func1\n\t/go/src/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:2180\nmain.apiServerInterceptor\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/interceptor.go:30\ngithub.com/kubeflow/pipelines/backend/api/go_client._RunService_GetRun_Handler\n\t/go/src/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:2182\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1286\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1609\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:934\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357","error_details":"Internal error: Unauthenticated: Request header error: there is no user identity header.: Request header error: there is no user identity header.\nFailed to authorize with API resource references\ngithub.com/kubeflow/pipelines/backend/src/common/util.Wrap\n\t/go/src/github.com/kubeflow/pipelines/backend/src/common/util/error.go:279\ngithub.com/kubeflow/pipelines/backend/src/apiserver/server.(*RunServer).canAccessRun\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/server/run_server.go:390\ngithub.com/kubeflow/pipelines/backend/src/apiserver/server.(*RunServer).GetRun\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/server/run_server.go:151\ngithub.com/kubeflow/pipelines/backend/api/go_client._RunService_GetRun_Handler.func1\n\t/go/src/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:2180\nmain.apiServerInterceptor\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/interceptor.go:30\ngithub.com/kubeflow/pipelines/backend/api/go_client._RunService_GetRun_Handler\n\t/go/src/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:2182\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1286\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1609\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:934\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357\nFailed to authorize the request\ngithub.com/kubeflow/pipelines/backend/src/common/util.Wrap\n\t/go/src/github.com/kubeflow/pipelines/backend/src/common/util/error.go:279\ngithub.com/kubeflow/pipelines/backend/src/apiserver/server.(*RunServer).GetRun\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/server/run_server.go:153\ngithub.com/kubeflow/pipelines/backend/api/go_client._RunService_GetRun_Handler.func1\n\t/go/src/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:2180\nmain.apiServerInterceptor\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/interceptor.go:30\ngithub.com/kubeflow/pipelines/backend/api/go_client._RunService_GetRun_Handler\n\t/go/src/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:2182\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1286\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1609\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:934\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357"}]}

```

 Interestingly I can successfully request using `get_experiment` method from inside pipeline B's component.

My questions all revolve around how to resolve this:
1. Is this expected behaviour?
2. I have seen the ability to assign service accounts to pipeline runs - is this an avenue way to grant authentication to the executing pods of pipeline B so that the `get_run` method will succeed when being run from within a component? and if so, could you say how?
3. Is there - more generally - a better way to grab pipeline A's components outputs than my custom parsing code route?

For now I will probably resolve this by moving my run meta data extraction step outside of pipeline B, and feed it the extracted S3 locations as input parameters. just wondering if there's a better way of doing it.

**Comment by SebastianScherer88** [comment]
interestingly, the `read_artifact` method of the client also works from within a kubeflow component.

its just the `get_run` method that throws this authentication issue. weird how 

- looking at the run meta data is being sealed off, but 
- reading in its outputs is allowed

for the same "unauthenticated" client instance

**Comment by kimwnasptd** [comment]
Hi @SebastianScherer88, could you open this issue in the https://github.com/kubeflow/pipelines repo as well? This way the KFP devs will also be in sync and might provide some feedback

**Comment by juliusvonkohout** [comment]
I am securing every api call together with @difince. Your scenario is definitely possible

/close

There has been no activity for a long time. Please reopen if necessary.
Please also consult the Kubeflow slack channel for support questions.
