### ISSUE TITLE
[codeserver-python-bug] codeserver-python image 'Not Found' error in notebooks

### ISSUE THREAD

**Issue by ghost** [kubeflow/kubeflow#7099]
/kind bug

**What steps did you take and what happened:**

Modified the example notebook server base image with the installation of some terminal programs (full list of programs that I installed at below), then build the base codeserver image with the new base image. After that, build the codeserver-python image with the new base codeserver image. By following the image build, uploaded the new codeserver-python image to gcr.io registry.

Finally, I created a new notebook server with new image and when I connected to my new notebook, got `Not Found.`error on the web browser screen with the logs:

```bash
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-copy-tmp-home: executing... 
[cont-init.d] 01-copy-tmp-home: exited 0.
[cont-init.d] 02-conda-init: executing... 
no change     /opt/conda/condabin/conda
no change     /opt/conda/bin/conda
no change     /opt/conda/bin/conda-env
no change     /opt/conda/bin/activate
no change     /opt/conda/bin/deactivate
no change     /opt/conda/etc/profile.d/conda.sh
no change     /opt/conda/etc/fish/conf.d/conda.fish
no change     /opt/conda/shell/condabin/Conda.psm1
no change     /opt/conda/shell/condabin/conda-hook.ps1
no change     /opt/conda/lib/python3.8/site-packages/xontrib/conda.xsh
no change     /opt/conda/etc/profile.d/conda.csh
modified      /home/jovyan/.bashrc
==> For changes to take effect, close and re-open your current shell. <==
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run
    $ conda init <SHELL_NAME>
Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell
See 'conda init --help' for more information and options.
IMPORTANT: You may need to close and restart your shell after running 'conda init'.
[cont-init.d] 02-conda-init: exited 1.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2023-04-15T12:31:03.262Z] info  code-server 4.3.0 09bc30027a7fbba170f907a527eaa9f7219fe739
[2023-04-15T12:31:03.263Z] info  Using user-data-dir ~/.local/share/code-server
[2023-04-15T12:31:03.282Z] info  Using config file ~/.config/code-server/config.yaml
[2023-04-15T12:31:03.282Z] info  HTTP server listening on http://0.0.0.0:8888/ 
[2023-04-15T12:31:03.282Z] info    - Authentication is disabled 
[2023-04-15T12:31:03.282Z] info    - Not serving HTTPS 
[12:31:53] Extension host agent started.
Error: Unexpected SIGPIPE
    at process.<anonymous> (/usr/lib/code-server/lib/vscode/out/bootstrap.js:1:370)
    at process.emit (events.js:400:28)
```

**What did you expect to happen:**

I was expecting to open new notebook with the new codeserver-python image without any issues.

**Anything else you would like to add:**

`Modified base image command:`

```Dockerfile
RUN export DEBIAN_FRONTEND=noninteractive \
 && apt-get -yq update \
 && apt-get -yq install --no-install-recommends \
    apt-transport-https \
    bash \
    bzip2 \
    ca-certificates \
    curl \
    git \
    gnupg \
    gnupg2 \
    locales \
    build-essential \
    htop \
    jq \
    tree \
    strace \
    screen \
    lsb-release \
    nano \
    software-properties-common \
    tzdata \
    unzip \
    vim \
    wget \
    zip \
 && echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list \
 && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add - \
 && apt-get -yq update \
 && apt-get -yq install google-cloud-sdk \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*
```

`codeserver-python image Dockerfile:`

```Dockerfile
# Use the respective Makefile to pass the appropriate BASE_IMG and build the image correctly
ARG BASE_IMG=<codeserver>
FROM $BASE_IMG

USER root

# args - software versions
ARG CODESERVER_PYTHON_VERSION=2021.5.842923320
ARG MINIFORGE_ARCH="x86_64"
 # renovate: datasource=github-tags depName=conda-forge/miniforge versioning=loose
ARG MINIFORGE_VERSION=4.10.1-4
ARG PIP_VERSION=21.1.2
ARG PYTHON_VERSION=3.8.10

# setup environment for conda
ENV CONDA_DIR /opt/conda
ENV PATH "${CONDA_DIR}/bin:${PATH}"
RUN mkdir -p ${CONDA_DIR} \
 && chown -R ${NB_USER}:users ${CONDA_DIR}

USER $NB_UID

# install - conda, pip, python
RUN curl -sL "https://github.com/conda-forge/miniforge/releases/download/${MINIFORGE_VERSION}/Miniforge3-${MINIFORGE_VERSION}-Linux-${MINIFORGE_ARCH}.sh" -o /tmp/Miniforge3.sh \
 && curl -sL "https://github.com/conda-forge/miniforge/releases/download/${MINIFORGE_VERSION}/Miniforge3-${MINIFORGE_VERSION}-Linux-${MINIFORGE_ARCH}.sh.sha256" -o /tmp/Miniforge3.sh.sha256 \
 && echo "$(cat /tmp/Miniforge3.sh.sha256 | awk '{ print $1; }') /tmp/Miniforge3.sh" | sha256sum --check \
 && rm /tmp/Miniforge3.sh.sha256 \
 && /bin/bash /tmp/Miniforge3.sh -b -f -p ${CONDA_DIR} \
 && rm /tmp/Miniforge3.sh \
 && conda config --system --set auto_update_conda false \
 && conda config --system --set show_channel_urls true \
 && echo "conda ${MINIFORGE_VERSION:0:-2}" >> ${CONDA_DIR}/conda-meta/pinned \
 && echo "python ${PYTHON_VERSION}" >> ${CONDA_DIR}/conda-meta/pinned \
 && conda install -y -q \
    python=${PYTHON_VERSION} \
    conda=${MINIFORGE_VERSION:0:-2} \
    pip=${PIP_VERSION} \
 && conda update -y -q --all \
 && conda clean -a -f -y \
 && chown -R ${NB_USER}:users ${CONDA_DIR} \
 && chown -R ${NB_USER}:users ${HOME}

# install - requirements.txt
COPY --chown=jovyan:users requirements.txt /tmp
RUN python3 -m pip install -r /tmp/requirements.txt --quiet --no-cache-dir \
 && rm -f /tmp/requirements.txt \
 && chown -R ${NB_USER}:users ${CONDA_DIR} \
 && chown -R ${NB_USER}:users ${HOME}

# install - codeserver extensions
RUN curl -# -L -o /tmp/ms-python-release.vsix "https://github.com/microsoft/vscode-python/releases/download/${CODESERVER_PYTHON_VERSION}/ms-python-release.vsix" \
 && code-server --install-extension /tmp/ms-python-release.vsix \
 && code-server --list-extensions --show-versions

# s6 - copy scripts
COPY --chown=jovyan:users s6/ /etc

# s6 - 01-copy-tmp-home
USER root
RUN mkdir -p /tmp_home \
 && cp -r ${HOME} /tmp_home \
 && chown -R ${NB_USER}:users /tmp_home
USER ${NB_UID}
```

`Modified Makefile of codeserver-python image:`

```Dockerfile
TAG ?= $(shell git describe --tags --always --dirty)
REGISTRY ?= gcr.io/<REDACTED_PROJECT>

docker-build-codeserver:
	$(MAKE) docker-build -C ../codeserver TAG=${TAG}

docker-build-cpu: docker-build-codeserver
	docker build -t ${REGISTRY}/codeserver-python:${TAG} --build-arg BASE_IMG=${REGISTRY}/codeserver:${TAG} -f cpu.Dockerfile . --platform=linux/amd64

docker-build-cuda: docker-build-codeserver-cuda
	docker build -t ${REGISTRY}/codeserver-python-cuda:${TAG} --build-arg BASE_IMG=${REGISTRY}/codeserver:${TAG} -f cuda.Dockerfile . --platform=linux/amd64

docker-push:
	docker push ${REGISTRY}/codeserver-python:${TAG}
```

**Environment:**

- Kubeflow version: 1.6.0
- Kubectl version: 1.21.0

**Comment by oguzhanoyan** [comment]
Hello 

When I added annotation(notebooks.kubeflow.org/http-rewrite-uri: /) to notebook kind, I successfully deployed. 

Please check ; https://github.com/kubeflow/kubeflow/issues/6404#issuecomment-1505050303
