### ISSUE TITLE
openmpi controller exited with error

### ISSUE THREAD

**Issue by zuowang** [kubeflow/kubeflow#718]
@jiezhang Could you help me on this?

```
controller entered
controller exited
Traceback (most recent call last):
  File "/root/controller/main.py", line 17, in <module>
    main()
  File "/root/controller/main.py", line 13, in main
    ctl.wait_master_terminated()
  File "/root/controller/controller.py", line 44, in wait_master_terminated
    phase = self._get_master_phase()
  File "/usr/local/lib/python3.6/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/usr/local/lib/python3.6/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/local/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/root/controller/controller.py", line 55, in _get_master_phase
    pod = self.api.read_namespaced_pod(self.master, self.namespace)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 18163, in read_namespaced_pod
    (data) = self.read_namespaced_pod_with_http_info(name, namespace, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 18254, in read_namespaced_pod_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 155, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 342, in request
    headers=headers)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/rest.py", line 231, in GET
    query_params=query_params)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Wed, 25 Apr 2018 05:36:04 GMT', 'Content-Length': '305'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"slim-377c8-master\" is forbidden: User \"system:serviceaccount:tfworkflow:default\" cannot get pods in the namespace \"tfworkflow\"","reason":"Forbidden","details":{"name":"slim-377c8-master","kind":"pods"},"code":403}

```

**Comment by jiezhang** [comment]
@zuowang Can you try to enable legacy authorization in your cluster? Please also paste the output of `kubectl version` here.

https://cloud.google.com/kubernetes-engine/docs/how-to/role-based-access-control?hl=en_US&_ga=2.8774710.-248250448.1522362327

![image](https://user-images.githubusercontent.com/37601164/39258107-ff8ddb34-4867-11e8-847c-4a5da34d001f.png)

**Comment by zuowang** [comment]
```

Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by zuowang** [comment]
resolved with 
`
kubectl create rolebinding  default-binding --clusterrole=cluster-admin --serviceaccount=kubeflow:default --namespace=kubeflow
`

but after exec `ks delete default  -c `, all pod hanging on Terminating  status
```
slim-3897e-master                    0/1       Terminating   0          1d
slim-3897e-worker-0                  0/2       Terminating   0          1d
slim-3897e-worker-1                  0/2       Terminating   0          1d
```

**Comment by jiezhang** [comment]
@zuowang All the pods should be in "Completed" status after the MPI job finishes. The deletion is supposed to finish instantly. Is that not working for you?

Even if the job is still running, delete should force terminate the pods after 30 seconds (see terminationGracePeriodSeconds in the pod spec). What's your Kubernetes cluster? 

```
jiez-C02W108JHTDG:openmpi jiez$ kubectl get pod -n kubeflow --show-all
NAME               READY     STATUS      RESTARTS   AGE
openmpi-master     0/1       Completed   0          1m
openmpi-worker-0   0/2       Completed   0          1m
openmpi-worker-1   0/2       Completed   0          1m
openmpi-worker-2   0/2       Completed   0          1m
openmpi-worker-3   0/2       Completed   0          1m
jiez-C02W108JHTDG:openmpi jiez$ ks delete default -c openmpi
INFO  Deleting pods kubeflow.openmpi-worker-3
INFO  Deleting pods kubeflow.openmpi-master
INFO  Deleting pods kubeflow.openmpi-worker-0
INFO  Deleting pods kubeflow.openmpi-worker-1
INFO  Deleting pods kubeflow.openmpi-worker-2
INFO  Deleting services kubeflow.openmpi
INFO  Deleting configmaps kubeflow.openmpi-assets
jiez-C02W108JHTDG:openmpi jiez$ kubectl get pod -n kubeflow --show-all
No resources found.
```

**Comment by zuowang** [comment]
I have terminationGracePeriodSeconds in the spec. But it just stay in Terminating status forever.
```
      "restartPolicy": "Never",
      "schedulerName": "default-scheduler",
      "subdomain": "slim-e0e01",
      "terminationGracePeriodSeconds": 30,
      "volumes": [

```
