### ISSUE TITLE
Ambassador crashing on minikube

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#734]
Posting on behalf of someone else. On minikube they observed Ambassador crashing.

It looks like there's is an SSL issue connecting to the ApiServer to list resources. Doesn't look like a Kubeflow issue perse.

```
$ k logs ambassador-859f957c8c-ngngw -c ambassador
./entrypoint.sh: set: line 65: can't access tty; job control turned off
2018-04-27 05:38:39,804 ERROR Certificate did not match expected hostname: 10.96.0.1. Certificate: {'subject': ((('organizationName', 'system:masters'),), (('commonName', 'minikube'),)), 'issuer': ((('commonName', 'minikubeCA'),),), 'version': 3, 'serialNumber': '02', 'notBefore': 'Apr 27 05:27:26 2018 GMT', 'notAfter': 'Apr 27 05:27:26 2019 GMT', 'subjectAltName': (('DNS', 'kubernetes.default.svc.cluster.local'), ('DNS', 'kubernetes.default.svc'), ('DNS', 'kubernetes.default'), ('DNS', 'kubernetes'), ('DNS', 'localhost'), ('IP Address', '192.168.99.100'), ('IP Address', '10.0.0.1'))}
2018-04-27 05:38:39 kubewatch 0.30.1 ERROR: Certificate did not match expected hostname: 10.96.0.1. Certificate: {'subject': ((('organizationName', 'system:masters'),), (('commonName', 'minikube'),)), 'issuer': ((('commonName', 'minikubeCA'),),), 'version': 3, 'serialNumber': '02', 'notBefore': 'Apr 27 05:27:26 2018 GMT', 'notAfter': 'Apr 27 05:27:26 2019 GMT', 'subjectAltName': (('DNS', 'kubernetes.default.svc.cluster.local'), ('DNS', 'kubernetes.default.svc'), ('DNS', 'kubernetes.default'), ('DNS', 'kubernetes'), ('DNS', 'localhost'), ('IP Address', '192.168.99.100'), ('IP Address', '10.0.0.1'))}
2018-04-27 05:38:39,805 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname '10.96.0.1' doesn't match either of 'kubernetes.default.svc.cluster.local', 'kubernetes.default.svc', 'kubernetes.default', 'kubernetes', 'localhost', '192.168.99.100', '10.0.0.1'",),)': /api/v1/namespaces/default/configmaps
2018-04-27 05:38:39 kubewatch 0.30.1 WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname '10.96.0.1' doesn't match either of 'kubernetes.default.svc.cluster.local', 'kubernetes.default.svc', 'kubernetes.default', 'kubernetes', 'localhost', '192.168.99.100', '10.0.0.1'",),)': /api/v1/namespaces/default/configmaps
2018-04-27 05:38:39,820 ERROR Certificate did not match expected hostname: 10.96.0.1. Certificate: {'subject': ((('organizationName', 'system:masters'),), (('commonName', 'minikube'),)), 'issuer': ((('commonName', 'minikubeCA'),),), 'version': 3, 'serialNumber': '02', 'notBefore': 'Apr 27 05:27:26 2018 GMT', 'notAfter': 'Apr 27 05:27:26 2019 GMT', 'subjectAltName': (('DNS', 'kubernetes.default.svc.cluster.local'), ('DNS', 'kubernetes.default.svc'), ('DNS', 'kubernetes.default'), ('DNS', 'kubernetes'), ('DNS', 'localhost'), ('IP Address', '192.168.99.100'), ('IP Address', '10.0.0.1'))}
2018-04-27 05:38:39 kubewatch 0.30.1 ERROR: Certificate did not match expected hostname: 10.96.0.1. Certificate: {'subject': ((('organizationName', 'system:masters'),), (('commonName', 'minikube'),)), 'issuer': ((('commonName', 'minikubeCA'),),), 'version': 3, 'serialNumber': '02', 'notBefore': 'Apr 27 05:27:26 2018 GMT', 'notAfter': 'Apr 27 05:27:26 2019 GMT', 'subjectAltName': (('DNS', 'kubernetes.default.svc.cluster.local'), ('DNS', 'kubernetes.default.svc'), ('DNS', 'kubernetes.default'), ('DNS', 'kubernetes'), ('DNS', 'localhost'), ('IP Address', '192.168.99.100'), ('IP Address', '10.0.0.1'))}
2018-04-27 05:38:39,821 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname '10.96.0.1' doesn't match either of 'kubernetes.default.svc.cluster.local', 'kubernetes.default.svc', 'kubernetes.default', 'kubernetes', 'localhost', '192.168.99.100', '10.0.0.1'",),)': /api/v1/namespaces/default/configmaps
2018-04-27 05:38:39 kubewatch 0.30.1 WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname '10.96.0.1' doesn't match either of 'kubernetes.default.svc.cluster.local', 'kubernetes.default.svc', 'kubernetes.default', 'kubernetes', 'localhost', '192.168.99.100', '10.0.0.1'",),)': /api/v1/namespaces/default/configmaps
2018-04-27 05:38:39,831 ERROR Certificate did not match expected hostname: 10.96.0.1. Certificate: {'subject': ((('organizationName', 'system:masters'),), (('commonName', 'minikube'),)), 'issuer': ((('commonName', 'minikubeCA'),),), 'version': 3, 'serialNumber': '02', 'notBefore': 'Apr 27 05:27:26 2018 GMT', 'notAfter': 'Apr 27 05:27:26 2019 GMT', 'subjectAltName': (('DNS', 'kubernetes.default.svc.cluster.local'), ('DNS', 'kubernetes.default.svc'), ('DNS', 'kubernetes.default'), ('DNS', 'kubernetes'), ('DNS', 'localhost'), ('IP Address', '192.168.99.100'), ('IP Address', '10.0.0.1'))}
2018-04-27 05:38:39 kubewatch 0.30.1 ERROR: Certificate did not match expected hostname: 10.96.0.1. Certificate: {'subject': ((('organizationName', 'system:masters'),), (('commonName', 'minikube'),)), 'issuer': ((('commonName', 'minikubeCA'),),), 'version': 3, 'serialNumber': '02', 'notBefore': 'Apr 27 05:27:26 2018 GMT', 'notAfter': 'Apr 27 05:27:26 2019 GMT', 'subjectAltName': (('DNS', 'kubernetes.default.svc.cluster.local'), ('DNS', 'kubernetes.default.svc'), ('DNS', 'kubernetes.default'), ('DNS', 'kubernetes'), ('DNS', 'localhost'), ('IP Address', '192.168.99.100'), ('IP Address', '10.0.0.1'))}
2018-04-27 05:38:39,832 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname '10.96.0.1' doesn't match either of 'kubernetes.default.svc.cluster.local', 'kubernetes.default.svc', 'kubernetes.default', 'kubernetes', 'localhost', '192.168.99.100', '10.0.0.1'",),)': /api/v1/namespaces/default/configmaps
2018-04-27 05:38:39 kubewatch 0.30.1 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname '10.96.0.1' doesn't match either of 'kubernetes.default.svc.cluster.local', 'kubernetes.default.svc', 'kubernetes.default', 'kubernetes', 'localhost', '192.168.99.100', '10.0.0.1'",),)': /api/v1/namespaces/default/configmaps
2018-04-27 05:38:39,842 ERROR Certificate did not match expected hostname: 10.96.0.1. Certificate: {'subject': ((('organizationName', 'system:masters'),), (('commonName', 'minikube'),)), 'issuer': ((('commonName', 'minikubeCA'),),), 'version': 3, 'serialNumber': '02', 'notBefore': 'Apr 27 05:27:26 2018 GMT', 'notAfter': 'Apr 27 05:27:26 2019 GMT', 'subjectAltName': (('DNS', 'kubernetes.default.svc.cluster.local'), ('DNS', 'kubernetes.default.svc'), ('DNS', 'kubernetes.default'), ('DNS', 'kubernetes'), ('DNS', 'localhost'), ('IP Address', '192.168.99.100'), ('IP Address', '10.0.0.1'))}
2018-04-27 05:38:39 kubewatch 0.30.1 ERROR: Certificate did not match expected hostname: 10.96.0.1. Certificate: {'subject': ((('organizationName', 'system:masters'),), (('commonName', 'minikube'),)), 'issuer': ((('commonName', 'minikubeCA'),),), 'version': 3, 'serialNumber': '02', 'notBefore': 'Apr 27 05:27:26 2018 GMT', 'notAfter': 'Apr 27 05:27:26 2019 GMT', 'subjectAltName': (('DNS', 'kubernetes.default.svc.cluster.local'), ('DNS', 'kubernetes.default.svc'), ('DNS', 'kubernetes.default'), ('DNS', 'kubernetes'), ('DNS', 'localhost'), ('IP Address', '192.168.99.100'), ('IP Address', '10.0.0.1'))}
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 346, in connect
    _match_hostname(cert, self.assert_hostname or hostname)
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 356, in _match_hostname
    match_hostname(cert, asserted_hostname)
  File "/usr/lib/python3.6/ssl.py", line 327, in match_hostname
    % (hostname, ', '.join(map(repr, dnsnames))))
ssl.CertificateError: hostname '10.96.0.1' doesn't match either of 'kubernetes.default.svc.cluster.local', 'kubernetes.default.svc', 'kubernetes.default', 'kubernetes', 'localhost', '192.168.99.100', '10.0.0.1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/application/kubewatch.py", line 493, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/application/kubewatch.py", line 476, in main
    sync(restarter)
  File "/application/kubewatch.py", line 313, in sync
    for x in v1.list_namespaced_config_map(restarter.namespace).items ]
  File "/usr/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 12395, in list_namespaced_config_map
    (data) = self.list_namespaced_config_map_with_http_info(namespace, **kwargs)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 12497, in list_namespaced_config_map_with_http_info
    collection_formats=collection_formats)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 335, in call_api
    _preload_content, _request_timeout)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 148, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 371, in request
    headers=headers)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/rest.py", line 250, in GET
    query_params=query_params)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/rest.py", line 223, in request
    headers=headers)
  File "/usr/lib/python3.6/site-packages/urllib3/request.py", line 66, in request
    **urlopen_kw)
  File "/usr/lib/python3.6/site-packages/urllib3/request.py", line 87, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python3.6/site-packages/urllib3/poolmanager.py", line 321, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.96.0.1', port=443): Max retries exceeded with url: /api/v1/namespaces/default/configmaps (Caused by SSLError(CertificateError("hostname '10.96.0.1' doesn't match either of 'kubernetes.default.svc.cluster.local', 'kubernetes.default.svc', 'kubernetes.default', 'kubernetes', 'localhost', '192.168.99.100', '10.0.0.1'",),))
AMBASSADOR: kubewatch sync exited with status 1
Here's the envoy.json we were trying to run with:
ls: /etc/envoy*.json: No such file or directory
No config generated.
AMBASSADOR: shutting down
```
/cc @vishh @richard @dlorenc @richarddli

**Comment by kflynn** [comment]
The other thing we've seen is `minikube` being started without RBAC support. Apparently you need

```
$ minikube start --extra-config=apiserver.authorization-mode=RBAC
```

for that to work correctly?
