### ISSUE TITLE
Kubeflow setup following tutorial not deploying, hanging up on cert-manager

### ISSUE THREAD

**Issue by palmerss** [kubeflow/kubeflow#7406]
/kind bug

**What steps did you take and what happened:**

Hello, I have been following the tutorial [here](https://awslabs.github.io/kubeflow-manifests/docs/deployment/) from the prerequisites to creating the EKS Cluster to Vanilla installation via Manifest Deployment. I am currently using cloud9 to set up everything on a t2.medium instance.

When getting to the point where I run
`make deploy-kubeflow INSTALLATION_OPTION=kustomize DEPLOYMENT_OPTION=vanilla`
The system hangs up when installing cert-manager due to timeouts, output from install is posted below

```
palmerss:~/environment/kubeflow-manifests ((v1.7.0-aws-b1.0.3)) $ make deploy-kubeflow INSTALLATION_OPTION=kustomize DEPLOYMENT_OPTION=vanilla
test A101xCluster || (echo Please export CLUSTER_NAME variable ; exit 1)
test us-east-2 || (echo Please export CLUSTER_REGION variable ; exit 1)
aws eks update-kubeconfig --name A101xCluster --region us-east-2
Added new context arn:aws:eks:us-east-2:837587209284:cluster/A101xCluster to /home/ubuntu/.kube/config
yq e '.cluster.name=env(CLUSTER_NAME)' -i tests/e2e/utils/ack_sm_controller_bootstrap/config.yaml
yq e '.cluster.region=env(CLUSTER_REGION)' -i tests/e2e/utils/ack_sm_controller_bootstrap/config.yaml
cd tests/e2e && PYTHONPATH=.. python3.8 utils/ack_sm_controller_bootstrap/setup_sm_controller_req.py
/home/ubuntu/environment/kubeflow-manifests/tests/e2e/utils/utils.py:271: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if retcode is not 0:
=================================================================
                          Reading Config                         
=================================================================
=================================================================
        Create OIDC IAM role for ACK SageMaker Controller        
=================================================================
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
An error occurred (EntityAlreadyExists) when calling the CreateRole operation: Role with name kf-ack-sm-controller-role-A101xCluster already exists.
Try running cleanup_sm_controller_req.py
=================================================================
         Writing params.env for ACK SageMaker Controller         
=================================================================
Params file written to : ../../awsconfigs/common/ack-sagemaker-controller/params.env
Editing ./utils/ack_sm_controller_bootstrap/config.yaml with appropriate values...
Config file written to : ./utils/ack_sm_controller_bootstrap/config.yaml
=================================================================
                             SUCCESS                             
=================================================================
cd tests/e2e && PYTHONPATH=.. python3.8 utils/kubeflow_installation.py --deployment_option vanilla --installation_option kustomize --pipeline_s3_credential_option irsa --cluster_name A101xCluster
A101xCluster
=================================================================
 Installing kubeflow vanilla deployment with kustomize with irsa 
=================================================================
==========Installing cert-manager==========
namespace/cert-manager created
customresourcedefinition.apiextensions.k8s.io/certificaterequests.cert-manager.io created
customresourcedefinition.apiextensions.k8s.io/certificates.cert-manager.io created
customresourcedefinition.apiextensions.k8s.io/challenges.acme.cert-manager.io created
customresourcedefinition.apiextensions.k8s.io/clusterissuers.cert-manager.io created
customresourcedefinition.apiextensions.k8s.io/issuers.cert-manager.io created
customresourcedefinition.apiextensions.k8s.io/orders.acme.cert-manager.io created
serviceaccount/cert-manager created
serviceaccount/cert-manager-cainjector created
serviceaccount/cert-manager-webhook created
role.rbac.authorization.k8s.io/cert-manager-webhook:dynamic-serving created
role.rbac.authorization.k8s.io/cert-manager-cainjector:leaderelection created
role.rbac.authorization.k8s.io/cert-manager:leaderelection created
clusterrole.rbac.authorization.k8s.io/cert-manager-cainjector created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-approve:cert-manager-io created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-certificates created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-certificatesigningrequests created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-challenges created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-clusterissuers created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-ingress-shim created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-issuers created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-orders created
clusterrole.rbac.authorization.k8s.io/cert-manager-edit created
clusterrole.rbac.authorization.k8s.io/cert-manager-view created
clusterrole.rbac.authorization.k8s.io/cert-manager-webhook:subjectaccessreviews created
rolebinding.rbac.authorization.k8s.io/cert-manager-webhook:dynamic-serving created
rolebinding.rbac.authorization.k8s.io/cert-manager-cainjector:leaderelection created
rolebinding.rbac.authorization.k8s.io/cert-manager:leaderelection created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-cainjector created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-approve:cert-manager-io created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-certificates created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-certificatesigningrequests created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-challenges created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-clusterissuers created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-ingress-shim created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-issuers created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-orders created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-webhook:subjectaccessreviews created
configmap/cert-manager-webhook created
service/cert-manager created
service/cert-manager-webhook created
deployment.apps/cert-manager created
deployment.apps/cert-manager-cainjector created
deployment.apps/cert-manager-webhook created
mutatingwebhookconfiguration.admissionregistration.k8s.io/cert-manager-webhook created
validatingwebhookconfiguration.admissionregistration.k8s.io/cert-manager-webhook created
wait for 60s for cert-manager-webhook resource to be ready...
Waiting for cert-manager pods to be ready ...
running command: kubectl wait --for=condition=ready pod -l 'app.kubernetes.io/instance in (cert-manager)' --timeout=240s -n cert-manager
timed out waiting for the condition on pods/cert-manager-74d949c895-bsdlq
timed out waiting for the condition on pods/cert-manager-cainjector-d9bc5979d-jbtg6
timed out waiting for the condition on pods/cert-manager-webhook-84b7ddd796-h74wh
error: unknown flag: --timeout
See 'kubectl describe --help' for usage.
Waiting for cert-manager pods to be ready ...
running command: kubectl wait --for=condition=ready pod -l 'app.kubernetes.io/instance in (cert-manager)' --timeout=240s -n cert-manager
timed out waiting for the condition on pods/cert-manager-74d949c895-bsdlq
timed out waiting for the condition on pods/cert-manager-cainjector-d9bc5979d-jbtg6
timed out waiting for the condition on pods/cert-manager-webhook-84b7ddd796-h74wh
error: unknown flag: --timeout
See 'kubectl describe --help' for usage.
Waiting for cert-manager pods to be ready ...
running command: kubectl wait --for=condition=ready pod -l 'app.kubernetes.io/instance in (cert-manager)' --timeout=240s -n cert-manager
timed out waiting for the condition on pods/cert-manager-74d949c895-bsdlq
timed out waiting for the condition on pods/cert-manager-cainjector-d9bc5979d-jbtg6
timed out waiting for the condition on pods/cert-manager-webhook-84b7ddd796-h74wh
error: unknown flag: --timeout
See 'kubectl describe --help' for usage.
Traceback (most recent call last):
  File "utils/kubeflow_installation.py", line 324, in <module>
    install_kubeflow(
  File "utils/kubeflow_installation.py", line 101, in install_kubeflow
    install_component(
  File "utils/kubeflow_installation.py", line 180, in install_component
    validate_component_installation(installation_config, component_name)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/retrying.py", line 56, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/retrying.py", line 266, in call
    raise attempt.get()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/retrying.py", line 301, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/lib/python3/dist-packages/six.py", line 719, in reraise
    raise value
  File "/home/ubuntu/.local/lib/python3.8/site-packages/retrying.py", line 251, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "utils/kubeflow_installation.py", line 192, in validate_component_installation
    kubectl_wait_pods(value, namespace, key)
  File "/home/ubuntu/environment/kubeflow-manifests/tests/e2e/utils/utils.py", line 275, in kubectl_wait_pods
    raise Exception("Timeout/error waiting for pod condition")
Exception: Timeout/error waiting for pod condition
make: *** [Makefile:104: deploy-kubeflow] Error 1
palmerss:~/environment/kubeflow-manifests ((v1.7.0-aws-b1.0.3)) $
```

**What did you expect to happen:**
That the installation is successful and that I can move on to access the kubeflow GUI 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
I'm very open to being pointed in any other direction for known tutorials that are more known to work well, I'm very new to kubernetes/kubeflow so I'm really just trying to get things rolling

**Environment**
* Kubernetes version 1.25 (I think this is the version you specify when creating EKS cluster right?)
* Kubeflow version 1.7

**Comment by thesuperzapper** [comment]
@palmerss Please raise this issue with your distribution, in this case https://github.com/awslabs/kubeflow-manifests.

/close
