### ISSUE TITLE
[JupyterLab] KubeFlow 1.8.0 - error when cloning repository

### ISSUE THREAD

**Issue by alekseyolg** [kubeflow/kubeflow#7413]
/kind bug

**What steps did you take and what happened:**
Installation of all components according to instructions.
Used image kubeflownotebookswg/jupyter-scipy:v1.8.0
After installation, we create a laptop based on any image and clone the repository from bitbucket with authorization.
![image](https://github.com/kubeflow/kubeflow/assets/86011874/20a6fe8f-db2e-41d4-8c33-eece020bab5c)

![image](https://github.com/kubeflow/kubeflow/assets/86011874/32fb6161-56c9-4be7-b89c-c87e8e139a86)

I get an error:
```
Traceback (most recent call last): File "/opt/conda/lib/python3.11/site-packages/jupyterlab_git/git.py", line 175, in execute code, output, error = await call_subprocess_with_authentication( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/conda/lib/python3.11/site-packages/jupyterlab_git/git.py", line 119, in call_subprocess_with_authentication i = await p.expect(["Username for .*: ", "Password for .*:"], async_=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/conda/lib/python3.11/site-packages/pexpect/spawnbase.py", line 343, in expect return self.expect_list(compiled_pattern_list, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/conda/lib/python3.11/site-packages/pexpect/spawnbase.py", line 369, in expect_list from ._async import expect_async File "/opt/conda/lib/python3.11/site-packages/pexpect/_async.py", line 7, in <module> @asyncio.coroutine ^^^^^^^^^^^^^^^^^ AttributeError: module 'asyncio' has no attribute 'coroutine'
```
![image](https://github.com/kubeflow/kubeflow/assets/86011874/836a8dfa-c162-4237-abcd-e472db469052)

After execution I get the following in the pod logs:
```
[E 2023-11-16 07:21:49.149 ServerApp] {
      "Host": "kubeflow.dev",
      "Accept": "*/*",
      "Referer": "http://kubeflow.dev/notebook/kubeflow-user-example-com/test/lab",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
    }
[E 2023-11-16 07:21:49.149 ServerApp] 500 POST /notebook/kubeflow-user-example-com/test/git/clone?1700119308889 (edf39191d7f5450dbdb882b9d1810839@127.0.0.6) 73.75ms referer=http://kubeflow.dev/notebook/kubeflow-user-example-com/test/lab
[W 2023-11-16 07:21:55.227 ServerApp.jupyterlab_git] Fail to execute ['git', 'clone', '--recurse-submodules', 'https://bitbucket-my.example/scm/mlops/dags.git', '-q']
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.11/site-packages/jupyterlab_git/git.py", line 175, in execute
        code, output, error = await call_subprocess_with_authentication(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/jupyterlab_git/git.py", line 119, in call_subprocess_with_authentication
        i = await p.expect(["Username for .*: ", "Password for .*:"], async_=True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/pexpect/spawnbase.py", line 343, in expect
        return self.expect_list(compiled_pattern_list,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/pexpect/spawnbase.py", line 369, in expect_list
        from ._async import expect_async
      File "/opt/conda/lib/python3.11/site-packages/pexpect/_async.py", line 7, in <module>
        @asyncio.coroutine
         ^^^^^^^^^^^^^^^^^
    AttributeError: module 'asyncio' has no attribute 'coroutine'
[E 2023-11-16 07:21:55.328 ServerApp] {
      "Host": "kubeflow.dev",
      "Accept": "*/*",
      "Referer": "http://kubeflow.dev/notebook/kubeflow-user-example-com/test/lab",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
    }
[E 2023-11-16 07:21:55.328 ServerApp] 500 POST /notebook/kubeflow-user-example-com/test/git/clone?1700119314925 (edf39191d7f5450dbdb882b9d1810839@127.0.0.6) 220.33ms referer=http://kubeflow.dev/notebook/kubeflow-user-example-com/test/lab
```

**What did you expect to happen:**
Correct cloning of the repository and further work.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 1.8.0 
- kfctl version: (use `kfctl version`): -
- Kubernetes platform: Kubernetes on SberCloud
- Kubernetes version: (use `kubectl version`): 1.25.3
- OS (e.g. from `/etc/os-release`): centos 7

**Comment by alekseyolg** [comment]
similar problem

https://github.com/jupyterlab/jupyterlab-git/issues/1261

**Comment by yingding** [comment]
Here is a workaround https://github.com/kubeflow/manifests/issues/2570#issuecomment-1817225546
