### ISSUE TITLE
Create notebooks page and get [500] error

### ISSUE THREAD

**Issue by momaek** [kubeflow/kubeflow#7441]
/kind bug

**What steps did you take and what happened:**

Enter notebook page and get this error

```
[500] An error occured in the backend. http://xxx/jupyter/api/gpus
```

<img width="1057" alt="Screenshot 2024-01-05 at 19 08 40" src="https://github.com/kubeflow/kubeflow/assets/3843588/70010e92-0f1e-41e4-b236-7c72cc02f9c6">

**What did you expect to happen:**
Can get GPU Vendor and GPUs successfully

**Anything else you would like to add:**
logs from jupyter :
```
2024-01-05 11:08:37,929 | kubeflow.kubeflow.crud_backend.errors.handlers | ERROR | Caught and unhandled Exception!
2024-01-05 11:08:37,929 | kubeflow.kubeflow.crud_backend.errors.handlers | ERROR | module 'apps.common.status' has no attribute 'capacity'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/src/apps/common/routes/get.py", line 118, in get_gpu_vendors
    installed_resources.update(status.capacity.keys())
AttributeError: module 'apps.common.status' has no attribute 'capacity'
```

**Environment:**

- Kubeflow version:  build_version dev_local, master a642df7e899f9c313f4c1072189d7ee6491bdcf2 
- kfctl version: (use `kfctl version`):
- Kubernetes platform:  kubeadm version: &version.Info{Major:"1", Minor:"28", GitVersion:"v1.28.4", GitCommit:"bae2c62678db2b5053817bc97181fcc2e8388103", GitTreeState:"clean", BuildDate:"2023-11-15T16:56:18Z", GoVersion:"go1.20.11", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes version: 
```
kubectl version:
Client Version: v1.28.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.4
```
- OS:  22.04.3 LTS (Jammy Jellyfish)

**Comment by thesuperzapper** [comment]
@momaek thanks for raising this, we are tracking a fix for 1.8.1 in https://github.com/kubeflow/kubeflow/issues/7453#issuecomment-1913283891
