### ISSUE TITLE
AttributeError: module 'asyncio' has no attribute 'coroutine'

### ISSUE THREAD

**Issue by maisam94** [kubeflow/kubeflow#7462]
Hey,
I am using jupyterlab on EKS, used image kubeflownotebookswg/jupyter-tensorflow-cuda-full
After installation, I am clone the repository from GitHub with authentication.

I get an error:

Traceback (most recent call last): File "/opt/conda/lib/python3.11/site-packages/jupyterlab_git/git.py", line 175, in execute code, output, error = await call_subprocess_with_authentication( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/conda/lib/python3.11/site-packages/jupyterlab_git/git.py", line 119, in call_subprocess_with_authentication i = await p.expect(["Username for .: ", "Password for .:"], async_=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/conda/lib/python3.11/site-packages/pexpect/spawnbase.py", line 343, in expect return self.expect_list(compiled_pattern_list, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/conda/lib/python3.11/site-packages/pexpect/spawnbase.py", line 369, in expect_list from ._async import expect_async File "/opt/conda/lib/python3.11/site-packages/pexpect/_async.py", line 7, in @asyncio.coroutine ^^^^^^^^^^^^^^^^^ AttributeError: module 'asyncio' has no attribute 'coroutine'

How can fix it, and can we clone from GitHub?

Thanks

**Comment by pythonking6** [comment]
It is striking to me that this issue has been open since February 7 and yet it is still in Needs Triage!!

**Comment by mildmojo** [comment]
This looks like the upstream issue:

https://github.com/jupyterlab/jupyterlab-git/issues/1261

Sounds like the `pexpect` package needs to be updated to at least v4.9.0 to support Python 3.11. When I encountered this problem in a new jupyter notebook in my kubeflow deployment, I was able to use Kaschmiri's workaround from that issue, starting a terminal in the notebook and running:

```
conda config --add channels conda-forge
conda config --set channel_priority strict
conda update pexpect
```

It took a few minutes to run, and then I was able to clone a private repo with my username and PAT.

I'd like to see a full fix or a way to run that workaround on each new notebook.
