### ISSUE TITLE
JupyterHub pods restarting for unknown reason

### ISSUE THREAD

**Issue by cwbeitel** [kubeflow/kubeflow#752]
I'm seeing an issue where when returning to JupyterHub with a previously running session I'm presented with a log-in screen instead of my workspace, presumably because the underlying pod has re-started for some reason. This is problematic if there was unsaved work on the attached volume.

I am using the autoscaler (on GKE) with a min instance number of 1. Presumably the autoscaler doesn't scale down "inactive" pods. And presumably when pods are launched by kube spawner they have resource reservations attached that are recognized by the autoscaler.

Currently I see that tf-hub and ambassador have re-starts which might be relevant.

```
~ kubectl get pods -n kubeflow
NAME                                   READY     STATUS    RESTARTS   AGE
ambassador-56c8966c67-ltmb2            2/2       Running   4          24d
ambassador-56c8966c67-mvqjc            2/2       Running   1          58d
ambassador-56c8966c67-rtqtq            2/2       Running   0          22d
argo-ui-5d7fbb58d4-m6lmm               1/1       Running   0          58d
jupyter-cwbeitel                       1/1       Running   0          1d
nfs-1-provisioner-7497d85d76-8bs9t     1/1       Running   0          4d
nfs-2-provisioner-59bf96c5d4-g22wx     1/1       Running   0          58d
tf-hub-0                               1/1       Running   1          4d
tf-job-operator-5c497d644d-89jg7       1/1       Running   3          4d
workflow-controller-7d8f4bc5df-zrlvk   1/1       Running   0          4d

```

tf-hub logs:

```
[I 2018-05-02 15:02:46.001 JupyterHub reflector:98] watching for pods with label selector heritage=jupyterhub,component=singleuser-server in namespace kubeflow
2018-05-02 15:03:49,119 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fcec0cbf860>: Failed to establish a new connection: [Errno 111] Connection refused',)': /api/v1/namespaces/kubeflow/pods?labelSelector=heritage%3Djupyterhub%2Ccomponent%3Dsingleuser-server
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fcec0cbf860>: Failed to establish a new connection: [Errno 111] Connection refused',)': /api/v1/namespaces/kubeflow/pods?labelSelector=heritage%3Djupyterhub%2Ccomponent%3Dsingleuser-server
2018-05-02 15:03:49,121 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fcec1031198>: Failed to establish a new connection: [Errno 111] Connection refused',)': /api/v1/namespaces/kubeflow/pods?labelSelector=heritage%3Djupyterhub%2Ccomponent%3Dsingleuser-server
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fcec1031198>: Failed to establish a new connection: [Errno 111] Connection refused',)': /api/v1/namespaces/kubeflow/pods?labelSelector=heritage%3Djupyterhub%2Ccomponent%3Dsingleuser-server
2018-05-02 15:03:49,122 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fcec10311d0>: Failed to establish a new connection: [Errno 111] Connection refused',)': /api/v1/namespaces/kubeflow/pods?labelSelector=heritage%3Djupyterhub%2Ccomponent%3Dsingleuser-server
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fcec10311d0>: Failed to establish a new connection: [Errno 111] Connection refused',)': /api/v1/namespaces/kubeflow/pods?labelSelector=heritage%3Djupyterhub%2Ccomponent%3Dsingleuser-server
[E 2018-05-02 15:03:49.124 JupyterHub reflector:123] Error when watching pods, retrying in 12.8s
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/kubespawner/reflector.py", line 101, in _watch_and_update
        resource_version = self._list_and_update()
      File "/usr/local/lib/python3.6/site-packages/kubespawner/reflector.py", line 66, in _list_and_update
        label_selector=self.label_selector
      File "/usr/local/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 13060, in list_namespaced_pod
        (data) = self.list_namespaced_pod_with_http_info(namespace, **kwargs)
      File "/usr/local/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 13162, in list_namespaced_pod_with_http_info
        collection_formats=collection_formats)
      File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 335, in call_api
        _preload_content, _request_timeout)
      File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 148, in __call_api
        _request_timeout=_request_timeout)
      File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 371, in request
        headers=headers)
      File "/usr/local/lib/python3.6/site-packages/kubernetes/client/rest.py", line 250, in GET
        query_params=query_params)
      File "/usr/local/lib/python3.6/site-packages/kubernetes/client/rest.py", line 223, in request
        headers=headers)
      File "/usr/local/lib/python3.6/site-packages/urllib3/request.py", line 66, in request
        **urlopen_kw)
      File "/usr/local/lib/python3.6/site-packages/urllib3/request.py", line 87, in request_encode_url
        return self.urlopen(method, url, **extra_kw)
      File "/usr/local/lib/python3.6/site-packages/urllib3/poolmanager.py", line 321, in urlopen
        response = conn.urlopen(method, u.request_uri, **kw)
      File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 668, in urlopen
        **response_kw)
      File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 668, in urlopen
        **response_kw)
      File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 668, in urlopen
        **response_kw)
      File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
        _stacktrace=sys.exc_info()[2])
      File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
        raise MaxRetryError(_pool, url, error or ResponseError(cause))
    urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.47.240.1', port=443): Max retries exceeded with url: /api/v1/namespaces/kubeflow/pods?labelSelector=heritage%3Djupyterhub%2Ccomponent%3Dsingleuser-server (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fcec11634a8>: Failed to establish a new connection: [Errno 111] Connection refused',))

[I 2018-05-02 15:04:01.938 JupyterHub reflector:98] watching for pods with label selector heritage=jupyterhub,component=singleuser-server in namespace kubeflow
[E 2018-05-02 15:04:09.423 JupyterHub reflector:123] Error when watching pods, retrying in 25.6s
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/kubespawner/reflector.py", line 101, in _watch_and_update
        resource_version = self._list_and_update()
      File "/usr/local/lib/python3.6/site-packages/kubespawner/reflector.py", line 66, in _list_and_update
        label_selector=self.label_selector
      File "/usr/local/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 13060, in list_namespaced_pod
        (data) = self.list_namespaced_pod_with_http_info(namespace, **kwargs)
      File "/usr/local/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 13162, in list_namespaced_pod_with_http_info
        collection_formats=collection_formats)
      File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 335, in call_api
        _preload_content, _request_timeout)
      File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 148, in __call_api
        _request_timeout=_request_timeout)
      File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 371, in request
        headers=headers)
      File "/usr/local/lib/python3.6/site-packages/kubernetes/client/rest.py", line 250, in GET
        query_params=query_params)
      File "/usr/local/lib/python3.6/site-packages/kubernetes/client/rest.py", line 240, in request
        raise ApiException(http_resp=r)
    kubernetes.client.rest.ApiException: (403)
    Reason: Forbidden
    HTTP response headers: HTTPHeaderDict({'Audit-Id': '3774d8f8-5326-4fd2-9c21-038a82680d6a', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Wed, 02 May 2018 15:04:09 GMT', 'Content-Length': '318'})
    HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods is forbidden: User \"system:serviceaccount:kubeflow:jupyter-hub\" cannot list pods in the namespace \"kubeflow\": Unknown user \"system:serviceaccount:kubeflow:jupyter-hub\"","reason":"Forbidden","details":{"kind":"pods"},"code":403}

```

**Comment by inc0** [comment]
Log looks like RBAC issue. Jupyterhub isn't allowed to list namespaces, try adding (temporarily) permissive RBAC rules and see if it helps. If so, we need to add RBAC bindings to our jupyterhub prototype

**Comment by xieydd** [comment]
@inc0 How to create (temporarily) permissive RBAC rules?
