### ISSUE TITLE
Permission deny issue during executing Jupyter notebook "PermissionError: [Errno 13] Permission denied: '/home/jovyan/.jupyter'"

### ISSUE THREAD

**Issue by thsmfe001** [kubeflow/kubeflow#7626]
I have tried to solve permission deny problem during spawing up jupyter notebook but all things i tried were failed.
I already changed images on kubeflow dashboard UI and made customized image as well.
Poddefaults doesn't support root previlige to change ownership pod home directory to jupyter notebook user (jovyan).
Below is dockerfile to customize existing image on kubeflow. But the directory ownership wasn't changed.
Please check and give a solution to solve this situation.

 cat Dockerfile

```Dockerfile
# Use a base image provided by Kubeflow Notebooks
FROM kubeflownotebookswg/jupyter-pytorch-full:latest

# Set environment variables
ENV NB_PREFIX=/notebook
ENV NB_USER=jovyan

# Switch to root to perform installations and configurations
USER root

# Install additional Python packages
RUN pip install --no-cache-dir \
    bokeh==3.3.4 \
    cloudpickle==2.2.1 \
    dill==0.3.8 \
    ipympl==0.9.4 \
    matplotlib==3.8.4 \
    numpy==1.24.4 \
    pandas==2.1.4 \
    scikit-image==0.22.0 \
    scikit-learn==1.3.2 \
    scipy==1.11.3 \
    seaborn==0.13.2 \
    xgboost==1.7.6

# Set working directory and ensure ownership is set correctly
WORKDIR /home/jovyan
RUN chown -R jovyan:users /home/jovyan/
USER jovyan
```
----------------------------------------------------------------------------------------------

Below is pod's directory status.

```
(base) jovyan@pytorch03-0:~$ ls -la
total 20
drwxr-xr-x 4 root root 4096 Jul  2 02:35 .
drwxr-xr-x 1 root root 4096 May 27 21:10 ..
-rw-r--r-- 1 root root   56 Jul  2 02:35 .bashrc
drwxr-xr-x 3 root root 4096 Jul  2 02:35 .cache
drwxr-xr-x 2 root root 4096 Jul  2 02:35 .conda
```

As you can see the related directory didn't make proprely like .local and .jupyter.

Below is logs from the pod.

```
[E 2024-07-02 08:06:40.841 LabApp] {
      "Host": "192.168.10.201:30261",
      "Accept": "*/*",
      "Referer": "http://192.168.10.201:30261/notebook/kubeflow-user-example-com/pytorch03/lab",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
    }
[E 2024-07-02 08:06:40.841 LabApp] 500 PUT /notebook/kubeflow-user-example-com/pytorch03/lab/api/workspaces/default?1719907600266 (1db22ad8c3574fe298104fef8effc707@127.0.0.6) 1.58ms referer=http://192.168.10.201:30261/notebook/kubeflow-user-example-com/pytorch03/lab
[W 2024-07-02 08:07:17.863 ServerApp] 500 PUT /notebook/kubeflow-user-example-com/pytorch03/lab/api/workspaces/default?1719907637292 (127.0.0.6): [Errno 13] Permission denied: '/home/jovyan/.jupyter'
[W 2024-07-02 08:07:17.864 LabApp] wrote error: "[Errno 13] Permission denied: '/home/jovyan/.jupyter'"
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.11/pathlib.py", line 1116, in mkdir
        os.mkdir(self, mode)
    FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/.jupyter/lab/workspaces'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.11/pathlib.py", line 1116, in mkdir
        os.mkdir(self, mode)
    FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/.jupyter/lab'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.11/site-packages/jupyterlab_server/workspaces_handler.py", line 220, in put
        self.manager.save(space_name, raw)
      File "/opt/conda/lib/python3.11/site-packages/jupyterlab_server/workspaces_handler.py", line 140, in save
        self.workspaces_dir.mkdir(parents=True)
      File "/opt/conda/lib/python3.11/pathlib.py", line 1120, in mkdir
        self.parent.mkdir(parents=True, exist_ok=True)
      File "/opt/conda/lib/python3.11/pathlib.py", line 1120, in mkdir
        self.parent.mkdir(parents=True, exist_ok=True)
      File "/opt/conda/lib/python3.11/pathlib.py", line 1116, in mkdir
        os.mkdir(self, mode)
    PermissionError: [Errno 13] Permission denied: '/home/jovyan/.jupyter'

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/tornado/web.py", line 3301, in wrapper
        return method(self, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/jupyterlab_server/workspaces_handler.py", line 224, in put
        raise web.HTTPError(500, str(e)) from e
    tornado.web.HTTPError: HTTP 500: Internal Server Error ([Errno 13] Permission denied: '/home/jovyan/.jupyter')
```

**Comment by thesuperzapper** [comment]
@thsmfe001 two things:

1. Never use the `:latest` tag when building a docker image. It's impossible to debug anything when you dont even know what your base is (this is just good advice, not specific to Kubeflow)
    - [check dockerhub](https://hub.docker.com/r/kubeflownotebookswg/jupyter-pytorch-full/tags) for a list of available tags (but we recommend using the `v1.X.X` ones in production) 
2. Don't switch to root before installing `pip` packages (this is specific to Kubeflow Notebooks):
      - you will see from our [default images](https://github.com/kubeflow/kubeflow/blob/v1.9.0-rc.1/components/example-notebook-servers/jupyter-scipy/Dockerfile#L19) that we always run pip install as `USER $NB_UID`

**Comment by thsmfe001** [comment]
This case was resolved by cotomized image. I uses ubuntu based image then added additional packages. But i use just root previliage to access any directory for starting up jupyter notebook. 
Also after started up jupyter notebook i faced with pulling image issue from local cached images. I could know latest k8s changed container runtime with containerd. Containerd doesn't cache image with latest tag. So i always faced with pulling image issue due to it. If you faced with image pulling issue from local cached image you should check image's tag. You should avoid latest if you use latest k8s.
