### ISSUE TITLE
Unable to use image-releaser for tf-notebook-workflow

### ISSUE THREAD

**Issue by ankushagarwal** [kubeflow/kubeflow#909]
I am running this in the kubeflow releasing cluster. The gcloud command does not seem to have the credentials to push it to kubeflow-images-public. 

To reproduce this:
```
cd kubeflow/components/image-releaser
ENV=releasing
ks param set --env=${ENV} tf-notebook-workflow namespace kubeflow-releasing
ks param set --env=${ENV} tf-notebook-workflow name "agwl-tensorflow-notebook-image-release-v20180529-bc1cc8b3"
ks param set --env=${ENV} tf-notebook-workflow versionTag "v20180529-bc1cc8b3"
ks param set --env=${ENV} tf-notebook-workflow "JOB_NAME=tensorflow-notebook-image-release,JOB_TYPE=postsubmit,PULL_BASE_SHA=bc1cc8b3,REPO_NAME=kubeflow,REPO_OWNER=kubeflow,BUILD_NUMBER=3B76"

ks apply releasing -c tf-notebook-workflow

```

```
INFO|2018-06-01T18:04:11|/mnt/test-data-volume/agwl-tensorflow-notebook-image-release-v20180529-bc1cc8b3/src/kubeflow/kubeflow/components/build_image.py|46| denied: Token exchange failed for project 'kubeflow-images-public'. Caller does not have permission 'storage.buckets.get'. To configure permissions, follow instructions at: https://cloud.google.com/container-registry/docs/access-control
Traceback (most recent call last):
  File "/mnt/test-data-volume/agwl-tensorflow-notebook-image-release-v20180529-bc1cc8b3/src/kubeflow/kubeflow/components/build_image.py", line 184, in <module>
    main()
  File "/mnt/test-data-volume/agwl-tensorflow-notebook-image-release-v20180529-bc1cc8b3/src/kubeflow/kubeflow/components/build_image.py", line 175, in main
    args.func(args)
  File "/mnt/test-data-volume/agwl-tensorflow-notebook-image-release-v20180529-bc1cc8b3/src/kubeflow/kubeflow/components/build_image.py", line 135, in build_tf_notebook
    run(["gcloud", "docker", "--", "push", image_name])
  File "/mnt/test-data-volume/agwl-tensorflow-notebook-image-release-v20180529-bc1cc8b3/src/kubeflow/kubeflow/components/build_image.py", line 58, in run
    " ".join(command), process.returncode), "\n".join(output))
subprocess.CalledProcessError: Command 'cmd: gcloud docker -- push gcr.io/kubeflow-images-public/tensorflow-1.8.0-notebook-cpu:v20180529-bc1cc8b3 exited with code 1' returned non-zero exit status 1
```

**Comment by lluunn** [comment]
cc @lluunn

**Comment by jlewi** [comment]
What priority is this issue?
