### ISSUE TITLE
Add retries to vm_util.wait_for_operation to fix test flakes

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#934]
We need to add retries in vm_util.wait_for_operation to deal with transient errors getting the operation.
Here:
https://github.com/kubeflow/kubeflow/blob/d90ffccafca6136e0a04925823dc92164bb6b8cf/testing/vm_util.py#L41

One transient error we observed is

```
W
t_util.py|151| Creating /mnt/test-data-volume/kubeflow-presubmit-kubeflow-e2e-minikube-921-4baff83-1932-f15e/output/artifacts/junit_kubeflow-deploy-teardo
wn-minikube.xml
Traceback (most recent call last):
 File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
   "__main__", fname, loader, pkg_name)
 File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
   exec code in run_globals
 File "/mnt/test-data-volume/kubeflow-presubmit-kubeflow-e2e-minikube-921-4baff83-1932-f15e/src/kubeflow/kubeflow/testing/test_deploy.py", line 679, in <m
odule>
   main()
 File "/mnt/test-data-volume/kubeflow-presubmit-kubeflow-e2e-minikube-921-4baff83-1932-f15e/src/kubeflow/kubeflow/testing/test_deploy.py", line 669, in ma
in
   wrap_test(args)
 File "/mnt/test-data-volume/kubeflow-presubmit-kubeflow-e2e-minikube-921-4baff83-1932-f15e/src/kubeflow/kubeflow/testing/test_deploy.py", line 265, in wr
ap_test
   test_util.wrap_test(run, test_case)
 File "/mnt/test-data-volume/kubeflow-presubmit-kubeflow-e2e-minikube-921-4baff83-1932-f15e/src/kubeflow/testing/py/kubeflow/testing/test_util.py", line 8
2, in wrap_test
   test_func()
 File "/mnt/test-data-volume/kubeflow-presubmit-kubeflow-e2e-minikube-921-4baff83-1932-f15e/src/kubeflow/kubeflow/testing/test_deploy.py", line 263, in ru
n
   args.func(args)
 File "/mnt/test-data-volume/kubeflow-presubmit-kubeflow-e2e-minikube-921-4baff83-1932-f15e/src/kubeflow/kubeflow/testing/test_deploy.py", line 466, in te
ardown_minikube
   final_op = vm_util.wait_for_operation(gce, args.project, args.zone, op_id)
 File "/mnt/test-data-volume/kubeflow-presubmit-kubeflow-e2e-minikube-921-4baff83-1932-f15e/src/kubeflow/kubeflow/testing/vm_util.py", line 42, in wait_fo
r_operation
   project=project, zone=zone, operation=op_id).execute()
 File "/usr/local/lib/python2.7/dist-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
   return wrapped(*args, **kwargs)
 File "/usr/local/lib/python2.7/dist-packages/googleapiclient/http.py", line 839, in execute
   method=str(self.method), body=self.body, headers=self.headers)
 File "/usr/local/lib/python2.7/dist-packages/googleapiclient/http.py", line 179, in _retry_request
   raise exception
ssl.SSLError: ('The read operation timed out',)
```

This is causing test flakes as in #921

**Comment by jlewi** [comment]
We no longer run minikube tests on presubmit so this is no longer blocking presubmits.

Removing from 0.3.0 since we are trying to narrow down the scope to get everything ready.

**Comment by jlewi** [comment]
Anyone working on this?
Should we punt to 0.5?
