### ISSUE TITLE
Presubmit failures; Timeout waiting for TFJob v1alpha2 job

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#974]
I'm seeing presubmit failures timing out waiting for TFJob

Example:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/kubeflow_kubeflow/967/kubeflow-presubmit/2032/

This errors seem like they are unrelated to my PR since I don't think my PR affects TFJob.

Logs from the tf-job-test pod are pasted below.

It looks like we tried to delete the job and then while waiting for the job we raised an exception because the job was not found. This seems like its working as intended because if we are waiting for the job to be
deleted we'd eventually expect the job to not exist.

I suspect when we added retry logic recently this bug crept in.

```
INFO|2018-06-11T13:43:18|/mnt/test-data-volume/kubeflow-presubmit-kubeflow-e2e-gke-967-4d8157a-2032-bf97/src/kubeflow/tf-operator/py/tf_job_client.py|71| Deleting job kubeflow.simple-tfjo
b-gke returned: {u'status': {u'phase': u'Done', u'reason': u'', u'replicaStatuses': [{u'tf_replica_type': u'MASTER', u'state': u'Succeeded', u'ReplicasStates': {u'Succeeded': 1}}, {u'tf_r
eplica_type': u'WORKER', u'state': u'Running', u'ReplicasStates': {u'Running': 1}}, {u'tf_replica_type': u'PS', u'state': u'Running', u'ReplicasStates': {u'Running': 2}}], u'state': u'Suc
ceeded'}, u'kind': u'TFJob', u'spec': {u'replicaSpecs': [{u'tfReplicaType': u'MASTER', u'tfPort': 2222, u'template': {u'spec': {u'restartPolicy': u'OnFailure', u'containers': [{u'image':
u'gcr.io/tf-on-k8s-dogfood/tf_sample:dc944ff', u'name': u'tensorflow', u'resources': {}}]}, u'metadata': {u'creationTimestamp': None}}, u'replicas': 1}, {u'tfReplicaType': u'WORKER', u'tf
Port': 2222, u'template': {u'spec': {u'restartPolicy': u'OnFailure', u'containers': [{u'image': u'gcr.io/tf-on-k8s-dogfood/tf_sample:dc944ff', u'name': u'tensorflow', u'resources': {}}]},
 u'metadata': {u'creationTimestamp': None}}, u'replicas': 1}, {u'tfReplicaType': u'PS', u'tfPort': 2222, u'template': {u'spec': {u'restartPolicy': u'OnFailure', u'containers': [{u'image':
 u'gcr.io/tf-on-k8s-dogfood/tf_sample:dc944ff', u'name': u'tensorflow', u'resources': {}}]}, u'metadata': {u'creationTimestamp': None}}, u'replicas': 2}], u'terminationPolicy': {u'chief':
 {u'replicaIndex': 0, u'replicaName': u'MASTER'}}, u'RuntimeId': u'q7t7', u'tfImage': u'tensorflow/tensorflow:1.3.0'}, u'apiVersion': u'kubeflow.org/v1alpha1', u'metadata': {u'name': u'si
mple-tfjob-gke', u'deletionTimestamp': u'2018-06-11T13:43:18Z', u'clusterName': u'', u'deletionGracePeriodSeconds': 0, u'namespace': u'kubeflow', u'generation': 0, u'finalizers': [u'foreg
roundDeletion'], u'resourceVersion': u'1172', u'creationTimestamp': u'2018-06-11T13:40:48Z', u'selfLink': u'/apis/kubeflow.org/v1alpha1/namespaces/kubeflow/tfjobs/simple-tfjob-gke', u'uid
': u'0c741ad4-6d7d-11e8-8dae-42010a8e008a'}}
INFO|2018-06-11T13:43:18|/mnt/test-data-volume/kubeflow-presubmit-kubeflow-e2e-gke-967-4d8157a-2032-bf97/src/kubeflow/tf-operator/py/test_runner.py|341| Waiting for job simple-tfjob-gke i
n namespaces kubeflow to be deleted.
ERROR|2018-06-11T13:43:18|/mnt/test-data-volume/kubeflow-presubmit-kubeflow-e2e-gke-967-4d8157a-2032-bf97/src/kubeflow/tf-operator/py/test_runner.py|49| rest.ApiException thrown
Traceback (most recent call last):
 File "/mnt/test-data-volume/kubeflow-presubmit-kubeflow-e2e-gke-967-4d8157a-2032-bf97/src/kubeflow/tf-operator/py/test_runner.py", line 47, in wait_for_delete
   tf_job_client.TF_JOB_PLURAL, name)
 File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/apis/custom_objects_api.py", line 697, in get_namespaced_custom_object
   (data) = self.get_namespaced_custom_object_with_http_info(group, version, namespace, plural, name, **kwargs)
 File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/apis/custom_objects_api.py", line 797, in get_namespaced_custom_object_with_http_info
   collection_formats=collection_formats)
 File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/api_client.py", line 321, in call_api
   _return_http_data_only, collection_formats, _preload_content, _request_timeout)
 File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/api_client.py", line 155, in __call_api
   _request_timeout=_request_timeout)
 File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/api_client.py", line 342, in request
   headers=headers)
 File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/rest.py", line 231, in GET
   query_params=query_params)
 File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/rest.py", line 222, in request
   raise ApiException(http_resp=r)
ApiException: (404)
Reason: Not Found
```

**Comment by jlewi** [comment]
wait_for_delete explicitly checks for Not Found here
https://github.com/kubeflow/tf-operator/blob/master/py/test_runner.py#L50

**Comment by jlewi** [comment]
I think this is a 404 is a red herring I think the code is just printing out the exception and then continuing. I don't think that's why the test actually failed.

**Comment by jlewi** [comment]
Looks like I was looking at the wrong test. It was the v1alpha2 job that timed out

```
ERROR|2018-06-11T13:50:24|/mnt/test-data-volume/kubeflow-presubmit-kubeflow-e2e-gke-967-4d8157a-2032-bf97/src/kubeflow/tf-operator/py/test_runner.py|354| Timeout waiting for simple-tfjob-
gke in namespace kubeflow to finish.
Traceback (most recent call last):
 File "/mnt/test-data-volume/kubeflow-presubmit-kubeflow-e2e-gke-967-4d8157a-2032-bf97/src/kubeflow/tf-operator/py/test_runner.py", line 280, in run_test
   api_client, namespace, name, args.tfjob_version, status_callback=tf_job_client.log_status)
 File "/mnt/test-data-volume/kubeflow-presubmit-kubeflow-e2e-gke-967-4d8157a-2032-bf97/src/kubeflow/tf-operator/py/tf_job_client.py", line 155, in wait_for_job
   name, namespace))
TimeoutError: Timeout waiting for job simple-tfjob-gke in namespace kubeflow to finish.
INFO|2018-06-11T13:50:24|/mnt/test-data-volume/kubeflow-presubmit-kubeflow-e2e-gke-967-4d8157a-2032-bf97/src/kubeflow/tf-operator/py/test_util.py|161| Creating /mnt/test-data-volume/kubef
low-presubmit-kubeflow-e2e-gke-967-4d8157a-2032-bf97/output/artifacts/junit_e2e-gke-v1a2.xml
```

**Comment by jlewi** [comment]
I did a quick sanity check to see if its a quota issue. At this exact instant we should have quota

```
gcloud --project=kubeflow-ci compute regions describe us-east1
creationTimestamp: '1969-12-31T16:00:00.000-08:00'
description: us-east1
id: '1230'
kind: compute#region
name: us-east1
quotas:
- limit: 320.0
  metric: CPUS
  usage: 177.0
- limit: 16384.0
  metric: DISKS_TOTAL_GB
  usage: 7225.0
- limit: 8.0
  metric: STATIC_ADDRESSES
  usage: 0.0
- limit: 128.0
  metric: IN_USE_ADDRESSES
  usage: 16.0
- limit: 500.0
  metric: SSD_TOTAL_GB
  usage: 10.0
- limit: 6000.0
  metric: LOCAL_SSD_TOTAL_GB
  usage: 0.0
- limit: 100.0
  metric: INSTANCE_GROUPS
  usage: 61.0
- limit: 50.0
  metric: INSTANCE_GROUP_MANAGERS
  usage: 5.0
- limit: 3200.0
  metric: INSTANCES
  usage: 16.0
- limit: 50.0
  metric: AUTOSCALERS
  usage: 0.0
- limit: 20.0
  metric: REGIONAL_AUTOSCALERS
  usage: 0.0
- limit: 20.0
  metric: REGIONAL_INSTANCE_GROUP_MANAGERS
  usage: 0.0
- limit: 0.0
  metric: PREEMPTIBLE_CPUS
  usage: 0.0
- limit: 24.0
  metric: NVIDIA_K80_GPUS
  usage: 6.0
- limit: 0.0
  metric: COMMITMENTS
  usage: 0.0
- limit: 200.0
  metric: INTERNAL_ADDRESSES
  usage: 0.0
- limit: 0.0
  metric: NVIDIA_P100_GPUS
  usage: 0.0
- limit: 0.0
  metric: PREEMPTIBLE_LOCAL_SSD_GB
  usage: 0.0
- limit: 0.0
  metric: PREEMPTIBLE_NVIDIA_K80_GPUS
  usage: 0.0
- limit: 0.0
  metric: PREEMPTIBLE_NVIDIA_P100_GPUS
  usage: 0.0
- limit: 0.0
  metric: NVIDIA_V100_GPUS
  usage: 0.0
- limit: 0.0
  metric: PREEMPTIBLE_NVIDIA_V100_GPUS
  usage: 0.0
- limit: 16.0
  metric: INTERCONNECT_ATTACHMENTS_PER_REGION
  usage: 0.0
- limit: 80000.0
  metric: INTERCONNECT_ATTACHMENTS_TOTAL_MBPS
  usage: 0.0
selfLink: https://www.googleapis.com/compute/v1/projects/kubeflow-ci/regions/us-east1
status: UP
zones:
- https://www.googleapis.com/compute/v1/projects/kubeflow-ci/zones/us-east1-b
- https://www.googleapis.com/compute/v1/projects/kubeflow-ci/zones/us-east1-c
- https://www.googleapis.com/compute/v1/projects/kubeflow-ci/zones/us-east1-d
```

**Comment by jlewi** [comment]
I used stackdriver to get the actual pod logs for this job using the following query

```
resource.type="container"
resource.labels.cluster_name="e2e-bf97-v1a2"
resource.labels.container_name = "tensorflow"
```

[Logs](https://pantheon.corp.google.com/logs/viewer?project=kubeflow-ci&resource=k8s_cluster%2Flocation%2Fus-east1-d%2Fcluster_name%2Fkubeflow-testing&minLogLevel=0&expandAll=false&timestamp=2018-06-11T20:59:49.019000000Z&customFacets=&limitCustomFacetWidth=true&dateRangeStart=2018-06-10T21:00:12.182Z&dateRangeEnd=2018-06-11T21:00:12.182Z&interval=P1D&scrollTimestamp=2018-06-11T13:42:22.000000000Z&advancedFilter=resource.type%3D%22container%22%0Aresource.labels.cluster_name%3D%22e2e-bf97-v1a2%22%0Aresource.labels.container_name%20%3D%20%22tensorflow%22%0A)

It looks like this is the mnist error downloading data that @pdmack Reported on slack.

```
Traceback (most recent call last): File "/var/tf_dist_mnist/dist_mnist.py", line 303, in <module> tf.app.run() File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 124, in run _sys.exit(main(argv)) File "/var/tf_dist_mnist/dist_mnist.py", line 110, in main mnist = input_data.read_data_sets(FLAGS.data_dir, one_hot=True) File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py", line 242, in read_data_sets train_images = extract_images(f) File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py", line 56, in extract_images magic = _read32(bytestream) File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py", line 38, in _read32 return numpy.frombuffer(bytestream.read(4), dtype=dt)[0] File "/usr/lib/python2.7/gzip.py", line 268, in read self._read(readsize) File "/usr/lib/python2.7/gzip.py", line 303, in _read self._read_gzip_header() File "/usr/lib/python2.7/gzip.py", line 197, in _read_gzip_header raise IOError, 'Not a gzipped file' IOError: Not a gzipped file
```

**Comment by jlewi** [comment]
Relevant stack trace

```
  File "/var/tf_dist_mnist/dist_mnist.py", line 303, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "/var/tf_dist_mnist/dist_mnist.py", line 110, in main
    mnist = input_data.read_data_sets(FLAGS.data_dir, one_hot=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py", line 242, in read_data_sets
    train_images = extract_images(f)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py", line 56, in extract_images
    magic = _read32(bytestream)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py", line 38, in _read32
    return numpy.frombuffer(bytestream.read(4), dtype=dt)[0]
  File "/usr/lib/python2.7/gzip.py", line 268, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 303, in _read
    self._read_gzip_header()
  File "/usr/lib/python2.7/gzip.py", line 197, in _read_gzip_header
    raise IOError, 'Not a gzipped file'
IOError: Not a gzipped file
```

**Comment by jlewi** [comment]
Looks like the source is here.
https://github.com/kubeflow/tf-operator/blob/master/test/e2e/dist-mnist/dist_mnist.py

**Comment by jlewi** [comment]
The logs indicate data was successfully downloaded 

```
Successfully downloaded train-images-idx3-ubyte.gz 257 bytes.
```

The size is suspicious; 257 bytes seems small but maybe I'm missing something.

Looks like an issue downloading the data:
https://github.com/tensorflow/tensorflow/issues/15668

We should probably make this test more robust by trying to skip the download (maybe store the data on GCS).

However, I'm not sure it makes to use mnist for a presubmit. It seems like we should be using a simpler smoke test like we do for v1alpha1.

**Comment by gaocegege** [comment]
I think we could use simple test instead.

**Comment by jlewi** [comment]
I believe we have stopped using mnist on presubmit and the presubmits are now fairly reliable.
