### ISSUE TITLE
presubmit failing:  couldn't open import "X": no match locally or in the Jsonnet library path

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#983]
```
INFO|2018-06-12T22:38:36|/src/kubeflow/testing/py/kubeflow/testing/util.py|62| level=error msg="find objects: RUNTIME ERROR: couldn't open import \"kubeflow/tf-serving/tf-serving.libsonnet\": no match locally or in the Jsonnet library paths\n\t<extvar:__ksonnet/components>:5:23-72\tthunk <tfServing> from <object <anonymous>>\n\t<extvar:__ksonnet/components>:21:20-29\tthunk <server> from <object <anonymous>>\n\t<extvar:__ksonnet/components>:(21:20)-(33:6)\tthunk <server> from <object <anonymous>>\n\t<extvar:__ksonnet/components>:36:7-13\tthunk from <thunk from <thunk from <object <anonymous>>>>\n\t<std>:1218:53-54\tthunk from <thunk from <function <anonymous>>>\n\t<std>:1216:24-25\tthunk from <thunk <t> from <function <anonymous>>>\n\t<builtin>\tbuiltin function <type>\n\t<std>:1217:8-9\tfunction <anonymous>\n\t<std>:1165:25-26\tthunk from <thunk <ta> from <function <anonymous>>>\n\t<builtin>\tbuiltin function <type>\n\t<std>:1167:29-31\tthunk from <function <anonymous>>\n\t<builtin>\tbuiltin function <primitiveEquals>\n\t<std>:1167:8-36\tfunction <anonymous>\n\t\t\n\t<std>:1218:45-55\tthunk from <function <anonymous>>\n\t<std>:1208:10-11\tfunction <isContent>\n\t<std>:1165:25-26\tthunk from <thunk <ta> from <function <anonymous>>>\n\t<builtin>\tbuiltin function <type>\n\t<std>:1167:29-31\tthunk from <function <anonymous>>\n\t<builtin>\tbuiltin function <primitiveEquals>\n\t<std>:1167:8-36\tfunction <anonymous>\n\t\t\n\t<std>:1218:35-56\tfunction <anonymous>\n\t<builtin>\tbuiltin function <flatMap>\n\t<std>:1222:20-35\tthunk from <function <anonymous>>\n\t<std>:1208:10-11\tfunction <isContent>\n\t<std>:1165:25-26\tthunk from <thunk <ta> from <function <anonymous>>>\n\t<builtin>\tbuiltin function <type>\n\t<std>:1167:29-31\tthunk from <function <anonymous>>\n\t<builtin>\tbuiltin function <primitiveEquals>\n\t<std>:1167:8-36\tfunction <anonymous>\n\t\t\n\t<std>:1222:10-36\tfunction <anonymous>\n\t<builtin>\tbuiltin function <flatMap>\n\t<builtin>\tbuiltin function <$objectFlatMerge>\n\t<extvar:__ksonnet/components>:(35:5)-(38:8)\tobject <anonymous>\n\tDuring manifestation\t\n"

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 320, in <module>
    final_result = main()
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 310, in main
    return run(args, file_handler)
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 183, in run
    util.run(["ks", "show", env, "-c", w.component], cwd=w.app_dir)
  File "/src/kubeflow/testing/py/kubeflow/testing/util.py", line 74, in run
    " ".join(command), process.returncode), "\n".join(output))
subprocess.CalledProcessError: Command 'cmd: ks show kubeflow-presubmit-tf-serving-image-979-4a8bc1c-2052-ebfd -c workflows exited with code 1' returned non-zero exit status 1
```

Is this ks version issue?

**Comment by lluunn** [comment]
we upgraded to ks 0.11 in https://github.com/kubeflow/testing/pull/155

**Comment by lluunn** [comment]
It's weird: 
it's doing `ks", "show", env, "-c", w.component` for the workflow, but gets import error from tf-serving.

similar to https://github.com/ksonnet/ksonnet/issues/502?

**Comment by lluunn** [comment]
cc @ankushagarwal  any idea?

**Comment by lluunn** [comment]
Also, the result page shows not finished, and no workflows:
<img width="1233" alt="screen shot 2018-06-12 at 16 37 03" src="https://user-images.githubusercontent.com/32310205/41322644-ee87463c-6e5e-11e8-8a2a-1799f67a720d.png">

**Comment by ankushagarwal** [comment]
That's odd. Should be related to the 0.11 upgrade. Does your PR #984 fix this issue?

**Comment by lluunn** [comment]
No. "./workflows.libsonnet" doesn't help.
I don't understand why and where it tries to import tf-serving, when doing ks show workflows

**Comment by jlewi** [comment]
But the presubmits passed in #984 
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/kubeflow_kubeflow/984/kubeflow-presubmit/2054/

**Comment by jlewi** [comment]
I can't reproduce running locally 

```
~/git_kubeflow/components/k8s-model-server/images/releaser$ ks show prow -c workflows
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: jlewi-tf-serving-release-v20180303-pr339-72bc7b1-98f7-98f7
  namespace: kubeflow-test-infra
spec:
...
```

**Comment by jlewi** [comment]
Gubernator link for the results mentioned above
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/kubeflow_kubeflow/982/kubeflow-presubmit/2050/?log#log

**Comment by lluunn** [comment]
It passed in  #984 because I was testing disabling that workflow.
It's specific to that workflow, but nothing has changed from what I can tell.

**Comment by lluunn** [comment]
I was able to repro locally with 0.11
```
00:11:35lunkai@None:releaser$ ks show prow -c workflows
ERROR find objects: RUNTIME ERROR: couldn't open import "kubeflow/tf-serving/tf-serving.libsonnet": no match locally or in the Jsonnet library paths
```
Even gpu_model failed with same reason
```
00:11:44lunkai@None:releaser$ ks show prow -c gpu_model
ERROR find objects: RUNTIME ERROR: couldn't open import "kubeflow/tf-serving/tf-serving.libsonnet": no match locally or in the Jsonnet library paths
```

**Comment by lluunn** [comment]
Actually, gpu_model is importing tf-serving
https://github.com/kubeflow/kubeflow/blob/master/components/k8s-model-server/images/releaser/components/gpu_model.jsonnet#L6

So if I remove gpu_model.jsonnet, `ks show prow -c workflows` works fine.

**Comment by lluunn** [comment]
We don't need gpu_model as our tf-serving component already covers that.
